### ISSUE TITLE
Ebook requires Microsoft corporate account to view

### ISSUE THREAD

**Issue by karenmattox** [dotnet/eShopOnContainers#105]
https://microsoft.sharepoint.com/teams/DotNetStrategyTeam/Shared%20Documents/Architecting%20and%20Developing%20Microservice-Docker%20Apps%20(Guide-eBook)

It's on a Microsoft sharepoint site that is accessible only with a corporate login (not a visual studio or msdn subscriber or windows live account, I tried all of those).

**Comment by CESARDELATORRE** [comment]
Sorry, that was a typo at the Wiki. It was right at the Repo Homepage/
The eBook URL for readers is this:
https://github.com/dotnet/eShopOnContainers/blob/master/docs/architecting-and-developing-containerized-and-microservice-based-net-applications-ebook-early-draft.pdf

I just updated the right URL at the Wiki. Can you confirm you see it right?
Thanks,

**Comment by karenmattox** [comment]
Yes I can get it now, thanks!
