### ISSUE TITLE
Upgrade Indentity Server 4 from RC3 to release version

### ISSUE THREAD

**Issue by larsontim12** [dotnet/eShopOnContainers#116]
Are you planning on upgrading this to use the release version of IdentityServer4.  It is currently using rc3 and when I upgrade the solution fails to work anymore.

**Comment by eiximenis** [comment]
Hi @larsontim12 
There are some breaking changes from rc3 to rtm of IS4. 

We'll take a look!

**Comment by CESARDELATORRE** [comment]
When migrating from Indentity Server 4 RC3 to its release version, we should also improve the token's lifetime management so it doesn't throw errors in special cases discussed in this other issue:
https://github.com/dotnet/eShopOnContainers/issues/118

**Comment by eiximenis** [comment]
Closed by #155
