### ISSUE TITLE
Post_update_product_price_and_catalog_and_basket_list_modified test failing

### ISSUE THREAD

**Issue by BillWagner** [dotnet/eShopOnContainers#129]
I ran all the tests on the dev branch today, and one is consistently failing.

This [test](https://github.com/dotnet/eShopOnContainers/blob/dev/test/Services/FunctionalTests/Services/IntegrationEventsScenarios.cs#L21) fails all three of the following asserts:
https://github.com/dotnet/eShopOnContainers/blob/dev/test/Services/FunctionalTests/Services/IntegrationEventsScenarios.cs#L59
https://github.com/dotnet/eShopOnContainers/blob/dev/test/Services/FunctionalTests/Services/IntegrationEventsScenarios.cs#L62
https://github.com/dotnet/eShopOnContainers/blob/dev/test/Services/FunctionalTests/Services/IntegrationEventsScenarios.cs#L63

It would appear that the update for the product price. does not happen.

However, on the same bits, I can run swagger and make a change to the product.

/cc @dsrodenas @CESARDELATORRE

**Comment by dsrodenas** [comment]
Fixed in commit 696610ed3636fd66584ed4ad12d14cdf3dbe693c 
I changed the route for the update in the controller but not in the test. Now the test has the correct routing.

**Comment by CESARDELATORRE** [comment]
Closing this one
