### ISSUE TITLE
MVC Launch fails with System.IdentityModel.TOkens.Jwt not found

### ISSUE THREAD

**Issue by dansand71** [dotnet/eShopOnContainers#131]
Launching the MVC app from VS or in a container results in this error.  Checked Nuget package manager and the package is installed.

System.IO.FileNotFoundException: 'Could not load file or assembly 'System.IdentityModel.Tokens.Jwt, Version=5.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.'

**Comment by CESARDELATORRE** [comment]
Have you set the "docker-compose" project as the by default start-up project in VS?
You need to launch the whole docker-compose solution, not a single container, as this is a "multi-container" microservices based application with multiple dependencies that you can see at the docker-compose files.

Also, important, please follow the [setting up procedure for Visual Studio 2017](https://github.com/dotnet/eShopOnContainers/wiki/02.-Setting-eShopOnContainer-solution-up-in-a-Visual-Studio-2017-environment), step by step. That is critical for the first time you are going to run the application.

Please, tell us if that solves your issue.

**Comment by CESARDELATORRE** [comment]
Closing. This issue was solved for Dan by using the right .sln and setting the docker-compose project as default startup.
