### ISSUE TITLE
[Xamarin App] Switch to AutoFac as IoC container instead of Unity

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/eShopOnContainers#147]
For the Xamarin app it would be better to use Autofac than Unity. 
I know that it is almost the same code for the Xamarin app and it won't change significantly, but Autofac is also the IoC container used in the Ordering microservice (the advanced microservice), so it would be aligned and most of all, Autofac is a more modern IoC container than Unity.

**Comment by davidbritch** [comment]
Note that this requires a change from PCL Profile 259 to Profile 111, which removes Windows Phone Silverlight 8 as a target framework for the PCL.

**Comment by CESARDELATORRE** [comment]
I think that would be ok, nowadays.
