### ISSUE TITLE
[Feedback] The web API does not follow common restful API guidelines

### ISSUE THREAD

**Issue by johnsonlu** [dotnet/eShopOnContainers#149]
E.g. in CatalogController, it uses 
- `POST api/v1/catalog/update` to update a product
- `POST api/v1/catalog/create` to create a product

According to most restful API guidelines, verbs(update, create) should be avoided in the path, instead using the correct HTTP verbs, e.g. PUT for update a resource, POST for create a resource.

One restful API guideline could be found here:
https://github.com/zalando/restful-api-guidelines

**Comment by CESARDELATORRE** [comment]
Agreed. We'll fix that.
Thanks for the feedback! :)


________________________________

**Comment by eiximenis** [comment]
Hi.
This is fixed in commit c85e880dad4b89541068e1edfa84c31eef7d809b

New endpoints are
- POST api/v1/catalog/items to create a new item
- PUT api/v1/catalog/items to update item

Both return "Location" header with the URL of the new/updated item.

**Comment by CESARDELATORRE** [comment]
Closing. But also mentioning that we're implementing basic REST requirements like resource orientation, driven by HTTP verbs, etc. but we're not implementing hypermedia. That could come in the future (it is a good thing to have in microservices) but it is not a priority for us right now.
If you see any other issue about REST compliance/improvement, please, re-open this issue and continue the thread/comments.
