### ISSUE TITLE
[Feedback] Publish physical-version of the book

### ISSUE THREAD

**Issue by tomkerkhove** [dotnet/eShopOnContainers#153]
Are there plans to publish a physical-version of the book?

**Comment by CESARDELATORRE** [comment]
We might do it. We have no specific plans with any particular Publisher, yet, but we'll try to start with a short number (like a few hundred printed books) of the DRAFT version by //BUILD, for attendees.
After that, we might publish it through any Publisher but our main goal it to make it available for free as eBook, so it reaches more folks in the community.

**Comment by tomkerkhove** [comment]
Thank you for considering this, going to close this issue then.
