### ISSUE TITLE
Visual Studio Build issue due to invalid NuGet packages. 

### ISSUE THREAD

**Issue by bobgodfrey** [dotnet/eShopOnContainers#1586]
It looks like there are some NuGet packages that are no longer hosted so i can't build the DEV branch.  

After clearing my NuGet package cache the solution no longer builds in visual studio. 

I originally found the issue when testing on a second dev box.  I had a fresh copy of windows installed.  the latest 3.0 and 3.1 SDK .net core installed.

Clone the Dev Repo
Clear your NuGet cache if you don't have a fresh install
Rebuild the dev branch
Error	NU1102	Unable to find package Microsoft.AspNetCore.DataProtection.Redis with version (>= 2.2.0-preview3-35458)
Error	NU1102	Unable to find package System.ValueTuple with version (>= 4.6.0-preview1-26829-04)
Error	NU1102	Unable to find package System.IO.Compression.ZipFile with version (>= 4.4.0-beta-24913-02)
Error	NU1102	Unable to find package Microsoft.AspNetCore.SignalR.Redis with version (>= 3.0.0-alpha1-34847)
Error	NU1102	Unable to find package Microsoft.AspNetCore.Razor.Design with version (>= 3.0.0-alpha1-10670)
Error	NU1102	Unable to find package Microsoft.AspNetCore.Hosting.Abstractions with version (>= 3.0.0-preview4-19123-01)
Error	NU1102	Unable to find package Microsoft.AspNetCore.DataProtection.Redis with version (>= 2.2.0-preview3-35458)
Error	NU1102	Unable to find package Microsoft.AspNetCore.Authentication with version (>= 3.0.0-preview4-19123-01)

**Comment by sughosneo** [comment]
Hi @bobgodfrey , thank you for reaching out. 

Right now, the `dev` branch is updated to support `.NET 5` specific changes. So if you need to install [.NET 5](https://dotnet.microsoft.com/download/dotnet/5.0) in your local environment to test out this application. You could also use docker containers to run the entire application. You can run the below commands from the **/src/** directory and get started with the `eShopOnContainers` immediately.

```text
docker-compose build
docker-compose up
```

Hope this helps !

**Comment by bobgodfrey** [comment]
Yes,  the update to .net 5 is great news.  I pulled down the latest and was able to build fine.
