### ISSUE TITLE
docker-compose ignoring .env 

### ISSUE THREAD

**Issue by Wosniak** [dotnet/eShopOnContainers#159]
I´m trying to run the solution with VS2017 Community, but I´m getting the following message when vs executes docker-compose:

---------------------------
Microsoft Visual Studio
---------------------------
The ESHOP_EXTERNAL_DNS_NAME_OR_IP variable is not set. Defaulting to a blank string.

The ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP variable is not set. Defaulting to a blank string.

build path C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\src\Web\WebMVC either does not exist, is not accessible, or is not a valid URL..

For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting
---------------------------

Running the docker-compose on powershell every thing looks fine...

It´s seems like running inside vs, composer is ignoring the .env file.

Tks for support

**Comment by ardalis** [comment]
I had this as well. Make sure you are not on the Edge docker for Windows install. Roll back to the stable install and try again. Remember to reset the docker settings for disk sharing and cpu/ram.

**Comment by CESARDELATORRE** [comment]
Yep. I just tested it with the following version (Docker Stable Version), today, with no issues:
![image](https://cloud.githubusercontent.com/assets/1712635/24831147/228834dc-1c49-11e7-812a-c091ae2552c0.png)

**Comment by Wosniak** [comment]
Thank you, guys.

I moved to the last stable docker for win and everything works like a charm!

Thank's once again for your support!

Eduardo Wosniak

2017-04-08 14:51 GMT-03:00 Cesar De la Torre <notifications@github.com>:

**Comment by CESARDELATORRE** [comment]
Closing the issue.
