### ISSUE TITLE
Login to SQL db fails

### ISSUE THREAD

**Issue by nandanu** [dotnet/eShopOnContainers#1590]
Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'Microsoft.eShopOnContainers.Service.IdentityDb'. This is with .net 5 version and running "docker compose build" and "docker compose up" in a terminal window.

**Comment by nandanu** [comment]
Running it in Visual Studio throws the exception
"Microsoft.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)"

Hope that helps.

**Comment by sughosneo** [comment]
Hi @nandanu, thank you for reaching out. 

It could be because of the `IdentityDb` wasn't created in the SQL container. 
If you want to clean up the existing containers and docker images and start the application from the scratch, you could follow the below steps.

- To do clean up 

```powershell

docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
docker volume rm $(docker volume ls -q)

```

> !IMPORTANT: Above commands will clean up all running containers and it's data in your MacOS/Workstation. So you want to be careful on that.

- To run the app 

```powershell
docker-compose up sqldata
```
Once it's ready to accept the new connection, then you can bring up the other container by using the following command from a separate terminal.

```powershell
docker-compose up
```

Hope this helps !

**Comment by ahems** [comment]
FYI I started with a new, freshly-cloned repo of eShopOnContainers this weekend, did a "docker-compose build"
followed by a "docker-compose up" as per the guidance on the front page and hit the same problem as @nandanu above. 
Although the clone was new, I did have a bunch of existing containers on my machine including a SQL server one - although none were related to eShopOnContainers. However the cleanup steps above cleaned all my containers out and fixed the problem in eShopOnContainers for me. Thank you @sughosneo!

**Comment by nandanu** [comment]
That worked! Thanks much @sughosneo!!

**Comment by sughosneo** [comment]
Great ! Thank you for the update. 
I am closing this issue as of now. Please feel free to reopen it, if you have any further questions.

**Comment by gauravkesharwani** [comment]
> Hi @nandanu, thank you for reaching out.
> 
> It could be because of the `IdentityDb` wasn't created in the SQL container. If you want to clean up the existing containers and docker images and start the application from the scratch, you could follow the below steps.
> 
> * To do clean up
> 
> ```powershell
> docker stop $(docker ps -aq)
> docker rm $(docker ps -aq)
> docker volume rm $(docker volume ls -q)
> ```
> 
> > !IMPORTANT: Above commands will clean up all running containers and it's data in your MacOS/Workstation. So you want to be careful on that.
> 
> * To run the app
> 
> ```powershell
> docker-compose up sqldata
> ```
> 
> Once it's ready to accept the new connection, then you can bring up the other container by using the following command from a separate terminal.
> 
> ```powershell
> docker-compose up
> ```
> 
> Hope this helps !

This worked! Thank you!!
