### ISSUE TITLE
Program used for diagraming

### ISSUE THREAD

**Issue by joshmouch** [dotnet/eShopOnContainers#1597]
What application do you use for the diagrams in your documentation?  You did a very nice job and I can't seem to do the same types of diagrams in the tools I'm using.

**Comment by leohickstein** [comment]
@joshmouch I am not entirely sure which tool was used on the slides/documentation, but I do know you can create similar ones using:
- Draw.io (https://www.draw.io) just go to New > Cloud template folder and check the already working templates
- CloudSkew (https://www.cloudskew.com) which will allow you to create cloud architecture diagrams for free

Both tools will provide you tons of cloud provider icon sets that you can play with.

**Comment by sughosneo** [comment]
Hi @joshmouch , thank you for reaching out. We have primarily used `PPT` to design most of the component diagrams. Few of occasions we have used `Microsoft Visio` as well. For e.g [Code Flow](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Code-Flow). 

Hope this helps !

**Comment by sughosneo** [comment]
Considering the original question has been answered, I am closing this issue as of now. Please feel free to reopen it, if needed.

Thank you.
