### ISSUE TITLE
Broken link in wiki

### ISSUE THREAD

**Issue by alikrc** [dotnet/eShopOnContainers#1598]
Hi, i want to update wiki, but seems like it's not editable by public. 

Problem is a link on this page is wrong, 
https://github.com/dotnet-architecture/eShopOnContainers/wiki/Docker-compose-deployment-files

#run-%22infrastructure%22-containers

should be 
#run-infrastructure-containers

**Comment by sughosneo** [comment]
Hi @alikrc , thank you for reporting this issue. Good catch !
Now, the wiki page is updated. You could check the latest changes. 

Also, please note wiki can't be edited directly but you could always share your feedback through an issue. Just like this one 👍 

Hope this helps !

**Comment by alikrc** [comment]
thanks!
