### ISSUE TITLE
NuGet Package certificate error

### ISSUE THREAD

**Issue by sughosneo** [dotnet/eShopOnContainers#1599]
**Description**

- Clone the `eShop` application
- Go to the `src` directory
- Run `docker-compose build`
- dotnet restore step fails with following error :

``` as expired. [/src/eShopOnContainers-ServicesAndWebApps.sln]
/src/Services/Ordering/Ordering.API/Ordering.API.csproj : error NU3028: Package 'Microsoft.NETCore.Targets 1.1.3' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain [/src/eShopOnContainers-ServicesAndWebApps.sln]
.......
```

**Status** : Under Investigations

This is issue is related to https://github.com/NuGet/Home/issues/8944 and NuGet team is actively looking into it https://twitter.com/nuget/status/1354455557541933056

**Comment by nishanil** [comment]
Original issue: https://github.com/NuGet/Home/issues/10491

**Comment by sughosneo** [comment]
Here is the PR https://github.com/dotnet-architecture/eShopOnContainers/pull/1601 that includes the temporary fix as mentioned in https://github.com/NuGet/Announcements/issues/49#issuecomment-768766265 until Debian 10 (Buster) and the .NET Docker SDK images have been republished.
