### ISSUE TITLE
Where to put validation logic?

### ISSUE THREAD

**Issue by alikrc** [dotnet/eShopOnContainers#1600]
For example before adding a product to cart/basket, i want to check for stock if there is any. Likewise where should i put this validation? 

[In this doc](https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/microservices) it says:

>Keep domain knowledge out of the gateway. The gateway should handle and route client requests without any knowledge of the business rules or domain logic. Otherwise, the gateway becomes a dependency and can cause coupling between services.

So Web.Shopping.HttpAggregator > BasketController > AddBasketItemAsync is not a good place to add this business rule, where should i put it in code? Also for cross cutting validation, should services call each other or should they talk via events here? I'm very confused here, any detailed explanation will be appreciated

**Comment by sughosneo** [comment]
Hi @alikrc, thank you for reaching out. 

Validation are usually implemented in the Domain model layer. For more details, please refer [Design validations in the domain model layer](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/domain-model-layer-validations)

If you want to explore more on Microservices related concepts you can check the [.NET microservices - Architecture](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/) guide which uses `eShopOnContainers` as reference application.

Hope this helps !

**Comment by alikrc** [comment]
I've studied a lot from both docs and source itself. My question is getting product stock data from catalog service and validating this stock before adding to basket. What i understood is it should be done in aggregate project. Also if stock is after adding the basket, it should be handled via event mechanism. 

For further info, following method seems very suitable for this validation

https://github.com/dotnet-architecture/eShopOnContainers/blob/c09191fb78e400e7e4cd2efb6c13201f71da37b8/src/ApiGateways/Web.Bff.Shopping/aggregator/Controllers/BasketController.cs#L30
