### ISSUE TITLE
AKS Deployment Issue using local copy

### ISSUE THREAD

**Issue by mina5500** [dotnet/eShopOnContainers#1604]
I have tried deploying latest eshop project using two methods.
AZURE CLI directly from github using dockerhub linnuxdev and this worked successfully 
Local copy from windows using cmd commands as in official documentation without changing anything in project using linuxlatest command  however it didn't work and all the deployed services are not ready 

Can you please assist if i should change any configuration in helm folders or not?

**Comment by sughosneo** [comment]
Hi @mina5500 , thank you for reaching out. 

I just wanted to make sure if you have followed all the steps mentioned in [deploy-your-local-images](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS)#deploy-your-local-images) and followed below command to deploy all the helm chart.

```powershell
.\deploy-all.ps1 -externalDns aks -aksName <aks-cluster-name> -aksRg <resource-group> -imageTag linux-latest -registry <container-registry>.azurecr.io -dockerUser <container-registry-user-name> -dockerPassword <container-registry-user-password> -useMesh $false
```

If you have already done that and still you are facing issue, then could you please share the output of the following commands ?

```powershell
kubectl get deployment
kubectl get ing
kubectl get pods
```
And if any of the specific pod which is not running you can also fetch and share the log for that pod with the helps of below mentioned command : 

```powershell
kubectl logs <pod-id>
```

**Comment by mina5500** [comment]
i depoyed again and everything worked fine... thanks
