### ISSUE TITLE
webmvc site name 

### ISSUE THREAD

**Issue by mina5500** [dotnet/eShopOnContainers#1607]
i want to know how to change my published site on aks to be without webmvc ( no subsite ) ... can you please advise and where it can be modified in helm files or in project

**Comment by mina5500** [comment]
any replies ??

**Comment by sughosneo** [comment]
Hi @mina5500, thank you for reaching out, and sorry for the delay in responding.

Yes, you could change the name of `webmvc` app for your customized deployment. For that, you need to make changes in the following places :

- `webmvc` helm chart 
- `app.yaml`
- `deploy-all` script (based on the platform)

Hope this helps !

**Comment by mina5500** [comment]
@sughosneo 

Thanks... can you please elaborate more the exact places if i want it to be on root with no subsite ( no webmvc)

**Comment by sughosneo** [comment]
Hi @mina5500 , Could you please explain more on what do you mean by "root with no subsite" ?

Thank you.

**Comment by mina5500** [comment]
I want site to be
www.mysite.com
Not 
www.mysite.com/webmvc

**Comment by sughosneo** [comment]
For that, you can change the `pathBase: /webmvc` in `values.yaml` file under `webmvc` helm chart directory.
You can modify that as `pathBase: /` to point it as root site.

Thank you.

**Comment by sughosneo** [comment]
Hi @mina5500 ,  just checking if you had a chance to look into this issue further. Thank you.

**Comment by mina5500** [comment]
It gave errors in deployment

**Comment by sughosneo** [comment]
> It gave errors in deployment

Could you please share the error message and related details ?

**Comment by sughosneo** [comment]
Hi @mina5500 , just checking if you had a chance to look into this issue further. Thank you.

**Comment by sughosneo** [comment]
I am closing this issue as of now. Please feel free to reopen if you have any further questions. 

Thank you.
