### ISSUE TITLE
About identity server 4 version

### ISSUE THREAD

**Issue by GreenShadeZhang** [dotnet/eShopOnContainers#1608]
I think the latest official version is 4.1.1, when to upgrade the version of identity server 4 in the project, or whether there is such a plan.

**Comment by sughosneo** [comment]
Hi @GreenShadeZhang, thank you for your suggestion. 

As of now, we don't have any immediate plan of updating the `Identity Server 4` to the latest version `4.1.1`. But if anyone submits a PR with the changes, we will be happy to review and merge the changes in the `dev` branch.

**Comment by GreenShadeZhang** [comment]
> Hi @GreenShadeZhang, thank you for your suggestion.
> 
> As of now, we don't have any immediate plan of updating the `Identity Server 4` to the latest version `4.1.1`. But if anyone submits a PR with the changes, we will be happy to review and merge the changes in the `dev` branch.

Hello, I have submitted a pr.
https://github.com/dotnet-architecture/eShopOnContainers/pull/1617

**Comment by erjain** [comment]
Considering IdentityServer is updated with Duende IdentityServer 6.2.0. I am closing this issue now.
