### ISSUE TITLE
Error with Chinese environment - hit F5 

### ISSUE THREAD

**Issue by bbs14438** [dotnet/eShopOnContainers#161]
18>Traceback (most recent call last):
18>  File "docker-compose", line 3, in <module>
18>  File "compose\cli\main.py", line 64, in main
18>  File "compose\cli\main.py", line 113, in perform_command
18>  File "compose\cli\command.py", line 36, in project_from_options
18>  File "compose\cli\command.py", line 99, in get_project
18>  File "compose\config\config.py", line 247, in find
18>UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 10: ordinal not in range(128)
18>Failed to execute script docker-compose
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018: “CleanWorkspace”任务意外失败。
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018: Microsoft.DotNet.Docker.CommandLineClientException: Traceback (most recent call last):
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:   File "docker-compose", line 3, in <module>
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:   File "compose\cli\main.py", line 64, in main
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:   File "compose\cli\main.py", line 113, in perform_command
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:   File "compose\cli\command.py", line 36, in project_from_options
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:   File "compose\cli\command.py", line 99, in get_project
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:   File "compose\config\config.py", line 247, in find
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018: UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 10: ordinal not in range(128)
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018: Failed to execute script docker-compose。
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018: 
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018: 有关更多疑难解答信息，请转到 http://aka.ms/DockerToolsTroubleshooting ---> Microsoft.DotNet.Docker.CommandLineClientException: Traceback (most recent call last):
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:   File "docker-compose", line 3, in <module>
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:   File "compose\cli\main.py", line 64, in main
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:   File "compose\cli\main.py", line 113, in perform_command
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:   File "compose\cli\command.py", line 36, in project_from_options
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:   File "compose\cli\command.py", line 99, in get_project
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:   File "compose\config\config.py", line 247, in find
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018: UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 10: ordinal not in range(128)
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018: Failed to execute script docker-compose
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:    在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:    在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:    在 Microsoft.DotNet.Docker.DockerComposeClient.<ExecuteAsync>d__18.MoveNext()
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:    --- 内部异常堆栈跟踪的结尾 ---
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:    在 Microsoft.DotNet.Docker.DockerComposeClient.<ExecuteAsync>d__18.MoveNext()
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018: --- 引发异常的上一位置中堆栈跟踪的末尾 ---
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:    在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:    在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:    在 Microsoft.DotNet.Docker.DockerComposeClient.<DownAsync>d__12.MoveNext()
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018: --- 引发异常的上一位置中堆栈跟踪的末尾 ---
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:    在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:    在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:    在 Microsoft.DotNet.Docker.DockerWorkspace.<CleanWorkspaceAsync>d__16.MoveNext()
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018: --- 引发异常的上一位置中堆栈跟踪的末尾 ---
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:    在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:    在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:    在 Microsoft.DotNet.Docker.BuildTasks.DockerBaseTask.Execute()
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:    在 Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
18>d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(208,5): error MSB4018:    在 Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
18>已完成生成项目“docker-compose.dcproj”的操作 - 失败。

**Comment by CESARDELATORRE** [comment]
@bbs14438 - What version of VS 2017 are you using? Chinese?, please, specify your environment.
Also, confirm if you already followed the setup instructions here:
https://github.com/dotnet/eShopOnContainers/wiki/02.-Setting-eShopOnContainer-solution-up-in-a-Visual-Studio-2017-environment

If you did, after you confirm your environment, I will add folks from the VS Tools for Docker, as it looks like a tooling issue of the UnicodeDecodeError when reading the docker-compose files...

**Comment by bbs14438** [comment]
@CESARDELATORRE  thank you.
yes,I do it.
my environment:
Microsoft Visual Studio Enterprise 2017 
版本 15.1 (26403.0) Release
VisualStudio.15.Release/15.1.0+26403.0
Microsoft .NET Framework
版本 4.7.02046

已安装的版本: Enterprise

Visual Basic 2017   00369-90000-00000-AA843
Microsoft Visual Basic 2017

Visual C# 2017   00369-90000-00000-AA843
Microsoft Visual C# 2017

Visual C++ 2017   00369-90000-00000-AA843
Microsoft Visual C++ 2017

Visual F# 4.1   00369-90000-00000-AA843
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio 包   8.6.00209.10
Application Insights Tools for Visual Studio

ASP.NET Web Frameworks and Tools 2017   5.2.50303.0
For additional information, visit https://www.asp.net/

ASP.NET 和 Web Tools 2017   15.0.30320.0
ASP.NET 和 Web Tools 2017

Azure App Service Tools v3.0.0   15.0.30209.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Fabric.DiagnosticEvents   1.0
Fabric 诊断事件

JavaScript UWP 项目系统   2.0
JavaScript UWP 项目系统

JavaScript 项目系统   2.0
JavaScript 项目系统

JavaScript 语言服务   2.0
JavaScript 语言服务

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Hive Query Language Service   2.2.5000.0
Language service for Hive query

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio VC 软件包   1.0
Microsoft Visual Studio VC 软件包

Mono Debugging for Visual Studio   Mono.Debugging.VisualStudio
Support for debugging Mono processes with Visual Studio.

NuGet 包管理器   4.1.0
Visual Studio 中的 NuGet 包管理器。有关 NuGet 的详细信息，请访问 http://docs.nuget.org/。

SQL Server Data Tools   15.1.61702.140
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   2.1.5.0
用于 Visual Studio 的 TypeScript 工具

Visual Studio Tools for Universal Windows Apps   15.0.26403.00
Visual Studio Tools for Universal Windows Apps 让你能够构建一种通用的应用体验，运行 Windows 10 的每种设备都可以获得这种体验，如手机、平板电脑、PC 等。它包含 Microsoft Windows 10 软件开发工具包。

Xamarin   4.4.0.34 (3f99c5a)
用于启用 Xamarin.iOS 和 Xamarin.Android 的开发的 Visual Studio 扩展。

Xamarin.Android SDK   7.2.0.7 (b16fb82)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   10.8.0.174 (7656cc6)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

通用 Azure 工具   1.9
通过 Azure 移动服务和 Microsoft Azure Tools 提供通用服务。

**Comment by bbs14438** [comment]
@CESARDELATORRE Yes,I'm Chinese.

**Comment by bbs14438** [comment]
@CESARDELATORRE This error occurs when the path contains Chinese.

**Comment by CESARDELATORRE** [comment]
Have you tried to deploy by just using the Docker CLI following these instructions?:
https://github.com/dotnet/eShopOnContainers/wiki/03.-Setting-the-eShopOnContainers-solution-up-in-a-Windows-CLI-environment-(dotnet-CLI,-Docker-CLI-and-VS-Code)

I would be good to isolate if the issue is related to VS 2017 or Docker itself.
Thanks,

**Comment by CESARDELATORRE** [comment]
Can you also try to isolate if your issue is related to this known issue in docker-compose which is still open at Docker?: 
https://github.com/docker/compose/issues/3817

In that case, the workaround is to use a Windows username with only ASCII characters...

**Comment by CESARDELATORRE** [comment]
The VS Tools for Docker just confirmed that it’s due to Chinese characters in the docker-compose file path. It’s a limitation of docker-compose. There are a couple of issues logged on that repo to track this.
https://github.com/docker/compose/issues/4376
https://github.com/docker/compose/issues/4122

**Comment by bbs14438** [comment]
@CESARDELATORRE Thank you，My English is poor, I will try later .
