### ISSUE TITLE
Sorry, there was an error : unauthorized_client

### ISSUE THREAD

**Issue by YiMing668** [dotnet/eShopOnContainers#1613]
![img](https://user-images.githubusercontent.com/48082918/108957226-13964600-76ac-11eb-9078-13d9d306b05b.png)

**Comment by sughosneo** [comment]
Hi @YiMing668 , thank you for reaching out. 
You may want to check [unauthorized_client error on Login](https://github.com/dotnet-architecture/eShopOnContainers/wiki/unauthorized_client-error-on-login) for more details.

**Comment by sughosneo** [comment]
Hi @YiMing668 , just checking if you had a chance to look into this issue further. Thank you.

**Comment by sughosneo** [comment]
Hi @YiMing668 , I am closing this issue as of now. Please feel free to reopen it if you have any further questions.

Thank you.
