### ISSUE TITLE
Issue webspa: ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by D4mo** [dotnet/eShopOnContainers#1616]
Hi, I got this error while trying to execute "docker-compose build" on webspa

Step 10/58 : RUN npm i npm@latest -g && npm update && npm install && npm run build:prod
 ---> Running in 4015b35d1f2a
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@7.6.0
added 69 packages from 33 contributors, removed 203 packages and updated 184 packages in 15.321s
(node:26) ExperimentalWarning: The fs.promises API is experimental
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: eshopaspnetnetcoredockerspa@0.0.0
npm ERR! Found: typescript@3.4.5
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"3.4.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"3.9.x || 4.0.x" from typedoc@0.19.2
npm ERR! node_modules/typedoc
npm ERR!   typedoc@"^0.19.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-27T16_00_53_888Z-debug.log
ERROR: Service 'webspa' failed to build : The command '/bin/sh -c npm i npm@latest -g && npm update && npm install && npm run build:prod' returned a non-zero code: 1
 
Thanks,

**Comment by sughosneo** [comment]
Hi @D4mo, thank you for reaching out. 

I could see that you are using `npm@7.6.0` for building the `webspa`. As of now, we have reverted the npm to use version `6.14.11` for the issue `ERESOLVE unable to resolve dependency tree` with the latest npm package.

![image](https://user-images.githubusercontent.com/13281246/109455881-98eb7300-7a7d-11eb-9316-006556363359.png)

Could you please take the latest from the `dev` branch and try to build the eShop again using the command `docker-compose build` ?

Hope this helps !

**Comment by D4mo** [comment]
HI @sughosneo, thank you for your quick response.

I am getting a new error (about docker image) after the last pull. I think is something local, I will try to fix it and get back with the details.

thanks,

**Comment by sughosneo** [comment]
Hi @D4mo , thank you for the update. You may want to clean up the existing docker images. If you are using the `Docker Desktop` then you can use **"Clean/Purge data"** feature to remove all the data.

**Comment by D4mo** [comment]
Hi @sughosneo , It's working as expected, I am closing this one. thanks!
