### ISSUE TITLE
[Question] Update on Blazor support

### ISSUE THREAD

**Issue by n-stefan** [dotnet/eShopOnContainers#1618]
Hello,

are there any updates on potential Blazor support?
While waiting for it I've developed a Blazor WebAssembly client for eShopOnContainers, to evaluate Blazor in such a project.
Found it overall nice to work with; IMHO Blazor support makes sense, even if it doesn't replace Angular.

Thanks in advance

**Comment by sughosneo** [comment]
Hi @n-stefan, thank you for your feedback.

As of now, we don't have any immediate plan to incorporate Blazor support in `eShopOnContainers` reference application. 
There has been a similar discussion happening in one of similar project [eShopOnDapr](https://github.com/dotnet-architecture/eShopOnDapr)
For more details, you may want to refer to the actual issue https://github.com/dotnet-architecture/eShopOnDapr/issues/18

**Comment by n-stefan** [comment]
I see, thanks.
A couple of issues I've encountered: couldn't get debugging to work and authentication + prerendering didn't really mix.
Though both should be fixed, in time.

**Comment by sughosneo** [comment]
Hi @n-stefan , are you referring something related to `eShopOnDapr` ?

**Comment by n-stefan** [comment]
Hi @sughosneo,
no, sorry for the confusion, I meant issues I've encountered while developing a Blazor WebAssembly client for `eShopOnContainers`.

**Comment by sughosneo** [comment]
That's fine @n-stefan 👍  I get it now.

**Comment by sughosneo** [comment]
I am closing this issue now, as it has already been answered. Please feel free to reopen or create a new one, if needed. Thank you.
