### ISSUE TITLE
Reg: StackExchange. Redis

### ISSUE THREAD

**Issue by amarendratollplus** [dotnet/eShopOnContainers#1619]
Hello Marc Gravell,

The details you had provided here: https://stackexchange.github.io/StackExchange.Redis/, were very good and easy to understand.  I have a question to you:  Here to view all the keys and values, can we use Redis Desktop Manager?  If not, please let me know how we can see all the keys and values that were added in Redis.

Regards,
Amarendra.

**Comment by sughosneo** [comment]
Hi @amarendratollplus , thank you for reaching out. 
You may want to raise this an issue in the correct repository [StackExchange.Redis](https://github.com/StackExchange/StackExchange.Redis/issues?q=is%3Aopen). 

I am closing this issue as of now, as this is not relevant. If you have any other questions related to `eShopOnContainers`, please feel free to reach out.
