### ISSUE TITLE
Cannot login IdentityDB because login failed for user 'sa'

### ISSUE THREAD

**Issue by yuvalitah** [dotnet/eShopOnContainers#1620]
Hi :)
I'm having a problem when I run docker-compose up. The Identity service gives me the following error "Cannot open database "Microsoft.eShopOnContainers.Service.IdentityDb" requested by the login. The login failed. Login failed for user 'sa'.
Can someone help me with this plz? 
Thanks!

**Comment by DavyGuedes** [comment]
Hi @yuvalitah, how did you solve this issue?

--edit
https://github.com/dotnet-architecture/eShopOnContainers/issues/1590
