### ISSUE TITLE
Ordering HTTP Background Check health check not passes because "Name or service not known"

### ISSUE THREAD

**Issue by yuvalitah** [dotnet/eShopOnContainers#1621]
Hi :)
I'm trying to run the program but I have one service that doesn't pass because "Name or service not known (ordering-backgroundtasks:80)"
Anyone knows why is this happening?
Thanks!

![image](https://user-images.githubusercontent.com/62797164/109952649-bde31e80-7ce7-11eb-866d-b00e885c3294.png)

**Comment by sughosneo** [comment]
Hi @yuvalitah , thank you for reaching out. Are you trying to run the services as `docker-compose` ? If yes, could you please see the docker container logs ? You can do that by following below commands : 

- Identify the `ordering.backgroundtasks` docker container 
```powershell
docker ps -a | Select-String "background"
```
> !NOTE Or you can `grep` the container id based on the OS you are using. 

- Then check the docker logs 

```powershell
docker logs <container-id>
```

**Comment by yuvalitah** [comment]
@sughosneo It seems like it can't connect to RabbitMQ for some reason.. do you have any idea why it could happen?
![image](https://user-images.githubusercontent.com/62797164/110097573-e0d50780-7da7-11eb-8e5a-e3027a9cbaa0.png)

**Comment by sughosneo** [comment]
Hi @yuvalitah - thanks for the update. Could you please check if your RabbitMQ docker container is running properly ?
You can check that with docker command as mentioned below  :

```powershell
docker ps -a | Select-String "rabbit"
```

Or you can use the RabbitMQ UI at http://localhost:15672/

**Comment by sughosneo** [comment]
Hi @yuvalitah , just checking if you had a chance to look into this issue further. Thank you.

**Comment by sughosneo** [comment]
Hi @yuvalitah , I am closing this issue as of now. Please feel free to reopen it if you have any further questions. 

Thank you.
