### ISSUE TITLE
[Question] why OrderQueries implementation not in the Infrastructure?

### ISSUE THREAD

**Issue by jzhouw** [dotnet/eShopOnContainers#1628]
[OrderRepository](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.Infrastructure/Repositories/OrderRepository.cs),  implementation of IOrderRepository  used by command is located in Infrastructure layer 

But [OrderQueries ](https://github.com/dotnet-architecture/eShopOnContainers/blob/873cdf8cefa46fa7bb4eb455925eee67101e44a2/src/Services/Ordering/Ordering.API/Application/Queries/OrderQueries.cs#L22), the implementation of OrderQuery used by query shouldn't be in the Infrastructure layer too?

**Comment by sughosneo** [comment]
Hi @jzhouw, thank you for reaching out. 

`Martin Fowler` describes a repository as follows:

`A repository performs the tasks of an intermediary between the domain model layers and data mapping, acting in a similar way to a set of domain objects in memory. Client objects declaratively build queries and send them to the repositories for answers. Conceptually, a repository encapsulates a set of objects stored in the database and operations that can be performed on them, providing a way that is closer to the persistence layer. Repositories, also, support the purpose of separating, clearly and in one direction, the dependency between the work domain and the data allocation or mapping.`

In that aspect if you would notice repositories need stay closer with the infrastructure layer where as query layer should be residing with application where actual data mapping happens.

For more details you can refer [Design the infrastructure persistence layer](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-design)

Hope this helps !

**Comment by jzhouw** [comment]
hi @sughosneo thanks.  I got above question when seeing Ordering.API package depends on Dapper (infrastructure) directly. I got it is because closer to the data mapping and uses dto/viewmodel as query's output. So is this an exception when introduce direct dependency to infrastructure in presentation/application layer?

If so, in application layer to call an external web api, should I define the IThirdParyCall in this layer and implement it in infrastructure layer, or just implement in the same application layer? what would you advice? thanks

**Comment by jzhouw** [comment]
found this old post very informative. thanks
https://github.com/dotnet-architecture/eShopOnContainers/issues/592
