### ISSUE TITLE
[Feedback] Code Execution on Windows 8.1 with VS2017

### ISSUE THREAD

**Issue by ajaysingh77** [dotnet/eShopOnContainers#163]
I know that one of the dependency for current codebase to run is "Docker for winzdows" which only supports Windows 10. I tried to create windows 10 with nested virtualization enabled for Hyper-v but didn't work out as my host OS (windows 8.1) doesn't support nested virtualization.  
Any plan to support the code execution to work on Windows 8.1 with VS2017? if not any any guidance and resource pointer would be appreciated.

**Comment by CESARDELATORRE** [comment]
@ajaysingh77 The requirements for this solution is basically "Docker".
So, you have the requirements that Docker Community Edition (aka. Docker for Windows/Mac) or Docker Enterprise Edition have. From Microsoft, we cannot change Docker's requirements.
The requirements are explained here:
https://github.com/dotnet/eShopOnContainers/wiki/00.-Dev-machine-requirements

Using Windows 8.x with Docker is out of the scope of Microsoft. That should be a question for Docker, I think.

The other option you have is to deploy the solution to a regular Linux Docker Host, but just for testing/deploying/running, not for a development environment with Visual Studio 2017.
Similar option if choosing Windows Server 2016 to deploy Windows Containers, but just for testing/deploying/running, not for a development environment with Visual Studio 2017.
