### ISSUE TITLE
Comple docker-compose.override.yml for Mac

### ISSUE THREAD

**Issue by jeffreywstevens** [dotnet/eShopOnContainers#1631]
My docker-compose.override.yml file webmvc: section that is supposed to be edited looks nothing like the description on the Mac instructions page.  

Is there a complete perfectly edited docker-compose.override.yml for the Mac somewhere?  My editing is butchering it and still unsuccessful.

**Comment by sughosneo** [comment]
Hi @jeffreywstevens, thank you for reaching out. 

The existing `docker-compose.override.yml` file should work fine in MacOS as well. Are you seeing any specific error message, while running the app ?

You can try the below steps :

In `Docker Desktop for Mac` :

- Clean up the existing docker images and data volumes using the **Clean/Purge data** feature.
- Under the **Resources/FILE SHARING** option right path is mounted. (You can delete the existing entry and add it back again)

Once the cleanup is done, then you need to rebuild the images for running that application. You can do that by using the following steps.

- You can go the directory `~/eShopOnContainers/src`
- Go to the `.env` file. 
- Choose the right DNS :
    Uncomment : 
       ```
        ESHOP_EXTERNAL_DNS_NAME_OR_IP=docker.for.linux.localhost
        ESHOP_STORAGE_CATALOG_URL=http://docker.for.linux.localhost:5202/c/api/v1/catalog/items/[0]/pic/
      ```
    and comment out :
       ```
         #ESHOP_EXTERNAL_DNS_NAME_OR_IP=host.docker.internal
         #ESHOP_STORAGE_CATALOG_URL=http://host.docker.internal:5202/c/api/v1/catalog/items/[0]/pic/
       ```
- Run the command `docker-compose build`
- And after that `docker-compose up`
- You should be able to access the `webmvc` app using `http://docker.for.linux.localhost:5100`

Hope this helps !

**Comment by sughosneo** [comment]
Hi @jeffreywstevens , just checking if you had a chance to try out the above mentioned steps. Thank you.

**Comment by BruceVS-RR** [comment]
Yes this worked for me too, only thing that is required now is to edit the .env file as described.
It is only the mac config pages here that are out of date.

Note that there is still an issue with the webmvc app somewhere that is still referencing localhost. I've updated the appsettings on that project and redeployed/restarted but not working yet. identity is still seeing the incomming redirect url as localhost which is incorrect.

I'm still digging but here's the log:
{"ClientId": "mvc", "ClientName": "MVC Client", "RedirectUri": null, **_"AllowedRedirectUris": ["http://docker.for.mac.localhost:5100/signin-oidc"]_**, "SubjectId": "anonymous", "ResponseType": null, "ResponseMode": null, "GrantType": null, "RequestedScopes": "", "State": null, "UiLocales": null, "Nonce": null, "AuthenticationContextReferenceClasses": null, "DisplayMode": null, "PromptMode": null, "MaxAge": null, "LoginHint": null, "SessionId": null, "Raw": {"client_id": "mvc", **_"redirect_uri": "http://localhost:5100/signin-oidc"_**, "response_type": "code id_token", ...

**Comment by sughosneo** [comment]
Hi @BruceVS-RR , thank you for the update. 

That could be because of the old value in Identity Database. Could you please try the following steps ?

- To do clean up 

```

docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
docker volume rm $(docker volume ls -q)

```

> !IMPORTANT: Above commands will clean up all running containers and it's data in your MacOS/Workstation. So you want to be careful on that.

- To run the app 
- Go to the `/src/` directory

```
docker-compose up sqldata
```
Once it's ready to accept the new connection, then you can bring up the other container by using the following command from a separate terminal/window.

```
docker-compose up
```

**Comment by BruceVS-RR** [comment]
Hi,

Yes, it works.
Note that the document for Mac still directs you to use http://localhost:5100/ to test the site.
But it should be http://docker.for.mac.localhost:5100/ else the signin won't work.

But all sorted now, thanks!

**Comment by sughosneo** [comment]
Thanks for the update @BruceVS-RR 

As of now, I am closing this issue. Please feel free to reopen it, if needed.
