### ISSUE TITLE
Getting the error "unauthorized_client" when trying to login

### ISSUE THREAD

**Issue by KarimGhallab** [dotnet/eShopOnContainers#1633]
Hello everyone, I just cloned the repo and launched it via docker. The app starts (no problem going to `http://host.docker.internal:5100/`) well but when I try to login, i get the following error : `Sorry, there was an error : unauthorized_client`.
![image](https://user-images.githubusercontent.com/18572297/111987947-1dc32d00-8b10-11eb-9f5a-711cb6c6d133.png)

I browsed though the docs and find out that the error could come from the content of the `[Microsoft.eShopOnContainers.Service.IdentityDb].[dbo].[ClientRedirectUris]` table.
So when a list all the content of this table, this is the result i have : 
![image](https://user-images.githubusercontent.com/18572297/111987860-03894f00-8b10-11eb-8917-122a4687a0ec.png)

This result is rather strange since the URLs do not match the ones that should be present. Those URLs should start with : `http://http://host.docker.internal/...` if I'm not mistaken.

To give more intel, i ran the docker command within the `src` dir.

**Comment by sughosneo** [comment]
Hi @KarimGhallab, thank you for reaching out. 

It seems like data of `IdentityDb` wasn't populated properly. 
You can clean up the existing containers and docker images and start the application from the scratch, For that you can follow below steps.

- To do clean up 

```powershell

docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
docker volume rm $(docker volume ls -q)

```

> !IMPORTANT: Above commands will clean up all running containers and it's data in your MacOS/Workstation. So you want to be careful on that.

- To run the app 

```powershell
docker-compose up sqldata
```
Once it's ready to accept the new connection, then you can bring up the other container by using the following command from a separate terminal.

```powershell
docker-compose up
```

Hope this helps !

**Comment by KarimGhallab** [comment]
Thanks for your response, I will try that and keep you in touch ;)

**Comment by KarimGhallab** [comment]
I just followed you indication and now everything works fine !
Thank for your help !
