### ISSUE TITLE
[Question] Learning Path and resources to Using Azure Kubernetes Service and HELM for a multi container ASP.NET CORE app

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/eShopOnContainers#1634]
I want to learn how to depoy a multi container app to AKS, like this great demo app below
https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS)

Can anyone recommend learning resources about using AKS including deployment to AKS, communication between containers etc?

Under this folder, there are many *.yaml files, and file under helm folder, and *.ps1 files.
https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/deploy/k8s

What are the minimum topics I should start learning to have a hello world two-containers .NET based app (e.g. API and db) using AKS?

**Comment by sughosneo** [comment]
Hi @PingPongSet, thank you for reaching out. 

You may want to get started with the following tutorials. 

- [Hello World Microservice tutorial](https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/intro)
- [Create and deploy a cloud-native ASP.NET Core microservice](https://docs.microsoft.com/en-us/learn/modules/microservices-aspnet-core/)
- [Deploy a cloud-native ASP.NET Core microservice with GitHub Actions](https://docs.microsoft.com/en-us/learn/modules/microservices-aspnet-core/)
- [Implement resiliency in a cloud-native ASP.NET Core microservice](https://docs.microsoft.com/en-us/learn/modules/microservices-resiliency-aspnet-core/)

Hope this helps !

**Comment by PingPongSet** [comment]
@sughosneo  thanks for the links.

The 2nd and 3rd links you provided are the same.

I think you wanted to provide this below:
https://docs.microsoft.com/en-gb/learn/modules/microservices-devops-aspnet-core/

These labs are good starting points. But I want to learning it systematically all relevant topics.

The problem is the communication between containers, which, I guess, are covered by Helm, and probably Kubernetes too.

Can anyone point out relevant topics to learn for deploying a Hello world multi containers app in ASP.NET Core to AKS, for an experienced ASP.NET CORE developer? For example, settings for communication between containers, networking (e.g. loadbalancer) for public requests.

**Comment by sughosneo** [comment]
Hi @PingPongSet , sorry for the confusion. Yes, you are right. Actually, this [.NET Microservices](https://docs.microsoft.com/en-us/users/dotnet/collections/8mq4i2mzgjwn10) link has all the necessary learning module.

To clarify, `Helm` is just the package manager for the kubernetes. It helps to deploy and manage application which runs on the kubernetes.  The networking and other aspects of the containers get managed by the kubernetes cluster itself. 

For more details, you can also refer following links : 

- [Tutorial: Create a multi-container app with Docker Compose](https://docs.microsoft.com/en-us/visualstudio/containers/tutorial-multicontainer?view=vs-2019)
- [Quickstart: Develop on Azure Kubernetes Service (AKS) with Helm](https://docs.microsoft.com/en-us/azure/aks/quickstart-helm)
- [Tutorial: Prepare an application for Azure Kubernetes Service (AKS)](https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-prepare-app)

**Comment by sughosneo** [comment]
Hi @PingPongSet , all the cloud-native and microservices related learning modules can be found under this page [Learn Cloud-Native Architecture and Microservices](https://dotnet.microsoft.com/learn/microservices)

**Comment by sughosneo** [comment]
Considering the original question has been addressed, I am closing this issue as of now. 
Please feel free reopen this if needed.  Thank you.
