### ISSUE TITLE
Gateway timeout

### ISSUE THREAD

**Issue by rasikasamarakoon** [dotnet/eShopOnContainers#1635]
Hi Team,
I have installed docker desktop and I am trying to run the containers locally with docker compose up. However the urls localhost:5107, localhost:5100 etc.. all end up with http 504(Gateway timeout) error. I am using linux containers. Can you please help ?

**Comment by sughosneo** [comment]
Hi @rasikasamarakoon, thank you for reaching out. 

It will be hard to comment on the reason behind this `Gateway Timeout error` without seeing the status or logs of each container. Are all the containers up and running fine ? Could you please try to run the app again ?

- You can clean up the existing docker containers and images. To do that, please follow below steps :

```powershell

docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
docker volume rm $(docker volume ls -q)

```

> !IMPORTANT: Above commands will clean up all running containers and it's data in your MacOS/Workstation. So you want to be careful of that.

- To run the app 

```powershell
docker-compose up sqldata
```
- Once it's ready to accept the new connection, then you can bring up the other container by using the following command from a separate terminal.

```powershell
docker-compose up
```

**Comment by rasikasamarakoon** [comment]
Thank you @sughosneo after cleaning up it started working.

**Comment by sughosneo** [comment]
Great ! Thanks for the update @rasikasamarakoon  Closing this issue as of now.
