### ISSUE TITLE
[Question] Deploy to AKS: both Docker compose and Helm are used in the deployment

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/eShopOnContainers#1639]
The command below are used to as part of deployment.
`docker-compose build`

However, it means that both Docker compose and Helm are used in the deployment.

Is it possible to use Helm only which can simply the code base? 

Because currently, it is using various tools including Docker compose, Helm, DevSpace, making it difficult for beginners to learn.

If so, links or learning resources on this would be appreciated.

**Comment by sughosneo** [comment]
Hi @PingPongSet , thank you for reaching out. 

Yes, you are right both the `docker-compose` and `kubernetes` manifest (managed by `helm`) deployment strategies are kept for the orchestration of the containers.

`docker-compose` - is for the local run and getting started. 
`kubernetes` - is primary to show the production deployment.

If you are new to `cloud-native` and `microservices`, then you can refer [Learn Cloud-Native Architecture and Microservices](https://dotnet.microsoft.com/learn/microservices)

Hope this helps !

**Comment by sughosneo** [comment]
Hi @PingPongSet , I am closing this issue as it has already been answered. 
Please feel free to reopen it if you have any further questions on this topic. 

Thank you.
