### ISSUE TITLE
Response status code does not indicate success: 503 (Service unavailable) error

### ISSUE THREAD

**Issue by krchome** [dotnet/eShopOnContainers#1642]
I have cloned the code for this project on my Windows 10 machine and using Visual Studio 2019 Community version 16.8.1
I have also updated the docker desktop for windows with the latest version and as required for docker-compose the docker for desktop is kept running before building and running the solution
Issue: 
When I run the solution eShopOnContainers-ServicesAndWebApps, it builds but ends up in a runtime error the stack trace is as attached:
![Capture](https://user-images.githubusercontent.com/8474855/113831153-6a2e8e00-97db-11eb-9295-025cb86b8b69.JPG)
Can some one help address this issue

**Comment by sughosneo** [comment]
Hi @krchome, thank you for reaching out. 

Could you please check if all the containers are up and running ? You can use the `docker ps -a` command to see that.

Did you also try to run the app using `docker compose` ? You can do that by using the following steps :

- To do clean up 

```powershell

docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
docker volume rm $(docker volume ls -q)

```

> !IMPORTANT: Above commands will clean up all running containers and it's data in your MacOS/Workstation. So you want to be careful on that.

- To run the app 
- Go to the `/src/` directory

```powershell
docker-compose up sqldata
```
Once it's ready to accept the new connection, then you can bring up the other container by using the following command from a separate terminal/window.

```powershell
docker-compose up
```

**Comment by krchome** [comment]
Hi  @sughosneo,
Thanks for proposing a solution. Today when I tried running the application by hitting green Docker Compose arrow in VS, it worked and brought the required page on loading.
I then tried to run the app a second time after stopping it again by the above process, when it ended in the same runtime error as earlier mentioned.
The third time, I followed your instructions and issued docker commands as above, but after accepting the new sql connection the docker-compose up command would still run after several hours without an end in sight. So terminated the powershell window.

**Comment by sughosneo** [comment]
Thank you for the update @krchome

Did you check if all the containers are running during the second Visual Studio run ? You can do that using the `docker ps -a` command. Please note, Visual Studio (F5 experience) uses a different set of docker images (with `dev` tag) than when you are using the docker-compose up command (with `linux-latest` tag) from your terminal window. So you may want to check if all respective containers (with `dev` tag) are running fine or not.

Also, if you see a 503 error for any specific service, you can check the logs of that specific unavailable container to see more details.

**Comment by krchome** [comment]
When I run the application again with VS debugger (F5) it didn't build with this error (several times with the 
same error):
	Cannot launch container because the following port(s) are already in use: 5103, 9103, 5101, 9101, 5105, 5120, 5102, 9102, 5111, 5112, 5108, 5113, 5114, 5100, 5121, 5104, 5107	

I have attached the screendump of docker-compose ps -a (for you to have a look at `dev` and `linux-latest` tags. 
[eShopOnContainers-Containers.txt](https://github.com/dotnet-architecture/eShopOnContainers/files/6284482/eShopOnContainers-Containers.txt)

I would expect the application to be stable enough to build and run every time with F5 or docker-compose up command. That means you do not need to have to kill and remove the running containers(clean up) as well as have to force start the sql first before issuing` docker-compose up.

Hope I could make myself clear. 
`

**Comment by developertest02** [comment]
krchrome, Do you have IIS running or anything on port 80? If so, stop IIS (or whatever is listening on port 80). I had the same issue, this was the fix... 

In my WebMVC service logs, the exception I was getting was

11:03:36 INF] Sending HTTP request GET http://identity-api/hc
[11:03:37 ERR] Health check identityapi-check completed after 327.1475ms with status Unhealthy and description 'null'
System.Net.Http.HttpRequestException: Connection refused **(identity-api:80)**
 ---> System.Net.Sockets.SocketException (111): Connection refused

**Comment by sughosneo** [comment]
Thank you @krchome for sharing all the details.

From the log, I could see that all the containers of the previous execution (*`docker-compose up` command from the powershell*) are still up and running. For e.g :

```
1a59f43aef48   eshop/webspa:linux-latest                     "dotnet WebSPA.dll"      33 hours ago        Up 33 hours   0.0.0.0:5104->80/tcp                                                                                         
8fb8f6991a0f   eshop/webmvc:linux-latest                     "dotnet WebMVC.dll"      33 hours ago        Up 33 hours   0.0.0.0:5100->80/tcp 
.....
```

Now, if you'll use `Visual Studio` (*F5 experience*) to bring up the new set of containers, it will try to use the same set of previously occupied ports (For e.g: 5104,5100 etc..). And, it will end up throwing the `port(s) are already in use` error message. 
That's the reason you'll need to stop the existing containers before running the application again from the Visual Studio. 

You can do that by using the following steps :

- Go to the `eShopOnContainers\src` directory
- And run `docker-compose down` (*This command will stop all the running containers*)
- Validate nothing is running using the command `docker ps -a`
- And then you should be able to run the application from Visual Studio. 

Please note that on the same host, you can either follow `docker-compose` or `Visual Studio F5` scenario to run the application. Because though the docker containers use different docker images, but use the same ports.

**Comment by krchome** [comment]
@sughosneo ,
Thanks very much for your prompt support and willingness to help. Here is what I have tested further:
I did `docker-compose down`
Then ran the app from VS F5 
After building, it again came up with the 503 Error (**CatalogService** container seems not be available as in all previous cases of this error as this exception stack trace shows)
`An unhandled exception occurred while processing the request.
HttpRequestException: Response status code does not indicate success: 503 (Service Unavailable).
System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
Microsoft.eShopOnContainers.WebMVC.Services.CatalogService.GetCatalogItems(int page, int take, Nullable<int> brand, Nullable<int> type) in **D:\Projects\Microservices\eShopOnContainers\src\Web\WebMVC\Services\CatalogService.cs**
Microsoft.eShopOnContainers.WebMVC.Controllers.CatalogController.Index(Nullable<int> BrandFilterApplied, Nullable<int> TypesFilterApplied, Nullable<int> page, string errorMsg) in **D:\Projects\Microservices\eShopOnContainers\src\Web\WebMVC\Controllers\CatalogController.cs**
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Show raw exception details
System.Net.Http.HttpRequestException: Response status code does not indicate success: 503 (Service Unavailable).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.eShopOnContainers.WebMVC.Services.CatalogService.GetCatalogItems(Int32 page, Int32 take, Nullable`1 brand, Nullable`1 type) in D:\Projects\Microservices\eShopOnContainers\src\Web\WebMVC\Services\CatalogService.cs:line 35
   at Microsoft.eShopOnContainers.WebMVC.Controllers.CatalogController.Index(Nullable`1 BrandFilterApplied, Nullable`1 TypesFilterApplied, Nullable`1 page, String errorMsg) in D:\Projects\Microservices\eShopOnContainers\src\Web\WebMVC\Controllers\CatalogController.cs:line 20
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

Further, the result of the `docker-compose down `and `docker ps -a` are attached which was carried out before the F5 operation. 
[eShopOnContainers-Down-ProcessStatus.txt](https://github.com/dotnet-architecture/eShopOnContainers/files/6288554/eShopOnContainers-Down-ProcessStatus.txt)

**Comment by krchome** [comment]
> krchrome, Do you have IIS running or anything on port 80? If so, stop IIS (or whatever is listening on port 80). I had the same issue, this was the fix...
> 
> In my WebMVC service logs, the exception I was getting was
> 
IIS or anything was **not running** on port 80 when I got error 503. Somehow it's the CatalogService that's the real culprit as this error always points to nonavailablity of this service in bold.

**Comment by krchome** [comment]
@sughosneo 
I found on the next run with Visual Studio F5 it came up with Error 503 again. This time I refreshed my browser after a few minutes and then surprised to find that everything is working fine when I browsed to :
Web Status : `http://host.docker.internal:5107/`
Web MVC :  `http://host.docker.internal:5100/`

The unavailable service may have responded in between as the health check shows now. Closing the issue now.
**Thanks very much for your patience in explaining everything that helped increase my insight.**

**Comment by sughosneo** [comment]
> @sughosneo
> I found on the next run with Visual Studio F5 it came up with Error 503 again. This time I refreshed my browser after a few minutes and then surprised to find that everything is working fine when I browsed to :
> Web Status : `http://host.docker.internal:5107/`
> Web MVC : `http://host.docker.internal:5100/`
> 
> The unavailable service may have responded in between as the health check shows now. Closing the issue now.
> **Thanks very much for your patience in explaining everything that helped increase my insight.**

Great  👍 
Yes, it may take few mins for all the services to come up.
