### ISSUE TITLE
Load testing deprecated since 2019

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/eShopOnContainers#1643]
Load Testing was [announced deprecated in Feb 2019](https://devblogs.microsoft.com/devops/cloud-based-load-testing-service-eol). The Load Testing docs on docs.microsoft.com have this notice. We should update these architectural docs to point to the 3rd party recommendations as well. https://github.com/dotnet-architecture/eShopOnContainers/wiki/Load-testing

**Comment by sughosneo** [comment]
Thank you @kendrahavens, for the feedback. Adding this to our backlogs to update the docs.

CC @nishanil

**Comment by sughosneo** [comment]
Wiki page has been updated. So closing this issue now. Thank you.
