### ISSUE TITLE
Github action not work

### ISSUE THREAD

**Issue by KhoiNguyenICT** [dotnet/eShopOnContainers#1648]
Hi
I fork this source but github action show error with message: 
```text
Run sudo -E docker-compose build apigateways
  sudo -E docker-compose build apigateways
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    SERVICE: apigateways
    IMAGE: apigateways
    BRANCH: dev
    TAG: dev
    REGISTRY: ***
Building apigateways
invalid argument "***/apigateways:linux-dev" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
Service 'apigateways' failed to build
Error: Process completed with exit code 1.
```
How can i fix the above error?
My source code in github repository: [https://github.com/KhoiNguyenICT/AioCore/actions](https://github.com/KhoiNguyenICT/AioCore/actions)
Thank you so much

**Comment by sughosneo** [comment]
Hi @KhoiNguyenICT , just checking if you are still facing the issue. Please feel free to reopen it if you have any questions. 

Thank you.

**Comment by KhoiNguyenICT** [comment]
> Hi @KhoiNguyenICT , just checking if you are still facing the issue. Please feel free to reopen it if you have any questions.
> 
> Thank you.

Thanks @sughosneo, I found the cause because i config secrets repo fail
Thank for support
