### ISSUE TITLE
Communication Between two microservices using ASP.Net Core WebApi

### ISSUE THREAD

**Issue by kmuthugtk** [dotnet/eShopOnContainers#1655]
I have two Microservices. First Service for Customers and Second service for Invoice Service.

In Invoice MicroService, I will save only CustomerId in Invoice services. Using this CustomerId, I would like to retrieve all the related data for Customer Microservice. But i don't know to communicate async.

Any please get me some ideas and examples

**Comment by sughosneo** [comment]
Hi @kmuthugtk, thank you for reaching out. 

It depends on your business scenario and microservices architecture. I could think of the following options :

- If you have a simple architecture, then you can make REST/HTTP calls between microservices.
- If you want to maintain low latency between microservices calls, then you can use gRPC.
- If you want to fetch the information from the Customer Service and consolidate that data with the data of `Invoice microservices` before passing that to the client, you can use API Gateway Pattern with the aggregator.
  And the aggregator can further manage the microservices interactions through REST/HTTP or gRPC to achieve low latency.
- But if your microservices emits an event for a certain business scenario, then other microservice needs to subscribe to that event to act on it using pub/sub.

For more details, you can refer to [Communication in a microservice architecture](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/architect-microservice-container-applications/communication-in-microservice-architecture) and eShoponContainers code base.


Hope this helps !

**Comment by sughosneo** [comment]
Hi @kmuthugtk, just checking if you had any further questions on this topic. Or are we good to close this? Thank you.

**Comment by sughosneo** [comment]
Considering this question has been answered, I am closing this issue as of now. Please feel free to reopen if you have any further questions. 

Thank you.
