### ISSUE TITLE
Debugging code and flow

### ISSUE THREAD

**Issue by kotasha99** [dotnet/eShopOnContainers#1656]
Hi.

am trying to debug the code and going thru flow, found some urls pls clarify.

Like when our UI webMVC is connecting to the api gateway and microservices thru the Devspaces library, i see purchase url 

![image](https://user-images.githubusercontent.com/58392514/116380335-7ed9d100-a831-11eb-82de-cb31db97a2a2.png)

am seeing the url http://webshoppingapigw in dockercompose override.yml file.

![image](https://user-images.githubusercontent.com/58392514/116380722-dbd58700-a831-11eb-812a-0386bc910981.png)

if am debugging webMVC app in local computer how is tht referring and working with http urls, pls suggest

Regards, Kota

**Comment by sughosneo** [comment]
Hi @kotasha99, thank you for reaching out. 

When you try to run the `eShopOnContainers` application locally (`Without k8s cluster`), it uses the `docker-compose.yml` file to run the application.  All the configuration for each microservices is driven by the `environment` variables that get injected in every docker container whenever it comes up. For e.g [docker-compose.override.yml](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/docker-compose.override.yml) Now, individual microservice retrieves specific information from the environment whenever it's needed. For e.g [Basket API fetches Identity Url](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Basket/Basket.API/Startup.cs#L84) Similarly, for the WebMVC as well all the respective configurations are passed through the environment variables.

For more details, you can always refer to the [Wiki](https://github.com/dotnet-architecture/eShopOnContainers/wiki)

Hope this helps !

**Comment by kotasha99** [comment]
> Hi @kotasha99, thank you for reaching out.
> 
> When you try to run the `eShopOnContainers` application locally (`Without k8s cluster`), it uses the `docker-compose.yml` file to run the application. All the configuration for each microservices is driven by the `environment` variables that get injected in every docker container whenever it comes up. For e.g [docker-compose.override.yml](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/docker-compose.override.yml) Now, individual microservice retrieves specific information from the environment whenever it's needed. For e.g [Basket API fetches Identity Url](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Basket/Basket.API/Startup.cs#L84) Similarly, for the WebMVC as well all the respective configurations are passed through the environment variables.
> 
> For more details, you can always refer to the [Wiki](https://github.com/dotnet-architecture/eShopOnContainers/wiki)
> 
> Hope this helps !

#1362

hi @sughosneo ,  my query is how do http is working in local machine.
if it uses docker-compose files then why the same url is not working from Postman?
Url from the given source code:
http://webshoppingapigw/c/api/v1/catalog/items?pageIndex=0&pageSize=10
Its pulling records from localdb thru code but not working with Postman.

Please suggest.

Regards, Kota

**Comment by sughosneo** [comment]
Hi @kotasha99, thank you for the clarification. 

You'll not be able to access the hostname `webshoppingapigw` outside of the docker network. Service name as hostname is only reachable from other docker containers within the docker network. If you want to access any specific API from the postman, you can check the [docker-compose.override.yml](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/docker-compose.override.yml#L183) file for the port number.Then you can use this url template `http://<docker-host-name>:<port>/` to access the specific service. 

For e.g : If you are running this application on a Windows OS, then you can access the `webshoppingapigw` by using the `http://host.docker.internal:5202/`url.

![image](https://user-images.githubusercontent.com/13281246/116849537-8f60c180-ac0c-11eb-8a5a-756c74039cf9.png)

Hope this helps !

**Comment by kotasha99** [comment]
Hi @sughosneo , thanks for the inputs.
