### ISSUE TITLE
Cannot start service ordering-api: driver failed programming external connectivity on endpoint src_ordering-api_1 

### ISSUE THREAD

**Issue by lahiruchamira** [dotnet/eShopOnContainers#1659]
Cannot start service ordering-api: driver failed programming external connectivity on endpoint src_ordering-api_1 (238e9174ce31c1150fb764b83d756dacdd15cd6c327214444bc4aea6f06fa616): Timed out proxy starting the userland proxy

**Comment by sughosneo** [comment]
Hi @lahiruchamira, thank you for reaching out. 

Looking at the error message, it seems like there could be some network issue. 

- That development machine you are trying to run the application, is it behind a firewall or corporate network with restricted domain policy?
- Did you notice if there is anything already running on the ports? (*for e.g: 5001,5002 etc.*)
- If possible, could you please try disabling the firewall for a moment (*just for testing*) and try if that works?
