### ISSUE TITLE
Severity	Code	Description	Project	File	Line	Suppression State Error	MSB3644	The reference assemblies for .NETFramework,Version=v5.0 were not found. after updating the framework to version 5 

### ISSUE THREAD

**Issue by lahiruchamira** [dotnet/eShopOnContainers#1661]
![image](https://user-images.githubusercontent.com/9689769/116957831-6fdc9e00-accb-11eb-97bc-c4718accb4c3.png)

**Comment by sughosneo** [comment]
Hi @lahiruchamira , thank you for reporting this issue.

When do you get this error ? `dev` branch is already updated to `.NET 5`. Did you take the latest?

**Comment by lahiruchamira** [comment]
Yes I have the dev Branch and this is the first time run the code using visual studio

**Comment by sughosneo** [comment]
Thanks for the update @lahiruchamira 

Could you please follow the steps mentioned [Visual Studio (F5 experience)](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#optional---use-visual-studio) and try to run the application ?

**Comment by lahiruchamira** [comment]
Yes that's what I follow but still haven't run the project :(

**Comment by sughosneo** [comment]
I see. Could you please confirm if you are able to run the solution from the command line ? Ref : [Docker compose on windows](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup)

**Comment by sughosneo** [comment]
Hi @lahiruchamira, just checking if you had a chance to test out the steps mentioned above. Thank you.

**Comment by sughosneo** [comment]
I am closing this issue as of now. Please feel free to reopen it if there is any further question. Thank you.
