### ISSUE TITLE
Background Task vs Azure Function to process service bus messages

### ISSUE THREAD

**Issue by MuraliM** [dotnet/eShopOnContainers#1671]
I see that Background task (Ordering.BackgroundTasks) has been used to process the messages/events comes from service bus. 

Is there a reason why we are not using Azure functions that picks up the message and send it to API to process further? 
Azure function may have certain advantages over background tasks

1. It can run independently
2. Auto scaling is possible

Just curious to understand what benefits we get if we use Background tasks instead of Azure functions, when the function does not do lot of orchestration and just pass it to our API.

**Comment by sughosneo** [comment]
Hi @MuraliM, thank you for reaching out. 

Yes, `Ordering.BackgroundTasks` processes the messages/event from the event bus. 

The `eShopOnContainers` reference application is also designed to run in the local environment with both Docker-Compose/Kubernetes apart from AKS deployment. `Ordering.BackgroundTasks` helps you to achieve that easily. 
As a separate process/container is used for hosting the BackgroundTasks, it also easy to scale up and down based on the need. For more details, refer [Implement background tasks in microservices with IHostedService and the BackgroundService class](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice)

If your deployment is only focused on the Cloud (For e.g : `Azure`), then there are quite a few options available to [host your background job](https://docs.microsoft.com/en-us/azure/architecture/best-practices/background-jobs#hosting-environment) based on the type. And yes, you could consider `Azure Functions` as one of the popular choices in this segment.

Hope this helps !

**Comment by sughosneo** [comment]
Hi @MuraliM, just checking if you had any further questions on this topic, or shall we close this issue? Thank you.

**Comment by sughosneo** [comment]
I am closing this issue as of now. Please feel free to reopen if you have any further questions. Thank you.
