### ISSUE TITLE
Debugging in VS 2019 is painfully slow

### ISSUE THREAD

**Issue by maucaro** [dotnet/eShopOnContainers#1673]
I've cloned this repo and set up a local dev environment with VS 2019 as per the documentation (with WSL 2 option) on an Azure VM (Standard D4s v3 - 4 vCPUs and 16 GB of RAM) and starting a debugging session is painfully slow (3+ minutes the first time and just under 2 minutes thereafter). I tried beefing up the VM to 8 vCPUs and 32 GB of RAM with only marginal improvements (~2 minutes the first time and ~90 seconds from then on). I realize that in many (perhaps most) cases a developer will only be actively working on a single project, so my question is this: how can a developer iterate over a single project and have the rest of the setup already running in order to have a better and faster dev experience? Is this possible?

**Comment by sughosneo** [comment]
Hi @maucaro, thank you for reaching out. 

Distributed applications where many services are involved like `eShopOnContainers` are always tricky to debug in the local. Yes, the best solution would be [Bridge to Kubernetes](https://docs.microsoft.com/en-us/visualstudio/containers/bridge-to-kubernetes?view=vs-2019) But as of now, we haven't started any work related to `Bridge to Kubernetes` in the `eShopOnContainers` app. If anyone makes any progress and submits a PR, we will be happy to review and merge the changes in the `dev` branch. Till that time, we only have [Visual Studio (F5 experience)](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#optional---use-visual-studio) to debug the application locally with necessary breakpoints.

**Comment by maucaro** [comment]
@sughosneo , has anyone on your team looked into what needs to be done or where to start? I'd be willing to take a stab at this and it would be very valuable if I don't have to start from square one...

**Comment by sughosneo** [comment]
Hi @maucaro - I am yet to try out with the `eShopOnContainers` but these [samples](https://github.com/microsoft/mindaro/tree/master/samples) could be the starting point. Thank you.

**Comment by PSepah** [comment]
I had same problem but after I improve my hardware, it is working fine. this is my hardware improving:
HDD to SSD 1 TB
RAM from 8 GB to 16 GB DDR3
But still the problem for me is how to debug front-end ts codes (webSPA) on docker containers.

**Comment by erjain** [comment]
This issue is tracked and answered in [issue #1808](https://github.com/dotnet-architecture/eShopOnContainers/issues/1808). Thanks, @PSepah for answering it in new issue #1808. I am closing this issue, however, feel free to reopen it in case you are looking for more help.
