### ISSUE TITLE
apigwms fails to install on k8s

### ISSUE THREAD

**Issue by geerzo** [dotnet/eShopOnContainers#1675]
I followed the instructions to install the nginx ingest controller but get the following error during the install process 

```
Installing: apigwms
W0514 17:45:09.997154    6015 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0514 17:45:10.034949    6015 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Error: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://nginx-ingress-ingress-nginx-controller-admission.ingress-basic.svc:443/networking/v1beta1/ingresses?timeout=10s": service "nginx-ingress-ingress-nginx-controller-admission" not found
```

Did I miss a step somewhere with the ingress controller?

**Comment by sughosneo** [comment]
Hi @geerzo, thank you for reaching out. 

Did you follow the [Install NGINX Ingress Controller](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes#install-nginx-ingress-controller) step?

**Comment by geerzo** [comment]
I did and it installed the Ingress Controller but not the "controller-admission" part. I was able to get this working by following these instructions instead (using AKS) https://docs.microsoft.com/en-us/azure/aks/ingress-basic

**Comment by sughosneo** [comment]
I see. thank you for the update @geerzo 

As of now, in the `eShopOnConetainers` app, https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/deploy/k8s/nginx-ingress/mandatory.yaml manifest file will not have the `ingress-nginx-controller-admission` service component. That's the reason it's missing. But that shouldn't stop installing any component in AKS. Could you please share the below information? 

- If you could confirm that you have followed the wiki [Deploy-to-Azure-Kubernetes-Service-(AKS)](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS))
- The version of the Kubernetes you have used.

We'll try to test out the steps again and update the `nginx-controller` version if needed.

**Comment by geerzo** [comment]
Yes, I followed the guide. AKS is currently on Kubernetes 1.19.9

After solving this one I did run into another problem with the install script and the tag. If you specify a tag, it tries to use that tag to install the envoy proxy as well but "linux-dev" isn't a valid tag for that project. I had to modify the install script to install  the envoy-proxy based items separately with no tag.

**Comment by sughosneo** [comment]
Hi @geerzo, just checking if you were able to deploy the app in AKS. I just tried the steps again and it seems to be working fine for me.  If you are facing any other issues, could you please share the latest error message? Thank you.

**Comment by sughosneo** [comment]
Hi @geerzo, as there are no changes from the Azure installation step point of view, I am closing this issue as of now. Please feel free to reopen it, if you need any further help. Thank you.
