### ISSUE TITLE
Ingress Rewrite Rule does not work on newer nginx-ingress controllers

### ISSUE THREAD

**Issue by Blackclaws** [dotnet/eShopOnContainers#1676]
The existing k8s deployment will not work correctly on more recent versions of nginx-ingress due to the way the rewrite annotation was changed.

https://kubernetes.github.io/ingress-nginx/examples/rewrite/

It strips the complete path out so all requests to the api gateway get reduced to Path: /

If you'd like I can provide a pull request that fixes this

**Comment by sughosneo** [comment]
Hi @Blackclaws, thank you for your suggestions. 

As of now in `eShopOnConetainers` app, we are using `NGINX Ingress controller` of version `0.20.0`. For e.g : `quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.20.0`

![image](https://user-images.githubusercontent.com/13281246/118482997-1e082f00-b733-11eb-8768-958314d68db5.png)

Yes, if we are updating the `NGINX Ingress controller` to version `0.22.0`, we would need to make sure that we are updating the necessary configuration as well. For e.g `nginx.ingress.kubernetes.io/rewrite-target` configuration. Also, we need to see that all the changes work fine for both [Local Kubernetes](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes) and [Azure Kubernetes Service (AKS)](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS))

Please feel free to submit a PR with the proposed changes. We will be happy to review and merge the changes.

**Comment by Blackclaws** [comment]
Well the nginx version you ship together with it unfortunately doesn't matter that much when deploying to an existing test-cluster that already runs an ingress controller. Though I understand this might not be one of the officially supported use cases. 

I'm using the application in a teaching setting as an example and I deploy multiple applications to a semi-local kubernetes cluster that hosts multiple apps with different requirements. If I got some time I'll submit a pull request.

**Comment by sughosneo** [comment]
Hi @Blackclaws, recently we have updated all the Ingress objects to use API Version `V1.0` 
You can refer to the details in the PR https://github.com/dotnet-architecture/eShopOnContainers/pull/1725

You could take the latest and test out the ingress-related functionality. 
I am closing this issue as of now. Please feel free to reopen or submit a new issue if needed.

Thank you
