### ISSUE TITLE
Web SPA : not working;  http://host.docker.internal:5104/	(HealthChecks shows it up and running, but get 404 	Host.docker.internal page can’t be found)

### ISSUE THREAD

**Issue by PerProjBackup** [dotnet/eShopOnContainers#1677]
Visual Studio 2019 Enterprise 16.9.6; Latest Chrome; Docker 3.3.3; Win 10

I've downloaded the latest code.   eShopOnContainers-dev. zip 5/8/21

If run `docker-compose build` and `docker-compose up` I can browse to all three urls:
Web Status : http://host.docker.internal:5107/ 
Web MVC :  http://host.docker.internal:5100/	
Web SPA :  http://host.docker.internal:5104/

From Docker Desktop I then delete all Containers and Images.

From Visual Studio I then start the `docker-compose` project.

In the Containers tab all Containers are green.

Chrome opens to host.docker.internal:5100/  with this error:
An unhandled exception occurred while processing the request.
HttpRequestException: Response status code does not indicate success: 503 (Service Unavailable).

If refresh browser the Web MVC pages loads properly.

When I browse to the WebSPA, host.docker.internal:5104/, I get this error:
This host.docker.internal page can’t be found	No webpage was found for the web address: http://host.docker.internal:5104/
HTTP ERROR 404

The browser Console shows this error:
	Failed to load resource: the server responded with a status of 404 ()

host.docker.internal:5107/ shows all green arrows, including the `WebSPA HTTP Check`.

Docker Desktop Container dockercompose 1840313715643044858 is running
	WebSPA eshop/webspa:dev
	RUNNING PORT: 5104

I've  stopped and started everything numerous times and cleared all the Containers and Images numerous times and still cannot browse the WebSPA when running in Visual Studio.

**Comment by sughosneo** [comment]
Hi @PerProjBackup, thank you for reaching out. 
You may want to try out the instructions mentioned in this comment https://github.com/dotnet-architecture/eShopOnContainers/issues/1360#issuecomment-774091460

**Comment by PerProjBackup** [comment]
That fixed it.  The instructions for [Optional - Use Video Studio](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#optional---use-visual-studio) need to be updated to include the Angular setup for the SPA.

I deleted the solution and code download.  Then downloaded the latest zip file from github.
Unzipped to a local directory, opened an elevated prompt and navigated to the ...\eShopOnContainers-dev\src\Web\WebSPA folder.
Followed hero3616's instructions at #1360 (comment), adding a `npm audit fix`
npm install
npm audit fix
ng build

Open solution in Visual Studio and Start in debug.  Wait a minute after browser opens to navigate to host.docker.internal:5104.

This issue can be closed.

**Comment by sughosneo** [comment]
Thanks for the update @PerProjBackup . I will close this issue now.
