### ISSUE TITLE
Microsoft.Extensions.Configuration.AzureKeyVault is deprecated

### ISSUE THREAD

**Issue by hkooiker** [dotnet/eShopOnContainers#1680]
This package has been deprecated as it is legacy and no longer maintained.

    This library has been replaced by the following new Azure SDK.

    https://www.nuget.org/packages/Azure.Extensions.AspNetCore.Configuration.Secrets

    It is recommended that you move to the new package.

**Comment by sughosneo** [comment]
Hi @hkooiker, thank you for pointing it out.

I see a new PR https://github.com/dotnet-architecture/eShopOnContainers/pull/1685 already on this topic. We will review that and try to incorporate the changes. You may want to test this PR and share your early feedback as well.

**Comment by sughosneo** [comment]
As the changes are already merged into the `dev` branch, I am closing this issue as of now. Please feel free to reopen if needed. Thank you.
