### ISSUE TITLE
Can nullable reference types be enable in this project

### ISSUE THREAD

**Issue by sanderobdeijn** [dotnet/eShopOnContainers#1681]
I'm trying some of the patterns in this project and I want to implement this in a project that has nullable type references enabled. That breaks some of the examples.
Enabling nullable reference types is becoming more and more the default. (At least for new projects)

Can it also be enabled in this sample project?

**Comment by sughosneo** [comment]
Hi @sanderobdeijn, thank you for reaching out. 

That's a good idea. We are working on clearing the current backlogs at the moment. However, we are happy to review and accept a PR from the community on this. I will tag them as "help-wanted" for now. If you or anyone else wishes to work on this, please let us know on this thread. I will assign the issue to them to avoid duplicate efforts. 

Here are some excellent references for starters:
[Work with nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/nullable-reference-types) and [NullableIntroduction samples](https://github.com/dotnet/samples/tree/main/csharp/NullableIntroduction).

CC: @IEvangelist - any further thoughts ?

**Comment by IEvangelist** [comment]
Hi @sanderobdeijn and @sughosneo - this sounds like a great idea. We'd have to be careful to make sure that we thoroughly test any/all changes, and that the changes are correctly reflected in the [dotnet/docs](https://github.com/dotnet/docs) too.

**Comment by erjain** [comment]
Considering this issue is stale since this issue did not receive any further updates, I am closing it. Please feel free to reopen it if needed.
