### ISSUE TITLE
不再更新了吗？

### ISSUE THREAD

**Issue by xewn** [dotnet/eShopOnContainers#169]
这个项目不再更新代码了吗？

**Comment by FDUdannychen** [comment]
You are looking at the master branch, consider it as a stable release branch of this project, you can see the release plan [here](https://github.com/dotnet/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases). If you want to see the recent changes, check out [the dev branch](https://github.com/dotnet/eShopOnContainers/tree/dev).
