### ISSUE TITLE
[Questions] Domain events dispatch, domain model validation, unique constraint check and VO

### ISSUE THREAD

**Issue by sreejith-ms** [dotnet/eShopOnContainers#1690]
I have few questions related to the DDD implementation.

In `eShopOnContainers` the domain events are dispatched before committing the data. Consider a typical scenario like the application needs to send an email after creating the Order. There is an empty class `SendEmailToCustomerWhenOrderStartedDomainEventHandler` in the repo, but the email sending logic is on TBD. 

For the domain model validation, is it fine to use `FluentValidation`? even though the validators might be duplicated in the application and domain layer it is useful for validations like `EmailAddress`.

The next question is how to handle the unique constraints, a typical example is `username` must be unique.
I have read different articles mentioned about this [trilemma](https://enterprisecraftsmanship.com/posts/domain-model-purity-completeness/), with solutions like domain service, handle in the controller and handle in the domain model by passing domain service. I need to know how `eShopOnContainers` will handle this scenario :blush:

The final question is about value object serialization.
Suppose I'm storing the data as JSON and I want the value objects properties to be serialized in the entity object. Any thoughts on how to create a generic `JsonConverter` for value objects?
I already posted a question on SO. [How to create a generic JsonConverter for Value Object serialization?](https://stackoverflow.com/q/67821962/5078531)

**Comment by sughosneo** [comment]
Hi @sreejith-ms, thank you for reaching out. 

Q1) : In my opinion, it'll be better to keep your Domain entities as much less dependent as possible on framework or technology. Having said that, you'll definitely want to deal with a valid Domain entity. You can find a list of different approaches in [Implement validations in the domain model layer](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/domain-model-layer-validations#implement-validations-in-the-domain-model-layer). Now, the attribute you'll like to validate in your entity that depends on your business scenario. Let's say, if you are dealing with `User` registration/signup in that scenario, the `EmailAddress` can't be null. So you may want to make sure that never happens.

Q2) : Different approaches are very well explained in [Design a No Duplicates Rule in your Domain Model?](https://ardalis.com/design-no-duplicates-rule-in-domain-model/)

Q3) :  Did you try writing your own custom converter https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-5-0 ?

Hope this helps !

**Comment by sreejith-ms** [comment]
Thanks @sughosneo

**Comment by MattHartz** [comment]
Hi @sreejith-ms ,

Just a random question. It seems off to me to send an email based off a DomainEvent because of a potential failure to push the transaction to the DB, but still manage to send an email.

Is it preferred to actually do email sending as an IntegrationEventHandler instead? Or is the DomainEvent writing to some sort of email service message that can be done in process, but the actual delivery of the email is out of process?

I'll open up another ticket if preferred

Thanks!
