### ISSUE TITLE
Typo in label - order detail page

### ISSUE THREAD

**Issue by VictorZakharov** [dotnet/eShopOnContainers#1693]
The word "Shipping" should be with 2 Ps.

![image](https://user-images.githubusercontent.com/8978766/120854702-8769a980-c54b-11eb-9d93-18050d70a5e3.png)

**Comment by sughosneo** [comment]
Hi @VictorZakharov, thank you for pointing it out. Would you like to submit a PR?

**Comment by VictorZakharov** [comment]
@sughosneo  Sure. I'll take a look when time allows.

**Comment by kaypee90** [comment]
@VictorZakharov I can open a quick PR if you don't mind

**Comment by VictorZakharov** [comment]
@kaypee90 Yes, please go head.

**Comment by sughosneo** [comment]
As the changes are already merged, I am closing this issue. 
Thank you @kaypee90 and @VictorZakharov
