### ISSUE TITLE
Error while using Docker Windows app to start containers

### ISSUE THREAD

**Issue by KarolCommence** [dotnet/eShopOnContainers#1699]
Below is the error massage i receive when i try to start or stop containers from Docker Windows app:

" Cannot start Docker Compose application. Reason: Error invoking remote method 'compose-action': Error: Command failed: docker-compose --file "docker-compose.yml,docker-compose.override.yml" --project-name "src" --project-directory "C:\Users\ <user_name>\Documents\GitHub\eShopOnContainers\src" up -d .FileNotFoundError: [Errno 2] No such file or directory: '.\\docker-compose.yml,docker-compose.override.yml' "

![2021-06-15_15h10_17](https://user-images.githubusercontent.com/85217836/122058916-6b3bf700-cdec-11eb-96e1-18bb3caa4888.png)

I followed this tutorial: https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#configure-docker

**Comment by KarolCommence** [comment]
Works ok when using powershell commands to start and stop containers

**Comment by sughosneo** [comment]
Hi @KarolCommence, thank you for reaching out.

Did you stop the containers by Docker Dashboard? Because when I followed the below steps and I was able to start and stop the containers without any issue. 

- `docker-compose up`
- Stop the containers using the `STOP` button in the Docker Desktop Dashboard (Containers/App) section
- After that, I was able to start the container using the `START` button of the Docker Desktop Dashboard (Containers/App) section

Could you please try the above steps?

**Comment by KarolCommence** [comment]
Good news I've managed to deal with the issue today. What i did was deleting images, then my repository. I've changed location of repo to "root" (C:\Git\ <repo name>

Then used elevated Powershell to "docker-build compose" and "docker-build up"

Then instead of Ctrl+C in Powershell i just used stop button in Docker Windows App to stop it. It didn't throw an error so I've closed Powershell and carried on from there.

Now containers from SRC starts without issue in Docker Windows App. 

I guess issue was somehow connected to error thrown during first time stoping "docker-build up".

**Comment by sughosneo** [comment]
Great! Glad to hear that it's working for you. I am closing this issue as of now. Please feel free to reopen, if you have any more questions. Thank you.

**Comment by DanielOizumi** [comment]
Enabling **Use Docker Compose V2** fixed the issue I was having with "_Reason: Error invoking remote method 'compose-action'_".
![image](https://user-images.githubusercontent.com/23506840/145612604-a57dcaaa-110e-436c-8b75-de8780585d99.png)

**Comment by roland681** [comment]
I activated "Use Docker Compose V2" and did this and worked: https://blog.csdn.net/smallteddy/article/details/121926669
Just restarted the container and already was green (up & running)
