### ISSUE TITLE
401 Unauthorized with Azure Container Registry

### ISSUE THREAD

**Issue by MinhTraHong** [dotnet/eShopOnContainers#1700]
Hi there,

I try to deploy to Azure AKS and get issue with Authentication in Azure Container Registry. I provide user & pass into "helm install" but I cannot deploy website into Azure AKS

Helm command into deploy deploy-all.ps1:
cmd /c "helm install test-aks-api -f app.yaml --values inf.yaml -f ingress_values.yaml -f ingress_values_linkerd.yaml --set app.name=test --set inf.k8s.dns=test.c4c4d2af0b3a49f39d68.eastus.aksapp.io --set ingress.hosts={test.c4c4d2af0b3a49f39d68.eastus.aksapp.io} --set image.tag=linux-latest --set image.pullPolicy=Always --set inf.tls.enabled=False --set inf.mesh.enabled=False --set inf.k8s.local=False --set inf.registry.server=akspoc.azurecr.io --set inf.registry.login=akspoc --set inf.registry.pwd==XRGdYYEUpkrSqOm4qEsp --set inf.registry.secretName=test-docker-scret aks-api"

![image](https://user-images.githubusercontent.com/46124728/122256389-39fd1d00-cef9-11eb-8d1b-596e5181fd05.png)

Can you please take a look and help me to resolve this issue

**Comment by sughosneo** [comment]
Hi @MinhTraHong , thank you for reaching out.

Did you pass the login credential while running the `.\deploy-all.ps1` script? For more detail steps, you can refer [Deploy Your Local Images](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS)#deploy-your-local-images)

**Comment by sughosneo** [comment]
Hi @MinhTraHong, just checking if you had a chance to test out the steps further. Thank you.

**Comment by sughosneo** [comment]
I am closing this issue as of now. Please feel free to reopen if you need any further help. Thank you.
