### ISSUE TITLE
RabbitMQ queue bindings are lost after a reconnection

### ISSUE THREAD

**Issue by alan0428a** [dotnet/eShopOnContainers#1701]
Hello there,

I was checking the auto-reconnect mechanism of RabbitMQ. Then I found that after a reconnection to RabbitMQ, the exchange and all queues are restored but the bindings between them are lost. 
![image](https://user-images.githubusercontent.com/23318971/122581387-93945180-d089-11eb-960e-078937865d03.png)

After carefully tracing the code and the RabbitMQ document, I think I might have the idea. The [document ](https://www.rabbitmq.com/channels.html)states that 
> The following steps are performed for every channel known to being open at the time of connection failure:
> - Re-declare exchanges (except for predefined ones)
> - Re-declare queues
> - Recover all bindings
> - Recover all consumers

It means that if we want the bindings to be recovered after reconnection, channels must be opened at the time of connection failure. But in the DoInternalSubscription method, we use "using" to declare a channel, so the channel is being disposed when leaving the "using" section.

```
        private void DoInternalSubscription(string eventName)
        {
            var containsKey = _subsManager.HasSubscriptionsForEvent(eventName);
            if (!containsKey)
            {
                if (!_persistentConnection.IsConnected)
                {
                    _persistentConnection.TryConnect();
                }

                using (var channel = _persistentConnection.CreateModel())
                {
                    channel.QueueBind(queue: _queueName,
                                      exchange: BROKER_NAME,
                                      routingKey: eventName);
                }
            }
        }
```

Maybe we can use the `_consumerChannel` which is created at the constructor instead, rather than declare a new channel whenever needs to bind a queue to an exchange? What do you think?

The document also states that 
> Much like connections, channels are meant to be long lived. That is, there is no need to open a channel per operation and doing so would be very inefficient, since opening a channel is a network roundtrip.

So I think the fix might also improve the performance as well?

I have tested the approach and it works without issue. I am happy to create a PR if needed :)

### How to reproduce
1. Launch the project using docker-compose ( I was using visual studio)
2. Stop the RabbitMQ container
3. Wait services start trying to reconnect
3. Start the RabbitMQ container
4. Go to RabbitMQ admin UI to check bindings

**Comment by alan0428a** [comment]
Any thoughts or suggestions on this? Or if I miss something?

**Comment by sughosneo** [comment]
Hi @alan0428a, sorry for the delay in responding. Thank you for identifying the issue and sharing the details repro steps :thumbsup:

Yes, your right. If the RabbitMQ container/pod gets restarted, the binding between the exchange and queues were lost. We don't need to create the channel everytime, instead we could use a common `_consumerChannel`  like the connection `_persistentConnection`  If you could submit a PR, we will be happy to review and merge the changes. 

Also, in the k8s environment, the same repro steps should fetch similar results, if we delete the RabbitMQ pod. You may want to check that too.
