### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by HillCat** [dotnet/eShopOnContainers#1702]
=> CACHED [eshop/ordering.api:linux-latest build 36/42] COPY Web/WebStatus/WebStatus.csproj Web/WebStatus/WebSta  0.0s
 => CACHED [eshop/ordering.api:linux-latest build 37/42] COPY docker-compose.dcproj docker-compose.dcproj          0.0s
 => CACHED [eshop/ordering.api:linux-latest build 38/42] COPY NuGet.config NuGet.config                            0.0s
 => CANCELED [eshop/ordering.api:linux-latest build 39/42] RUN dotnet restore "eShopOnContainers-ServicesAndWeb  253.6s
 => CACHED [eshop/webspa:linux-latest node-build 2/6] WORKDIR /web                                                 0.0s
 => CACHED [eshop/webspa:linux-latest node-build 3/6] COPY Web/WebSPA/package.json .                               0.0s
 => CACHED [eshop/webspa:linux-latest node-build 4/6] COPY Web/WebSPA/package-lock.json .                          0.0s
 => CACHED [eshop/webspa:linux-latest node-build 5/6] COPY Web/WebSPA .                                            0.0s
 => ERROR [eshop/webspa:linux-latest node-build 6/6] RUN npm i npm@latest -g && npm update && npm install && np  239.4s
------
 > [eshop/webspa:linux-latest node-build 6/6] RUN npm i npm@latest -g && npm update && npm install && npm run build:prod:
#717 170.3 /usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
#717 170.3 /usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
#717 170.8 + npm@7.18.1
#717 170.8 added 72 packages from 34 contributors, removed 204 packages and updated 183 packages in 169.159s
#717 171.2 (node:26) ExperimentalWarning: The fs.promises API is experimental
#717 171.3 npm WARN old lockfile
#717 171.3 npm WARN old lockfile The package-lock.json file was created with an old version of npm,
#717 171.3 npm WARN old lockfile so supplemental metadata must be fetched from the registry.
#717 171.3 npm WARN old lockfile
#717 171.3 npm WARN old lockfile This is a one-time fix-up, please be patient...
#717 171.3 npm WARN old lockfile
#717 238.2 npm ERR! code ERESOLVE
#717 238.2 npm ERR! ERESOLVE unable to resolve dependency tree
#717 238.2 npm ERR!
#717 238.2 npm ERR! While resolving: eshopaspnetnetcoredockerspa@0.0.0
#717 238.2 npm ERR! Found: typescript@3.4.5
#717 238.2 npm ERR! node_modules/typescript
#717 238.2 npm ERR!   dev typescript@"3.4.5" from the root project
#717 238.2 npm ERR!
#717 238.2 npm ERR! Could not resolve dependency:
#717 238.2 npm ERR! peer typescript@"3.9.x || 4.0.x" from typedoc@0.19.2
#717 238.2 npm ERR! node_modules/typedoc
#717 238.3 npm ERR!   dev typedoc@"^0.19.2" from the root project
#717 238.3 npm ERR!
#717 238.3 npm ERR! Fix the upstream dependency conflict, or retry
#717 238.3 npm ERR! this command with --force, or --legacy-peer-deps
#717 238.3 npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
#717 238.3 npm ERR!
#717 238.3 npm ERR! See /root/.npm/eresolve-report.txt for a full report.
#717 238.3
#717 238.3 npm ERR! A complete log of this run can be found in:
#717 238.3 npm ERR!     /root/.npm/_logs/2021-06-21T00_39_10_115Z-debug.log
------
**failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c npm i npm@latest -g && npm update && npm install && npm run build:prod]: exit code: 1**
![image](https://user-images.githubusercontent.com/41800196/122693610-16c1cd00-d26d-11eb-8911-39ca58d018b1.png)

**Comment by sughosneo** [comment]
Hi @HillCat, thank you for reaching out. 

I just tested the build in 2 of the different environments. It seems to be working fine.
Did you take the latest from the `dev` branch? Could you please clean the npm cache and try to build the docker images?

**Comment by HillCat** [comment]
I cloned  the branch 3.1.1, not dev branch.

**Comment by HillCat** [comment]
> Hi @HillCat, thank you for reaching out.
> 
> I just tested the build in 2 of the different environments. It seems to be working fine.
> Did you take the latest from the `dev` branch? Could you please clean the npm cache and try to build the docker images?

/usr/share/dotnet/sdk/5.0.301/NuGet.targets(131,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/src/eShopOn]
/usr/share/dotnet/sdk/5.0.301/NuGet.targets(131,5): error :   Resource temporarily unavailable (api.nuget.org:443) [/src/eShopOnContainers-ServicesAndWebA]
/usr/share/dotnet/sdk/5.0.301/NuGet.targets(131,5): error :   Resource temporarily unavailable [/src/eShopOnContainers-ServicesAndWebApps.sln]
The command '/bin/sh -c dotnet restore "eShopOnContainers-ServicesAndWebApps.sln"' returned a non-zero code: 1
ERROR: Service 'identity-api' failed to build : Build failed
![image](https://user-images.githubusercontent.com/41800196/122737864-0bde5b00-d2b4-11eb-9c66-95205a640cf9.png)

**Comment by HillCat** [comment]
> Hi @HillCat, thank you for reaching out.
> 
> I just tested the build in 2 of the different environments. It seems to be working fine.
> Did you take the latest from the `dev` branch? Could you please clean the npm cache and try to build the docker images?

![image](https://user-images.githubusercontent.com/41800196/122742371-7396a500-d2b8-11eb-90dd-0ba4fc0ef484.png)
Unable to load the service index for source https://api.nuget.org/v3/index.json. [/src/eShopOnContain]

![image](https://user-images.githubusercontent.com/41800196/122742569-a93b8e00-d2b8-11eb-95be-e3bc12ade93b.png)
I set the proxy to my vmware centos7 var v2raya . but the nuget still have problem. the os is centos7.

**Comment by HillCat** [comment]
> Hi @HillCat, thank you for reaching out.
> 
> I just tested the build in 2 of the different environments. It seems to be working fine.
> Did you take the latest from the `dev` branch? Could you please clean the npm cache and try to build the docker images?
the branch 'Dev' is the same problem. 
![image](https://user-images.githubusercontent.com/41800196/122755585-c3c93380-d2c7-11eb-9fc2-c0418a21a699.png)

[logs-that.txt](https://github.com/dotnet-architecture/eShopOnContainers/files/6686273/logs-that.txt)

**Comment by HillCat** [comment]
> Hi @HillCat, thank you for reaching out.
> 
> I just tested the build in 2 of the different environments. It seems to be working fine.
> Did you take the latest from the `dev` branch? Could you please clean the npm cache and try to build the docker images?

clean the npm cache is ok , but in the end ,dotnet pulish failed.
![image](https://user-images.githubusercontent.com/41800196/122794719-22ee6e80-d2ef-11eb-861d-a4aa7f8193f9.png)

**Comment by HillCat** [comment]
/root/.nuget/packages/microsoft.web.librarymanager.build/2.0.96/build/Microsoft.Web.LibraryManager.Build.targets(35,9): error : Microsoft.Web.LibraryManager.Contracts.ResourceDownloadException: Failed to download resource from "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/core.js" [/src/Services/Identity/Identity.API/Identity.API.csproj]

[ErrorMessage.txt](https://github.com/dotnet-architecture/eShopOnContainers/files/6688210/ErrorMessage.txt)

**Comment by HillCat** [comment]
> Hi @HillCat, thank you for reaching out.
> 
> I just tested the build in 2 of the different environments. It seems to be working fine.
> Did you take the latest from the `dev` branch? Could you please clean the npm cache and try to build the docker images?

I try to exec : npm cache verify   ;  npm cache verify  ;  It is not work.
![image](https://user-images.githubusercontent.com/41800196/122846074-afbd1a80-d337-11eb-87e9-9ca314010a6f.png)
[log-errors.txt](https://github.com/dotnet-architecture/eShopOnContainers/files/6690235/log-errors.txt)

**Comment by sughosneo** [comment]
Hi @HillCat, based on your latest information shared earlier in the comment, I tried to run the solution in a newly created Ubuntu VM. But unfortunately, I am not able to reproduce the issue and able to build the WebSPA and other projects fine.
Could you please run `npm cache clean --force`? And then try to build the solution again.

Also, looking at the other error message `Microsoft.Web.LibraryManager.Contracts.ResourceDownloadException: Failed to download resource from "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/core.js"`, it seems like there could be something wrong in the network connectivity your VM is running.

**Comment by HillCat** [comment]
> Hi @HillCat, based on your latest information shared earlier in the comment, I tried to run the solution in a newly created Ubuntu VM. But unfortunately, I am not able to reproduce the issue and able to build the WebSPA and other projects fine.
> Could you please run `npm cache clean --force`? And then try to build the solution again.
> 
> Also, looking at the other error message `Microsoft.Web.LibraryManager.Contracts.ResourceDownloadException: Failed to download resource from "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/core.js"`, it seems like there could be something wrong in the network connectivity your VM is running.

I cleared the npm cache. try to build the solution agian, It is seems the error is from npm :
![image](https://user-images.githubusercontent.com/41800196/122989035-f14fd300-d3d4-11eb-9032-3f3a530867fa.png)
[last-ErrorMessage.txt](https://github.com/dotnet-architecture/eShopOnContainers/files/6696994/last-ErrorMessage.txt)

And I record the video :https://youtu.be/zkANwunQ--c

**Comment by sughosneo** [comment]
Hi @HillCat, thank you for sharing the detailed information. 

From the error message, it seems like that the issue is with the `npm version`. It's supposed to use the `npm@6` than latest `RUN npm i npm@latest -g`. Please see the below screenshot.

![image](https://user-images.githubusercontent.com/13281246/123051431-6b0cae80-d41f-11eb-9d07-e0464dc0fbe7.png)

Could you please take the latest from the `dev` branch and try to build the solution again?

**Comment by HillCat** [comment]
> Hi @HillCat, thank you for sharing the detailed information.
> 
> From the error message, it seems like that the issue is with the `npm version`. It's supposed to use the `npm@6` than latest `RUN npm i npm@latest -g`. Please see the below screenshot.
> 
> ![image](https://user-images.githubusercontent.com/13281246/123051431-6b0cae80-d41f-11eb-9d07-e0464dc0fbe7.png)
> 
> Could you please take the latest from the `dev` branch and try to build the solution again?

It was success. Thanks.
![image](https://user-images.githubusercontent.com/41800196/123544178-a2af8980-d784-11eb-9b93-117ef734258e.png)

**Comment by HillCat** [comment]
> Hi @HillCat, thank you for sharing the detailed information.
> 
> From the error message, it seems like that the issue is with the `npm version`. It's supposed to use the `npm@6` than latest `RUN npm i npm@latest -g`. Please see the below screenshot.
> 
> ![image](https://user-images.githubusercontent.com/13281246/123051431-6b0cae80-d41f-11eb-9d07-e0464dc0fbe7.png)
> 
> Could you please take the latest from the `dev` branch and try to build the solution again?
