### ISSUE TITLE
Images don't display - unless port 5202 is open

### ISSUE THREAD

**Issue by maucaro** [dotnet/eShopOnContainers#1703]
I set up the site per the instructions, one of which was to ensure that ports 5100-5105 should be open. The site worked as expected except for the pictures. After some troubleshooting I noticed that both docker-compose.override.yml and .env reference port 5202, which is obviously outside the range. Once port 5202 was opened, the issue was fixed. Was the intent to use port 5202 (instead of 5102)? If so, please update the documentation. Otherwise, please update docker-compose.override.yml and .env

**Comment by sughosneo** [comment]
Hi @maucaro , thank you for your feedback. 
I have submitted one PR to update the script. Once it gets approved and merged, will update the wiki pages.
