### ISSUE TITLE
Question:  What is the purpose/need of the OrderStatus in the Order entity in the Order Aggregate?

### ISSUE THREAD

**Issue by mlenartcto** [dotnet/eShopOnContainers#1713]
My question is related to the OrderStatus property within the Order entity.  The Order class also has the _orderStatusId field.
 
My question is what is the correlation between the those two.  I don’t see anywhere that the OrderStatus property is set - only the _orderStatusId field.
 
Can you please help me understand why the OrderStatus property?

**Comment by sughosneo** [comment]
Hi @mlenart1010, thank you for reaching out.

[OrderStatus](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.Domain/AggregatesModel/OrderAggregate/OrderStatus.cs#L9) class keeps track of all the different statuses of an order.
When you create an order from the UI, the `_orderStatusId` property gets set by the [constructor](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.Domain/AggregatesModel/OrderAggregate/Order.cs#L56) of the `Order` class. 
Initially, the value of the `_orderStatusId` gets set to `OrderStatus.Submitted.Id` and keeps on getting updated to different id as the order goes through the different phases (For e.g: `OrderStatus.AwaitingValidation.Id`, `OrderStatus.StockConfirmed.Id` etc..)

Hope this helps!

**Comment by mlenartcto** [comment]
@sughosneo Thanks - yes I see that the _order StatusId field gets set but not the OrderStatus property itself.  How and when is this property populated?

**Comment by sughosneo** [comment]
Hi @mlenart1010, `OrderStatus` property gets set in the `Task<Order> GetAsync(int orderId)` method of `OrderRepository` class.
https://github.com/dotnet-architecture/eShopOnContainers/blob/2afc00360f55e288b95a81d8c22cfc318971a287/src/Services/Ordering/Ordering.Infrastructure/Repositories/OrderRepository.cs#L34

Also, please note that the **OrderStatus** and other "types" are implemented as Entities in the Domain Model. They are modeled as a Value-Object. For more details, refer this https://github.com/dotnet-architecture/eShopOnContainers/issues/25

**Comment by mlenartcto** [comment]
@sughosneo Thank you - this fully explains it.  Thank you so much.
