### ISSUE TITLE
http://host.docker.internal:5100/ Doesn't Work but http://localhost:5100/ Does.  What did I do wrong?

### ISSUE THREAD

**Issue by jeffreywstevens** [dotnet/eShopOnContainers#1718]
With http://host.docker.internal:5100/ I receive a "This site can't be reached" error.  I thought it wouldn't be a big deal.  However, none of the forms in the app work because of bad addressing.  Can this be fixed easily?

**Comment by sughosneo** [comment]
Hi @jeffreywstevens, thank you for reaching out. 

If you are running the application on Windows OS environment, then by default, the host name is set to `host.docker.internal`

https://github.com/dotnet-architecture/eShopOnContainers/blob/5c57b8c3f9b705c5be0890416d9005fca36f6ffe/src/.env#L8

But if you are running on MacOS or Linux, you'll need to uncomment the right DNS name. For e.g:

https://github.com/dotnet-architecture/eShopOnContainers/blob/5c57b8c3f9b705c5be0890416d9005fca36f6ffe/src/.env#L12

**Comment by sughosneo** [comment]
Considering the question has already been answered, I am closing this issue as of now. Please feel free to reopen if needed. Thank you.
