### ISSUE TITLE
docker-compose build fails OrderStartedEvent does not exist in the namespace

### ISSUE THREAD

**Issue by RobAllan27** [dotnet/eShopOnContainers#1720]
### **Build errors at the last commit point -** 

**### Overview**
I have cloned the repo. Order start event not found.

docker-compose build fails ...

```
```
 => ERROR [build 39/39] RUN dotnet publish --no-restore -c Release -o /app                                         6.5s
------
 > [build 39/39] RUN dotnet publish --no-restore -c Release -o /app:
#47 0.534 Microsoft (R) Build Engine version 16.10.1+2fd48ab73 for .NET
#47 0.534 Copyright (C) Microsoft Corporation. All rights reserved.
#47 0.534
#47 4.714 /src/Services/Ordering/Ordering.Domain/AggregatesModel/OrderAggregate/Order.cs(32,22): warning CS0414: The field 'Order._isDraft' is assigned but its value is never used [/src/Services/Ordering/Ordering.Domain/Ordering.Domain.csproj]
#47 4.766   EventBus -> /src/BuildingBlocks/EventBus/EventBus/bin/Release/net5.0/EventBus.dll
#47 4.829   Ordering.Domain -> /src/Services/Ordering/Ordering.Domain/bin/Release/net5.0/Ordering.Domain.dll
#47 5.017   WebHost.Customization -> /src/BuildingBlocks/WebHostCustomization/WebHost.Customization/bin/Release/net5.0/WebHost.Customization.dll
#47 5.586   EventBusRabbitMQ -> /src/BuildingBlocks/EventBus/EventBusRabbitMQ/bin/Release/net5.0/EventBusRabbitMQ.dll
#47 5.613   EventBusServiceBus -> /src/BuildingBlocks/EventBus/EventBusServiceBus/bin/Release/net5.0/EventBusServiceBus.dll
#47 5.710   Ordering.Infrastructure -> /src/Services/Ordering/Ordering.Infrastructure/bin/Release/net5.0/Ordering.Infrastructure.dll
#47 5.733   IntegrationEventLogEF -> /src/BuildingBlocks/EventBus/IntegrationEventLogEF/bin/Release/net5.0/IntegrationEventLogEF.dll
#47 6.358 /src/Services/Ordering/Ordering.API/Infrastructure/AutofacModules/MediatorModule.cs(6,52): error CS0234: The type or namespace name 'OrderStartedEvent' does not exist in the namespace 'Ordering.API.Application.DomainEventHandlers' (are you missing an assembly reference?) [/src/Services/Ordering/Ordering.API/Ordering.API.csproj]
------
executor failed running [/bin/sh -c dotnet publish --no-restore -c Release -o /app]: exit code: 1
ERROR: Service 'ordering-api' failed to build : Build failed
```

```

### **Background info**

Not sure that this is hugely relevant but out of couretesy

**Windows 10 machine**

I have cloned this near my root to keep file paths short

C:\Training\eShopOnContainers

**Docker Version**
```

C:\.....\eShopOnContainers\src>docker version
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:56 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**gitlog (so you can see the code git checksum.)**

```

C:\...... qeShopOnContainers\src>git log
commit 5c57b8c3f9b705c5be0890416d9005fca36f6ffe (HEAD -> dev, origin/dev, origin/HEAD)
Author: AlanYu <alan0428a@gmail.com>
Date:   Wed Jul 7 15:34:25 2021 +0800

    Binding queue using existing cosumerChannel (#1716)

    Co-authored-by: Alan.Yu <alan.yu@hidglobal.com>
```

**### Alternatives**
I have cloned the repo again and used a recent commit. I used the following version (about 2 weeks old)

commit 2afc00360f55e288b95a81d8c22cfc318971a287
Author: Sumit Ghosh <sumit.ghosh@neudesic.com>
Date:   Mon Jun 28 19:16:00 2021 +0530

    Included Envoyproxy firewall rules in the script (#1704)

This allowed me to progress the build - next stop docker-compose up

**Comment by sughosneo** [comment]
Hi @RobAllan27, thank you for reaching out and the details. 
Could you please take the latest from the `dev` branch and try to build the solution? 
Then you can run the `docker-compose up` command from the `/src/` directory to run the app.

**Comment by RobAllan27** [comment]
Sure will do - I will test this out, but gonna be tomorrow tho coz got an
interview to prepare for.. thanks Rob

**Comment by sughosneo** [comment]
Hi @RobAllan27, just checking if you had a chance to test this solution out further. Thank you.

**Comment by sughosneo** [comment]
Hi @RobAllan27, I am closing this issue as of now. Please feel free to reopen if needed. Thank you.
