### ISSUE TITLE
SeedWork Shared Library

### ISSUE THREAD

**Issue by lixaotec** [dotnet/eShopOnContainers#1722]
Dear folks,

Just a question regardin best practice/architecture.

Could folder \SeedWork become a shared library among Services? 

Thanks

**Comment by lixaotec** [comment]
Perhaps I missed out to say, in the case I have other microservices

**Comment by sughosneo** [comment]
Hi @lixaotec , thank you for reaching out. 

You can have `seedworks` as a shared library. For more details please refer [Seedwork (reusable base classes and interfaces for your domain model)](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/seedwork-domain-model-base-classes-interfaces)

**Comment by lixaotec** [comment]
Thanks @sughosneo !

Thats is exactely what I was looking for.
