### ISSUE TITLE
Helm Mal-Config for Shell Usage

### ISSUE THREAD

**Issue by darklight147** [dotnet/eShopOnContainers#1723]
In the Deployment phase, some might use the  `deploy-all.sh` file, but it's lacking some configuration that is present in the other forms of the script, like deploy-all.ps1 & deploy-all-mac.ps1, like imagePullPolicy etc

**Comment by sughosneo** [comment]
Hi @darklight147, thank you for your feedback. 

Yes, the `deploy-all.sh` bash script needs improvement. I am marking it under enhancement and including it in the backlog. 
But in the meantime, if anyone submits a PR with the changes, we will be happy to review and merge the changes in the dev branch.

**Comment by sughosneo** [comment]
Closing this issue as the related PR has been merged now. Thank you.
