### ISSUE TITLE
Kafka Implementation

### ISSUE THREAD

**Issue by darklight147** [dotnet/eShopOnContainers#1724]
Is the event-bus Implementation Agnostic in the project, or it's hard coupling for RabbitMQ specifically

I would like to know if the code in the project is neutral to which event bus is running

**Comment by sughosneo** [comment]
Hi @darklight147, thank you for reaching out. 

`IEventBus` interface is agnostic to any specific service bus tool.
https://github.com/dotnet-architecture/eShopOnContainers/blob/dc6028010127efd06289fa455213db2febf99b7e/src/BuildingBlocks/EventBus/EventBus/Abstractions/IEventBus.cs#L5 

You can initialize this with either to use RabbitMQ or Azure Service Bus. For e.g :
https://github.com/dotnet-architecture/eShopOnContainers/blob/dc6028010127efd06289fa455213db2febf99b7e/src/Services/Basket/Basket.API/Startup.cs#L282

If you want any other service messaging solution for your [asynchronous messaging](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Asynchronous-messaging) you can easily extend that by implementing the `IEventBus` interface in your concrete EventBus class.

**Comment by darklight147** [comment]
Thanks much, this is what i needed to know, glad to hear the design was soft coupled

**Comment by sughosneo** [comment]
Great! I am closing this issue as of now. Please feel free to reopen if needed.
