### ISSUE TITLE
Declarative way to define RabbitMQ channels and Subscriptions  

### ISSUE THREAD

**Issue by darklight147** [dotnet/eShopOnContainers#1730]
Most microservices communicate between eachother using event bus, but i noticed that most of these services have the channel and the Subsciption name hardcoded, which means you have to also type is in both the consumer service and the emitter service, and i wonder is this the best approach, is this how people does it, or there is a better declarative way to define the Subscription channell for both the consumer and publisher

**Comment by sughosneo** [comment]
Hi @darklight147, thank you for reaching out.

Yes, microservices communicate with each other using `EventBus`. Now for each service registration to the subscription happens in the `Startup.cs` class. For e.g :

https://github.com/dotnet-architecture/eShopOnContainers/blob/a478fdabf6440c51d94f4cf7c32ef5926a26af54/src/Services/Basket/Basket.API/Startup.cs#L120

You'll also need to register different events which a service needs to subscribe to. And that happens in the following step:

https://github.com/dotnet-architecture/eShopOnContainers/blob/a478fdabf6440c51d94f4cf7c32ef5926a26af54/src/Services/Basket/Basket.API/Startup.cs#L319

For a service it's required to be listening to a specific events for its take an actions on that event. 

For the RabbitMQ, we always use one instance of the channel `_consumerChannel` for all the operation and it gets created and manged within the `EventBusRabbitMQ` class. For e.g:

https://github.com/dotnet-architecture/eShopOnContainers/blob/a478fdabf6440c51d94f4cf7c32ef5926a26af54/src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.cs#L41

**Comment by darklight147** [comment]
Yes, but from what i understand, both the publisher and the consumer need to know the name of the event right?, so we find that in two or more Services the same name of the Event, is there a way to instead of typing the name of the event that the service is consuming, declare it globally, maybe in helm or kubernetes file,

i also noticed here 

```java
                    var subscriptionClientName = Configuration["SubscriptionClientName"];
```

that the `SubscriptionClientName` is coming from the appSettings.json, can we make the code get the SubscriptionClientName from the global declaration, helm or yml file etc....

Maybe am not undertstanding the structure very well

**Comment by sughosneo** [comment]
Yes, you can pass the `SubscriptionClientName` as part of the `helm` configuration or as an environment variable within the `docker-compose` override file.

But for the events, though you need a `name` to subscribe to that, you may not want to maintain the configuration and actual event class name separately. That's the reason in the eShop app has `IEventBus` interface, which helps a microservice to subscribe to a single/multiple events based on the need. If a service needs to take action on any other event, it just needs to implement a handler and subscribes to that event in its `Startup.cs` class.

https://github.com/dotnet-architecture/eShopOnContainers/blob/a478fdabf6440c51d94f4cf7c32ef5926a26af54/src/BuildingBlocks/EventBus/EventBus/Abstractions/IEventBus.cs#L9

**Comment by darklight147** [comment]
i dunnot understand this structure 
![image](https://user-images.githubusercontent.com/39389636/127345534-4e7bff06-579c-4dfd-beb7-4521357cad58.png)

On the left it's the key, but where does the value come from ? is that just a placeholder?

**Comment by sughosneo** [comment]
These values get populated from the `.env` file. 
https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/.env
If the value of the key is not set in the env file then it gets replaced with the default value.

**Comment by darklight147** [comment]
Oh okay i see, does the default value get set in the code it self, or is it something in docker & helm

**Comment by sughosneo** [comment]
Default value get set in the environment configuration itself. For e.g: in the container if '$ESHOP_AZURE_SERVICE_BUS' doesn't get passed/set then it would assign `rabbitmq` as default value to `EventBusConnection` env variable. 

For more details, you can always refer https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution

**Comment by sughosneo** [comment]
Considering the original question has been answered already, I am closing this issue as of now. Please feel free to reopen, if need. Thank you.
