### ISSUE TITLE
Build failed due to connection failure from cloudflare.com

### ISSUE THREAD

**Issue by nicholasyin** [dotnet/eShopOnContainers#1735]
If I can't access cloudflare.com, I can't build the solution.

**Comment by sughosneo** [comment]
Hi @nicholasyin, thank you for reaching out. 

What's the error message when you were trying to build?

**Comment by nicholasyin** [comment]
> Hi @nicholasyin, thank you for reaching out.
> 
> What's the error message when you were trying to build?

![image](https://user-images.githubusercontent.com/17007651/128495924-9481f8f9-5624-43df-bc1d-cb930b4f929e.png)

**Comment by sughosneo** [comment]
Ah ok, yes few of the JavaScript/CSS files have dependencies on `cdnjs.cloudflare.com` CDN. If it's blocked in your environment, then you may face issues while running the application.

You can refer to this similar issue https://github.com/dotnet-architecture/eShopOnContainers/issues/1169

**Comment by nicholasyin** [comment]
Do you have any plan to remove this dependency? After all, the point of this project is to demonstrate the design and use of microservices. Why would it get constrained by the CDN chosen?

**Comment by sughosneo** [comment]
Hi @nicholasyin, we don't have any plan to remove this dependency at the moment. Besides interim issues in CDN, we have not had anyone else complain about this before. We rely on the CDN to deliver these js files faster on user machines. Also, since we do not make changes to these files, it reduces the effort to maintain these on our repo. I hope it clarifies.

I am closing this issue as of now. Please feel free to reopen if needed. Thank you.

**Comment by nicholasyin** [comment]
At least there should be an option to choose which CDN to use, or at least to download from the official source. Limiting it to a specific CDN, not the official source, is not logical, regardless of how many people have complained.

**Comment by oshabanisbg** [comment]
Hi,

i have the same error , for different internet connection

**Comment by brSaif** [comment]
> i have the same error , for different internet connection

Hi @oshabanisbg, Maybe the guide in the following answer can solve your issue as it did for me.
https://stackoverflow.com/questions/56748429/libman-error-lib002-during-build-application
