### ISSUE TITLE
Problem deploying the API gateways using deploy-all.sh

### ISSUE THREAD

**Issue by oliviergaumond** [dotnet/eShopOnContainers#1738]
I am using the deploy\k8s\helm\deploy-all.sh script to try to deploy the application on AKS using Azure Cloud Shell.

Everything deploys fine using the default public images or a private registry hosted with ACR. However, the two API gateways (apigwms and apigwws) are not deploying correctly with an ImagePullBackOff error.

The equivalent PowerShell script works correctly and I see the ps1 script has a specific logic to install the charts for the API gateways. The bash script tries to install those two charts with the same parameters than the other ones, however those two are using envoy images that are not expected to be in our private registry and have the 'linux-dev' tag used by the other images.

Updating the script using the same logic than the Power Shell script fixes the issue. See my updated version in my fork here: https://github.com/oliviergaumond/eShopOnContainers/commit/f4546290c59b7c3952407aff5d8f641d680cbd97

If this is the indented behavior I can submit a PR to fix this. If I misunderstood something, please let me know.

**Comment by sughosneo** [comment]
Hi @oliviergaumond, thank you for bringing it up.

Yes, the `deploy-all.sh` bash script needs improvement. It's been discussed in this issue https://github.com/dotnet-architecture/eShopOnContainers/issues/1723 as well. Please feel free to submit a PR. We will be happy to review and merge the changes in the dev branch.

**Comment by oliviergaumond** [comment]
I will work on a PR to address this and #1723 and submit it in the next few days

**Comment by sughosneo** [comment]
Closing this issue as the PR is already merged.
