### ISSUE TITLE
Errors in deployment script for GitHub Actions

### ISSUE THREAD

**Issue by oliviergaumond** [dotnet/eShopOnContainers#1739]
There are some errors in the shell script proposed to deploy the infrastructure for GitHub Actions here
https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deployment-With-GitHub-Actions

This line
```
# set the k8s context locally
az get-credentials -g $rg -n $aks
```

should be
```
# set the k8s context locally
az aks get-credentials -g $rg -n $aks
```

I also get an error with this line, it won't find the Service Principal with the name, it expects an object ID
```
spnId=$(az ad sp show --id http://$spnName --query appId --output tsv)
```

This could be an issue in the Azure CLI as reported here: https://github.com/Azure/azure-cli/issues/19179

In the meantime this alternate version seems to work, however `--display-name` isn't an exact match, it could return multiple results if multiple spn share the same prefix
```
spnId=$(az ad sp list --display-name http://$spnName --query [0].appId)
```

Let me know if there is a better way to contribute changes to the Wiki than opening an issue.

**Comment by sughosneo** [comment]
Hi @oliviergaumond, thank you for your feedback. Great catch 👍 

Unfortunately, there is no direct way to update the wiki with the help of PR. So, I have updated the instructions mentioned on the `Deployment With GitHub Actions` page. You can take a look and share your thoughts if something more is missing. Please feel free to report it as an issue with the details. We'll be able to validate and update if necessary.

**Comment by oliviergaumond** [comment]
The changes look good.

I think there was a small mistake in one of my suggested line. We should specify tsv output for the command, otherwise the text is qualified with quotes.

```
spnId=$(az ad sp list --display-name http://$spnName --query [0].appId  --output tsv)
```

**Comment by sughosneo** [comment]
Ah ok. That's right. I have updated the instructions.

I am closing this issue as of now. Please feel free to reopen if it's needed.
Thank you.
