### ISSUE TITLE
Multi currencies support

### ISSUE THREAD

**Issue by abodehq** [dotnet/eShopOnContainers#1744]
Dears ,

Great work,

can you please advice on what is the best way to implement multi currency support .??
and also if you can how can it support also multi language in microservice world?

thanks again.

**Comment by sughosneo** [comment]
Hi @abodehq, thank you for your feedback.

***For the currency support, it depends on your business requirement.***
For e.g : Let's say if you have a Payment microservice that interacts with an external Payment Gateway that accepts multicurrency *(US Dollars/Euro/INR etc..)*, then in that scenario, your `Payment microservice` you can accept/process requests that contain difference currencies.


***I am not sure if I understand the term `multi language` exactly.***
`Did you mean you can have one microservice written in `C#` another one written in `Python`?` -  Then yes, you can have Polyglot microservices.
`On the other hand, if you were referring to the `Globalization and localization` concepts?` -  Then yes, you can do that too by using Resource Files. For more details, please refer to the [Resource files](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-5.0#resource-files) section.

Hope this helps!

**Comment by abodehq** [comment]
Thanks for the quick response.

I am new to microservice world so i hope you can guide me thru this.

i build Product service which is contain a field called price for example : 20 and the value based on $ ,

so if user select change currency to euro then our currency service know that the conversion rate forexample .85 

then the price will be 20*.85 = 17.02 Euro

my questioin this conversion calculation what is the best way to do ?

1- client side save the conversion rate and then when the response came from product service we do the conversion on client side?
2- on product service : we add a clone table of the conversion rates and then process the calculation on the product service.
3-on the gate way we call the product service and currency service , edit the response on the gateway and return to client .

i am new so please let me know what do you think.

-------------

about the localization my concern is about the entity translation like for product service we need to translate name,description,.... so shall we add a translation table for each service to handle the entity or there is a better solution to do this task.


thanks again,
abed

**Comment by sughosneo** [comment]
Thank you @abodehq, for sharing all the details.

Ideally, you should avoid doing any conversion of your own. It's better to rely on Payment Gateway.
For an e.g: you can store the currency value as per below with the `currency_code` for each of your transactions and then you can pass on the data to the Payment Gateway to do the calculation for you.

| .... | currency_val | currncy_code | currency_rate | transaction_date_time | .... |
|------|--------------|--------------|---------------|-----------------------|------|
|      | 100          | USD          | 0.85          |                       |      |
|      | 200          | EUR          | 1.18          |                       |      |
|      |              |              |               |                       |      |

And regarding the localization aspect, it's better to handle one type of language format for all of your microservices and let the conversion happen on the UI side.

Hope this helps!

**Comment by sughosneo** [comment]
Hi @abodehq, I am closing this issue as of now as the original question has already been answered. But please feel free to reopen this issue or create a new one if you have any further questions. Thank you.
