### ISSUE TITLE
Polly not used with EF Core DbContext

### ISSUE THREAD

**Issue by sameer-kumar** [dotnet/eShopOnContainers#1758]
I have noticed while referencing your codebase that Polly is used for areas like RabbitMQ however not with EF Core DbContext calls nor with repositories. Is there any reason for this choice or just by preference?

Thanks!

**Comment by sughosneo** [comment]
Hi @sameer-kumar, thank you for reaching out. 

`Polly` retry mechanism has been configured during the database migration. Please refer to the below code snippets.  

https://github.com/dotnet-architecture/eShopOnContainers/blob/93383de096bd204232f46b415d2b1f81e9af64c3/src/Services/Ordering/Ordering.API/Infrastructure/OrderingContextSeed.cs#L25

https://github.com/dotnet-architecture/eShopOnContainers/blob/93383de096bd204232f46b415d2b1f81e9af64c3/src/BuildingBlocks/WebHostCustomization/WebHost.Customization/WebHostExtensions.cs#L41

Were you trying to refer something else?

**Comment by sameer-kumar** [comment]
Yeah @sughosneo, I noticed that too. However, I was referring to EF DbContext calls made for the application. E.g. I referred the [OrderContext](https://github.com/dotnet-architecture/eShopOnContainers/blob/d0cd2830a864a8b975341b02b93a0887a3908c04/src/Services/Ordering/Ordering.Infrastructure/OrderingContext.cs) but couldn't see any Polly policies in there.

**Comment by sughosneo** [comment]
Ah ok. Entity Framework (EF) Core already provides internal database connection resiliency and retry logic. Actually for `OrderContext ` it's implemented in `Startup.cs` in the `services.AddDbContext<>` step. Here is the code snippet with that implementation.

https://github.com/dotnet-architecture/eShopOnContainers/blob/d0cd2830a864a8b975341b02b93a0887a3908c04/src/Services/Ordering/Ordering.API/Startup.cs#L233

For more details you can also refer to [Implement resilient Entity Framework Core SQL connections](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-resilient-entity-framework-core-sql-connections)

**Comment by sameer-kumar** [comment]
To me it seems you are relying on just vanilla retry. Correct me if I'm wrong? What if with every retry attempt you need to wait exponentially before trying it again? And if the error persists even after Nth attempt, you want to break the circuit for the next N seconds. Finally, if the failure still exists, degrade gracefully using a fallback. Do you think these are all valid cases for cloud resilient apps like yours?

**Comment by sughosneo** [comment]
Yes, though Polly is not used in this scenario. But, the retry still gets randomized by the `maxRetryDelay` configuration.  For more details, please refer to this discussion [When configuring RetryOnFailure what is the maxRetryDelay parameter](https://stackoverflow.com/questions/55827106/when-configuring-retryonfailure-what-is-the-maxretrydelay-parameter)

In the production scenario, you may want to offload these functionalities to a service mesh to build and deploy more resilient cloud-native apps. [Implement resiliency in a cloud-native ASP.NET Core microservice](https://docs.microsoft.com/en-us/learn/modules/microservices-resiliency-aspnet-core/?WT.mc_id=dotnet-35129-website&ns-enrollment-type=Collection&ns-enrollment-id=8mq4i2mzgjwn10) MS learn module explains similar aspects in more detail. You may want to check that as well.

**Comment by sughosneo** [comment]
Hi @sameer-kumar, considering the original question has been answered, I am closing this issue as of now. Please feel free to reopen this if needed. Thank you.
