### ISSUE TITLE
Usage of Context.DbSet<T>.Local in the repository implementation.

### ISSUE THREAD

**Issue by senal** [dotnet/eShopOnContainers#1760]
Hi,

I'm just trying to understand the usage/purpose of the following line of the OrderRepository implementation.
Line 40 - 46 in the current implementation of OrderRepository.

````
           if (order == null)
            {
                order = _context
                            .Orders
                            .Local
                            .FirstOrDefault(o => o.Id == orderId);
            }
````
Also, why we required the `Local` property?
Why can't access the `FirstOrDefault` extension methods on `Local` property?

Appreciate it if someone can provide some insight into my above questions.

Cheers,

**Comment by sughosneo** [comment]
Hi @senal, thank you for reaching out. 

The purpose of using `Context.DbSet<T>.Local` to keep tracking those inmemory objects whose state state has modified but has been persisted yet to the data store by the context yet.
For more details, please refer to [Local Data](https://docs.microsoft.com/en-us/ef/ef6/querying/local-data)

**Comment by sughosneo** [comment]
Considering the original question has been answered, I am closing this issue as of now. Please feel free to reopen if you have any further questions. Thank you.
