### ISSUE TITLE
Is there any particular reason to have <xxx>IntegrationEventService implement IDisposable?

### ISSUE THREAD

**Issue by nicholasyin** [dotnet/eShopOnContainers#1763]
Can't help wondering the purpose of using `private volatile bool disposedValue;` in every implementation of integration event service, as well as the
 ```
        protected virtual void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                    (_eventLogService as IDisposable)?.Dispose();
                }

                disposedValue = true;
            }
        }

        public void Dispose()
        {
            Dispose(disposing: true);
            GC.SuppressFinalize(this);
        }
```
code snippet. What are they, and is it really necessary to do so?

**Comment by sughosneo** [comment]
Hi @nicholasyin, thank you for reaching out.

Variable `private volatile bool disposedValue` acts as a flag to check if the object is already disposed or not.
For more details, please refer to [Implement a Dispose method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose)

**Comment by nicholasyin** [comment]
@sughosneo So why was the dispose mechanism implemented like this? What's the problem of using the normal way of Dispose method, or even not implementing IDisposable at all? The only thing that will get disposed of, as far as I can tell, is the DbContext for integration event log. Don't know why this context requires explicit disposal, unlike the regular business DbContext that got injected in many places.

**Comment by sughosneo** [comment]
For more context, issue https://github.com/dotnet-architecture/eShopOnContainers/issues/1392

**Comment by nicholasyin** [comment]
Well, the integration services are not wrapped in any usings, instead they are used just like any regular injected scoped service in the controller. So I don't really see the reasoning of implementing IDisposable here.

Furthermore, I'm more confused about the use of volatile boolean variable. Not a clue of why it is done this way.

**Comment by erjain** [comment]
Considering the original question has been answered, I am closing this issue as of now. Please feel free to reopen if needed. Thank you.

**Comment by nicholasyin** [comment]
psst... don't see any sign of an answer.
