### ISSUE TITLE
[Question] ClientRequest - Idempotency

### ISSUE THREAD

**Issue by ivanekel** [dotnet/eShopOnContainers#1766]
Hi everyone. I have a question about domain models in [Ordering](https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/src/Services/Ordering) project. Mainly on [ClientRequest.cs](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.Infrastructure/Idempotency/ClientRequest.cs).
Depending on Clean architecture / DDD concepts domain entities must live in the domain layer 
![image](https://user-images.githubusercontent.com/50170762/135452131-f2b54718-b217-490c-aed3-31eda5be4260.png)

so what is the goal of placing ClientRequest.cs in the Infrastructure layer which is also part of [OrderingContext](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.Infrastructure/OrderingContext.cs) and not in the Domain layer?

**Comment by nhdinh** [comment]
@ivanekel in DDD, the term Bounded Context or in architectural term, Domain Layer, both refer to all the entities that are in the business workflow, herein is the Ordering. In this business workflow, the entities are the Order, OrderItem and Address..., those are the things that contains data in real life as well.
In the other side, OrderingContext and ClientRequest are the helpers (or can be called Infrastructure) that helps Domain layer working with things outside boundary. Therefore, I see no wrong putting OrderingContext and ClientRequest out of Domain Layer.

**Comment by erjain** [comment]
Thanks for the clarification @ivanekel.
Considering that the original question has been answered, I am closing this issue as of now. Please feel free to reopen if needed. Thank you.

**Comment by erjain** [comment]
Thanks for the clarification @ivanekel.
Considering that the original question has been answered, I am closing this issue as of now. Please feel free to reopen if needed. Thank you.
