### ISSUE TITLE
webspa docker-compose build fails

### ISSUE THREAD

**Issue by mohammed-ehsan** [dotnet/eShopOnContainers#1768]
The project does not build because ` RUN npm i npm@latest -g && npm update && npm install && npm run build:prod` fails

I have tried removing 'npm update', so that npm will not be updated to make the system use npm version that comes with Node. I have tried using --force attribute as well with no success.

Error screenshot:
![image](https://user-images.githubusercontent.com/25776171/136495543-535d9e67-197d-44ee-9f03-94fbc2548a6b.png)

Thanks!

**Comment by sughosneo** [comment]
Hi @mohammed-ehsan, thank you for reaching out. 

Did you take the latest from the `dev` branch and try to build again?

**Comment by mohammed-ehsan** [comment]
@sughosneo Thank you for reaching back!
I was trying to build from the main branch. The dev branch fails to build, as it is unable to load the nuget packages, I have not investigated it yet. However, according to the documentation the main branch should be functional at all times.

Screenshot of dev branch docker-compose build failure for reference:
![image](https://user-images.githubusercontent.com/25776171/136520696-c4f42f3b-79f1-47bf-8604-426ee2b2f2e3.png)

**Comment by sughosneo** [comment]
Hi @mohammed-ehsan, I just took the latest from the `dev` branch and did build the solution using the `docker-compose build` command. It worked fine for me. Could you please clear the Nuget cache and try again? You can do that by following:

From Visual Studio : 

```text
- Tools > Options > NuGet Package Manager > General > Clear All NuGet Cache(s)
```

From the File Explorer :

```text
- Delete C:\Users\<user-name>\xxx.nuget\packages
```

**Comment by sughosneo** [comment]
Hi @mohammed-ehsan, just checking if you had a chance to look into this further. Thank you.

**Comment by sughosneo** [comment]
I am closing this issue as of now. Please feel free reopen if needed. Thank you.
