### ISSUE TITLE
Why we have separate Ordering.Infrastructure project in Ordering service ONLY when each service has its own Infrastructure folder

### ISSUE THREAD

**Issue by rizwaanbutt** [dotnet/eShopOnContainers#1787]
Hi everyone,

I am new to micro-services and trying to understand best practices for implementing micro-services for our upcoming project.

My question is, why we are having a separate class project Ordering.Infrastructure inside Ordering service (Ordering folder) ONLY when we are following the same pattern to have Infrastructure folder its own service folder?

This is causing confusion, shouldn't we move EntityConfigurations, Idempotency folder to Ordering.API folder?

Thanks and Regards,
/Rizwan

**Comment by sorcerb** [comment]
Hello,
There are  two articles about this:
[Creating a simple data-driven CRUD microservice](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/data-driven-crud-microservice)
[Design a DDD-oriented microservice](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/ddd-oriented-microservice
)

**Comment by erjain** [comment]
Thanks for sharing the links @sorcerb.
I am closing this issue as of now. Please feel free to reopen it, if needed.

**Comment by erjain** [comment]
Thanks for sharing the links @sorcerb.
I am closing this issue as of now. Please feel free to reopen it, if needed.
