### ISSUE TITLE
Build failed with Visual Studio 2022

### ISSUE THREAD

**Issue by Nikkelmann** [dotnet/eShopOnContainers#1788]
**Error message:** Missing partial modifier on declaration of type 'Program'; another partial declaration of this type exists
**Branch:** dev
**Files:**
- \src\Web\WebStatus\Program.cs
- \src\Web\WebMVC\Program.cs
- \src\Services\Basket\Basket.API\Program.cs
- \src\Services\Catalog\Catalog.API\Program.cs
- \src\Services\Ordering\Ordering.API\Program.cs
- \src\Services\Ordering\Ordering.SignalrHub\Program.cs
- \src\Services\Payment\Payment.API\Program.cs

Visual Studio info:
```
Microsoft Visual Studio Professional 2022
Version 17.0.0
VisualStudio.17.Release/17.0.0+31903.59
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional
```

Both .NET 5 and .NET 6 is installed.

**Comment by nishanil** [comment]
@Nikkelmann Thanks for reporting this. We are working on the updates. Try this PR: https://github.com/dotnet-architecture/eShopOnContainers/pull/1786 
cc @sughosneo

**Comment by Nikkelmann** [comment]
@nishanil The PR works better, but fails to build the WebStatus project producing the same errror message.

**Comment by nishanil** [comment]
@Nikkelmann We merged .NET 6 updates to dev branch today. We have updated the Web Status project too. Please let us know if you are able to compile them now.

**Comment by ASPMartin** [comment]
I have been able to successfully build the latest from the dev branch with VS 2022. The browser does launch and show a 503 error initially, but on refresh, or when debugging it does load the home page. Based on the comments in the setup guide, this seems to be normal.

**Comment by gaetandezeiraud** [comment]
Worked like a charm for me!

**Comment by nishanil** [comment]
Cool, Thanks for reporting back. I will close this issue now.
