### ISSUE TITLE
dotnet 6 Minimal API

### ISSUE THREAD

**Issue by abritabroad** [dotnet/eShopOnContainers#1791]
Are you planning on upgrading the services to use Minimal API and remove Startup.cs?

I tried with my own app but got stuck with my functional tests. I couldn't get WebApplicationFactory or TestServer to work with the new model.

Thanks!

**Comment by nishanil** [comment]
@abritabroad Thanks for reaching out. At the moment, we don't plan to remove the Startup.cs in the existing projects. We may consider them in the future for smaller projects.

**Comment by abritabroad** [comment]
Thanks for the feedback!
