### ISSUE TITLE
Orchard CMS as administrator backend?

### ISSUE THREAD

**Issue by gaetandezeiraud** [dotnet/eShopOnContainers#1792]
Hi!
First, thanks for the repo, a very good way to learn micro-architecture in asp.net!
I want to know if it is planned or at least possible to add Orchard CMS as an administrator backend to fulfill products. Add new, remove, see commands... Seems possible? As a headless CMS.

Thanks.

**Comment by nishanil** [comment]
@Brouilles Not at the moment :) We just want to keep this sample as simple as possible. Feel free to fork this repo and add Orchard CMS there. Happy to link to that from our wiki.
