### ISSUE TITLE
Some redundant injections in commands

### ISSUE THREAD

**Issue by mmramezani** [dotnet/eShopOnContainers#1795]
https://github.com/dotnet-architecture/eShopOnContainers/blob/9e5cd835b44aaa65c885d1a22165a3136a67b402/src/Services/Ordering/Ordering.API/Application/Commands/CreateOrderDraftCommandHandler.cs#L12

Hi guys
As I see there is a MediatR decreation and injection which is not needed. Also observed cases like this in other places.

**Comment by erjain** [comment]
The issue can be closed now.
