### ISSUE TITLE
Mac OS Monterey - Docker 20.10.10 - docker.for.mac.localhost no longer working

### ISSUE THREAD

**Issue by ChrisHolcomb** [dotnet/eShopOnContainers#1799]
I'm not sure if this is something new with Docker 20.10.10, or running on Mac OS Monterey or something else in my config but the only way to get everything up and running was to replace all instances of docker.for.mac.localhost and docker.host.internal to just localhost. Once I updated all references I was able to see the images on the SPA app, the catalog service returned records and I was able to sign-in using IdentityServer.

Has anyone else had this issue. If something changed then the instructions on the main page should be updated.

**Comment by berkuttech** [comment]
I'm struggling to take the project up on docker as well.

#229 17.78 /root/.nuget/packages/grpc.tools/2.34.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : Google.Protobuf.Tools cannot determine host OS and CPU. [/src/ApiGateways/Mobile.Bff.Shopping/aggregator/Mobile.Shopping.HttpAggregator.csproj]

**Comment by Atantares** [comment]
> I'm struggling to take the project up on docker as well.
> 
> #229 17.78 /root/.nuget/packages/grpc.tools/2.34.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : Google.Protobuf.Tools cannot determine host OS and CPU. [/src/ApiGateways/Mobile.Bff.Shopping/aggregator/Mobile.Shopping.HttpAggregator.csproj]

If you use M1 then you need to update all Grpc packages to 2.44 version. This version has support of ARM

**Comment by erjain** [comment]
Hi @ChrisHolcomb, There was an [issue ](https://github.com/dotnet-architecture/eShopOnContainers/issues/1771) reported on M1 Mac, which was resolved, sharing link which you can refer to: https://github.com/dotnet-architecture/eShopOnContainers/issues/1771. Hope this helps.

**Comment by erjain** [comment]
I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
