### ISSUE TITLE
Debugging fails with 504 (Gateway Timeout)

### ISSUE THREAD

**Issue by anet256** [dotnet/eShopOnContainers#1801]
Slow debugging of microservices code together with WebMVC always fell into 504 (Gateway Timeout). The timeout is somewhat like 30 sec. If you run application without debugging, or debug microservices extremely fast, everything works OK. How to increase this timeout?
![image](https://user-images.githubusercontent.com/33517691/144168866-9abb7098-c5b3-4407-9b29-22928c9ede75.png)

**Comment by erjain** [comment]
You can update code in the controller to increase the timeout as follows 
System.Web.HttpContext.Current.Server.ScriptTimeout = 300. Let me know if this works.

**Comment by erjain** [comment]
Hi @anet256, 
I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
