### ISSUE TITLE
Why is double used for price instead of decimal?

### ISSUE THREAD

**Issue by HummingMind** [dotnet/eShopOnContainers#1803]
Hello. I was trying to check and see how you dealt with GRPC not having a well-known-type for decimal, only to find out that double is being used instead of decimal for prices.

Should this project be updated to use decimal and show how decimal should be handled in GRPC?

I found the approach with units and nanos, but just wanted to see what you would prefer to use here.

Thank you.

**Comment by erjain** [comment]
Due to less complexity of values, we have used double and protobuf does support floats and double only, but you can implement decimal in gRPC by creating custom types. Please find the illustration for the same by clicking on the link: https://itnext.io/net-decimal-datatype-in-grpc-51c2ddb1c153

**Comment by erjain** [comment]
I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
