### ISSUE TITLE
Invalid Operation Exception

### ISSUE THREAD

**Issue by badbobo911** [dotnet/eShopOnContainers#1806]
Hi, 

Followed directions to install on Mac and when navigating to the mvc app received the following error. 
[Internal Server Error.pdf](https://github.com/dotnet-architecture/eShopOnContainers/files/7736687/Internal.Server.Error.pdf)

**Comment by erjain** [comment]
Hi @badbobo911, Try the suggestion given on issue #1771. Hope it helps.

**Comment by erjain** [comment]
I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
