### ISSUE TITLE
How to have an efficient Debugging on eShopOnContainers in vs 2022 

### ISSUE THREAD

**Issue by PSepah** [dotnet/eShopOnContainers#1808]
Hi all,
By hit f5 on eShopOnContainers with docker-compose debug, It is possible to debug .net core codes but it is impossible to debug angular ts files because all breakpoints are unbounded. Would you please describe how can we debug the webSPA on docker container? it is possible to ng start locally and use attach the process but to work with other echo systems, I need to debug it under 50124 port. I tried to attach WebSPA server but it was not useful.
Thanks in advanced :-)

**Comment by PSepah** [comment]
I found this topic useful:
https://github.com/dotnet-architecture/eShopOnContainers/wiki/06.-(Optional)-Setting-the-Web-SPA-application-up
but still, it seems there is an issue under "Build the SPA app with NPM" title. we cannot launch npm install in "src\Web\WebSPA" folder. If you launch it here you will face this error:
 ENOENT: no such file or directory, open 'D:\SC\eShopOnContainers\src\web\WebSPA\package.json'
Instead we should launch it in "src\Web\WebSPA\Client".
Am I right?

**Comment by PSepah** [comment]
After work around this issue if found the following solution:
**problem:**
After hitting f5, when debugger profile is set on docker-compose, Breakpoints in WebSPA project on typescript files (ts) is unbounded.
**Solution:**
1- close all opened browsers
2- after launching default chrome browser on http://host.docker.internal:5100, change the port to http://host.docker.internal:5104/catalog and wait to launch WebSPA properly
3- use f12 and open webpack:// folder then . folder and then src folder
4- find your ts file and set breakpoints
5- After launching the browser again, Automatically symbols will loaded for your breakpoints in ts files and you can debug ts file under visual studio 2019

**Which problem still is reamainding:**
If you update ts,html files it is not immediately build like you have ng serve. I am looking a proper way to debug frontend and backend (all the eco systems) in one IDE (Visual studio 2019). 

**My solution**
It is not proper way to hit f5 under docker-compose debug profile, Instead, the better way is to hit ctr+f5 to build the eco-system. Then localhost:<port which has been setting in debug profile> should add in Microsoft.eShopOnContainers.Service.IdentityDb.ClientRedirectUris, as well as this set WebSPA as startup project and finally hit f5.
By this method you can debug WebSPA locally and whenever you change the ts files the browser will refresh and you can see the result. But still the issue is, your changes are not effected in debug mode. You should stop and hit f5 again to have the changes in debug mode.

Anybody have another solution?
Best regards

**Comment by josephwambura** [comment]
Not sure if this helps you [WebSPA project doesn't come up on debug mode in Visual Studio 2019](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Frequent-errors#webspa-project-doesnt-come-up-on-debug-mode-in-visual-studio-2019)

**Comment by PSepah** [comment]
This is my final approach:
1- hit ctr f5 under docker-compose debug profile in vs 2022
2- After warm up the project, optionally on container tools use attach to process. Probably at the first time it will take too long but on the next time it is almost immediately. 

if you want to set your docker-compose project name, use `<DockerComposeProjectName>` and add your tag to `<PropertyGroup>` in docker-compose.dcproj. As well as this if you don't want to stop or close your docker containers after closing the solution you should change the parameters under tools->options-> container tools

**Comment by erjain** [comment]
Hi @PSepah, Thanks for addressing this scenario here. I am closing this issue, however, please feel free to reopen if needed.
