### ISSUE TITLE
VS 2022 & Docker won't start up

### ISSUE THREAD

**Issue by josephwambura** [dotnet/eShopOnContainers#1810]
VS 2022 & Docker won't start up, what could I be doing wrong?

[19:22:23 FTL] Program terminated unexpectedly (WebStatus)!
System.ArgumentException: The path must be absolute. (Parameter 'root')
at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.<>c.b__1_0(String contentRoot)
at Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider..ctor(StaticWebAssetManifest manifest, Func`2 fileProviderFactory)
at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)
at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment, IConfiguration configuration)
at Microsoft.AspNetCore.WebHost.<>c.b__9_0(WebHostBuilderContext ctx, IConfigurationBuilder cb)
at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
at Program.<

$>g__BuildWebHost|0_0(IConfiguration configuration, String[] args) in C:\BlahBlah\eShopOnContainers\src\Web\WebStatus\Program.cs:line 28
at Program.$(String[] args) in C:\BlahBlah\eShopOnContainers\src\Web\WebStatus\Program.cs:line 8

**Comment by josephwambura** [comment]
Identity DB error when connecting even on a new docker-compose up command, see image below

![image](https://user-images.githubusercontent.com/10076231/147169411-47b779cd-0d0f-4f6f-978a-17480378877c.png)

**Comment by PSepah** [comment]
Hi josephwambura,
As the log shows, There are some issues in regard with your connection string to the sql-server database. It causes not to set Microsoft.eShopOnContainers databases includes:
Microsoft.eShopOnContainers.Service.IdentityDb
Microsoft.eShopOnContainers.Services.CatalogDb
Microsoft.eShopOnContainers.Services.OrderingDb
Microsoft.eShopOnContainers.Services.WebhooksDb

It seems you first should get ride of this problem and most probably the source of problem is in your connection string.
to see these databases I use sql server management studio  with server name:localhost,5433.
Hope you sole the problem :-)

**Comment by josephwambura** [comment]
hello @PSepah , the clone was new, and the docker was reset. When I use sql server management studio with server name:localhost,5433 to view the databases, I only get:
Microsoft.eShopOnContainers.Services.CatalogDb
Microsoft.eShopOnContainers.Services.OrderingDb
Microsoft.eShopOnContainers.Services.WebhooksDb

**Comment by PSepah** [comment]
Hello @josephwambura,
It is possible there some error to create Microsoft.eShopOnContainers.Service.IdentityDb datavase. To get ride of this problem you can debug it. I suggest to set debug on decker-compose and start debugging. To find your database connection string in src\Services\Identity\Identity.API, you can visit AppSettings.cs and set breakpoints on IWebHostExtensions on line 67. You can check what is the problem here.
By the way there are .net 6 version that is most better for debugging. If you are using previous version it is better to upgrade it to the new version


Best regards

**Comment by Eduardo-Guedes** [comment]
> hello @PSepah , the clone was new, and the docker was reset. When I use sql server management studio with server name:localhost,5433 to view the databases, I only get: Microsoft.eShopOnContainers.Services.CatalogDb Microsoft.eShopOnContainers.Services.OrderingDb Microsoft.eShopOnContainers.Services.WebhooksDb

Put on Identity.API into appsettings.json:
`  "ConnectionString": "Server=tcp:127.0.0.1,5433;Initial Catalog=Microsoft.eShopOnContainers.Services.IdentityDb;User Id=sa;Password=Pass@word",
`

**Comment by nishanil** [comment]
Sometimes a failed startup can corrupt the entries in the databases. Can you delete all images and volumes or reset Docker and try again? I tried them on VS 2022, and it works as expected. Wait for the WebStatus project to show all the services healthy, before navigating to the Web Clients. There's a known issue for the WebSPA app and Visual Studio that we are tracking it here: https://github.com/dotnet-architecture/eShopOnContainers/issues/1821.

**Comment by josephwambura** [comment]
> > hello @PSepah , the clone was new, and the docker was reset. When I use sql server management studio with server name:localhost,5433 to view the databases, I only get: Microsoft.eShopOnContainers.Services.CatalogDb Microsoft.eShopOnContainers.Services.OrderingDb Microsoft.eShopOnContainers.Services.WebhooksDb
> 
> Put on Identity.API into appsettings.json: ` "ConnectionString": "Server=tcp:127.0.0.1,5433;Initial Catalog=Microsoft.eShopOnContainers.Services.IdentityDb;User Id=sa;Password=Pass@word",`

it is already there

`"ConnectionString": "Server=tcp:127.0.0.1,5433;Database=Microsoft.eShopOnContainers.Services.IdentityDb;User Id=sa;Password=Pass@word;",`

**Comment by josephwambura** [comment]
> Sometimes a failed startup can corrupt the entries in the databases. Can you delete all images and volumes or reset Docker and try again? I tried them on VS 2022, and it works as expected. Wait for the WebStatus project to show all the services healthy, before navigating to the Web Clients. There's a known issue for the WebSPA app and Visual Studio that we are tracking it here: #1821.


I had to uninstall Docker for it to cease throwing Db errors, however, it still has an issue finding the Absolute Path. see below image:

![image](https://user-images.githubusercontent.com/10076231/150583529-61a06d86-7af6-40ce-bddc-930721d04dc6.png)

**Comment by nishanil** [comment]
@josephwambura That is weird. After resetting Docker, without opening Visual Studio, can you try running the command `docker-compose up` ? Does that work?

**Comment by erjain** [comment]
@josephwambura You can double-check on SQL(sqldata) image, it should be up before other services start running so that there are no connectivity issues. Further, you can also follow the instructions on [windows-setup](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup) updated wiki page for more information. I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
