### ISSUE TITLE
Prompt to upgrade project to use Microsoft.TypeScript.MSBuild

### ISSUE THREAD

**Issue by nicholasyin** [dotnet/eShopOnContainers#1811]
<img width="781" alt="1640574572(1)" src="https://user-images.githubusercontent.com/17007651/147430416-cdf261ef-ec61-4875-ba4a-a8aa57670f8f.png">

Just want to make sure this is known and we don't need to do anything about it?

**Comment by erjain** [comment]
Thanks for reporting this, the warning is not appearing anymore, I am closing this issue as of now.
