### ISSUE TITLE
Can't start on Visual Studio 2022

### ISSUE THREAD

**Issue by xieyiincuit** [dotnet/eShopOnContainers#1812]
use the least dev branch, when build the solution successfully, start to start without debugging.
then pull all image down and create container, but the last step, when use "dotnet run" to start app, output windows show me can't find xxxxxx.dll for them.

docker exec -i 9762387e1246 sh -c ""dotnet"  --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  "/app/bin/Debug/net6.0/Basket.API.dll" | tee /dev/console"
docker exec -i 58d09f1b5313 sh -c ""dotnet"  --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  "/app/bin/Debug/net6.0/Catalog.API.dll" | tee /dev/console"
docker exec -i e4e24cc8b2f8 sh -c ""dotnet"  --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  "/app/bin/Debug/net6.0/Ordering.API.dll" | tee /dev/console"
docker exec -i -e ASPNETCORE_STATICWEBASSETS="/app/bin/Debug/net6.0/WebMVC.staticwebassets.runtime.DT.json" f851150eff78 sh -c ""dotnet"  --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  "/app/bin/Debug/net6.0/WebMVC.dll" | tee /dev/console"
docker exec -i -e ASPNETCORE_STATICWEBASSETS="/app/bin/Debug/net6.0/Identity.API.staticwebassets.runtime.DT.json" 39f3aca89a19 sh -c ""dotnet"  --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  "/app/bin/Debug/net6.0/Identity.API.dll" | tee /dev/console"
docker exec -i b4b6ab35331d sh -c ""dotnet"  --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  "/app/bin/Debug/net6.0/WebSPA.dll" | tee /dev/console"
docker exec -i -e ASPNETCORE_STATICWEBASSETS="/app/bin/Debug/net6.0/WebStatus.staticwebassets.runtime.DT.json" 89e37aba16be sh -c ""dotnet"  --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  "/app/bin/Debug/net6.0/WebStatus.dll" | tee /dev/console"
docker exec -i 03798d232aaa sh -c ""dotnet"  --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  "/app/bin/Debug/net6.0/Web.Shopping.HttpAggregator.dll" | tee /dev/console"
docker exec -i 208f9bd86efb sh -c ""dotnet"  --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  "/app/bin/Debug/net6.0/Ordering.SignalrHub.dll" | tee /dev/console"
docker exec -i ce71ba2452a0 sh -c ""dotnet"  --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  "/app/bin/Debug/net6.0/Payment.API.dll" | tee /dev/console"
docker exec -i e8f12e810948 sh -c ""dotnet"  --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  "/app/bin/Debug/net6.0/Webhooks.API.dll" | tee /dev/console"
docker exec -i -e ASPNETCORE_STATICWEBASSETS="/app/bin/Debug/net6.0/WebhookClient.staticwebassets.runtime.DT.json" b17ea361a84e sh -c ""dotnet"  --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  "/app/bin/Debug/net6.0/WebhookClient.dll" | tee /dev/console"
docker exec -i 9f2484a521ba sh -c ""dotnet"  --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  "/app/bin/Debug/net6.0/Ordering.BackgroundTasks.dll" | tee /dev/console"
docker exec -i c1e8ffd9566d sh -c ""dotnet"  --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  "/app/bin/Debug/net6.0/Mobile.Shopping.HttpAggregator.dll" | tee /dev/console"
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application '/app/bin/Debug/net6.0/Basket.API.dll' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application '/app/bin/Debug/net6.0/Ordering.API.dll' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
Could not execute because the application was not found or a compatible .NET SDK is not installed.

**Comment by nishanil** [comment]
@xieyiincuit Can you elaborate on the steps used to build? Are you using `docker-compose build` ?

**Comment by xieyiincuit** [comment]
@nishanil 

I can't use `docker-compose build` to make it right, I think is my network problem, I always get errors like this：
![image](https://user-images.githubusercontent.com/57696015/150456269-f45f79f3-745b-42f4-8a24-f9afdccd4082.png)

So，I wanna use visual studio 2022 to do this.
The build steps is：
1. build solution -- successfully
2. Use Visual Studio Docker-Compose (start without debugging)
3. Output windows Show All Container is ready 
4. Luanching error
![image](https://user-images.githubusercontent.com/57696015/150457769-4d482b53-bf5a-4767-b18c-2a6f9c6c58c6.png)

Tools Info:
Visual Studio 2022 Version: 17.05
Docker Version: 20.10.11
Docker Desktop Version:  4.3.2 (72729)
Use the WSL 2 based engine : True

**Comment by nishanil** [comment]
@xieyiincuit Yeah, that looks like a CDN not reachable issue. If the containers are built successfully, after the page opens, navigate to the Web Status project first using host.docker.internal:5107 and make sure all apps are healthy before navigating to the app.

**Comment by erjain** [comment]
Hi @xieyiincuit, you can also follow the updated instructions on [wiki page](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#build-and-run-the-application-with-f5-or-ctrlf5) to build and run the application in Visual Studio with F5. I am closing this issue as of now, however, feel free to reopen it in case you are looking for more help.

**Comment by lewisc99** [comment]
@xieyiincuit  for me happend  the same error, was because the folder that contain the c# project was, c# and another folder the name was month 9, so i rename the c# folder to csharp and the month 9 to month9 and then a ran the project again and worked it.
