### ISSUE TITLE
Whole project with all APIs and web applications are working in docker but unable to debug the same

### ISSUE THREAD

**Issue by divyeshdesanisos** [dotnet/eShopOnContainers#1813]
I have installed latest SDKs, Visual Studio 2022 and Docker Desktop.

Here are some details, might help you. 
Following are working:
CateLogApi
OrderApi
BAsketApi

Following are NOT working:
IdentilyApi
 - Error: System.ArgumentException: The path must be absolute. (Parameter 'root')
WebMVC
 - Error: System.ArgumentException: The path must be absolute. (Parameter 'root')
WebSPA
 - Error: System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.
WebStatus
 - System.ArgumentException: The path must be absolute. (Parameter 'root')

**Comment by addinfinity** [comment]
Facing same issue. MVC, SPA & IdentityApi not working.

**Comment by erjain** [comment]
Thanks for reporting the issue. If you are trying to run the application via Visual Studio 2022, test the application with the recommendation shared in the [link](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#build-and-run-the-application-with-f5-or-ctrlf5). Let us know if this works for you guys.

**Comment by erjain** [comment]
I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
