### ISSUE TITLE
Nginx Ingress controller 	0.20 - exited with 143

### ISSUE THREAD

**Issue by fruex** [dotnet/eShopOnContainers#1814]
I have installed the latest docker desktop:
![image](https://user-images.githubusercontent.com/16884614/147687088-0b240524-ce11-4399-93a0-c02bff4916e9.png)

Helm version: `version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}`
Branch: dev

I have set up a local configuration with k8s.
Steps to reproduce:
- Install Helm
- Install NGINX (`kubectl apply -f mandatory.yaml, kubectl apply -f local-cm.yaml, kubectl apply -f local-svc.yaml`)
- Install eShopOnContainers Using Helm from Public Images (`.\deploy-all.ps1 -imageTag linux-dev -useLocalk8s $true`)

```
kubectl get deployment
NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
eshop-apigwms                    1/1     1            1           10m
eshop-apigwws                    1/1     1            1           10m
eshop-basket-api                 1/1     1            1           11m
eshop-basket-data                1/1     1            1           11m
eshop-catalog-api                1/1     1            1           11m
eshop-identity-api               1/1     1            1           11m
eshop-keystore-data              1/1     1            1           11m
eshop-mobileshoppingagg          1/1     1            1           11m
eshop-nosql-data                 1/1     1            1           11m
eshop-ordering-api               1/1     1            1           11m
eshop-ordering-backgroundtasks   1/1     1            1           11m
eshop-ordering-signalrhub        1/1     1            1           11m
eshop-payment-api                1/1     1            1           11m
eshop-rabbitmq                   1/1     1            1           11m
eshop-sql-data                   1/1     1            1           11m
eshop-webhooks-api               1/1     1            1           10m
eshop-webhooks-web               1/1     1            1           10m
eshop-webmvc                     1/1     1            1           11m
eshop-webshoppingagg             1/1     1            1           11m
eshop-webspa                     1/1     1            1           11m
eshop-webstatus                  1/1     1            1           11m
```

```
kubectl get ing
NAME                       CLASS    HOSTS       ADDRESS   PORTS   AGE
eshop-apigwms              <none>   localhost             80      11m
eshop-apigwws              <none>   localhost             80      11m
eshop-identity-api         <none>   localhost             80      11m
eshop-identity-api-local   <none>   *                     80      11m
eshop-webhooks-api         <none>   localhost             80      11m
eshop-webhooks-web         <none>   localhost             80      11m
eshop-webmvc               <none>   localhost             80      11m
eshop-webmvc-local         <none>   *                     80      11m
eshop-webspa               <none>   localhost             80      11m
eshop-webstatus            <none>   localhost             80      11m
```
At this point, ADDRESS should be assigned but it's not.

I cannot reach apps after a while (9 minutes). Look like NGINX is stopped.
![image](https://user-images.githubusercontent.com/16884614/147687435-0be03c16-80d1-4b07-8fd5-8bb6bd84dab3.png)

The error is `Failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.extensions)`

```
E1229 16:54:27.686137       8 reflector.go:205] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:172: Failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.extensions)

I1229 16:54:28.317013       8 main.go:163] Received SIGTERM, shutting down

I1229 16:54:28.317061       8 nginx.go:341] Shutting down controller queues

I1229 16:54:28.317083       8 nginx.go:349] Stopping NGINX process

E1229 16:54:28.317192       8 store.go:176] Timed out waiting for caches to sync

I1229 16:54:28.317311       8 nginx.go:277] Starting NGINX process

I1229 16:54:28.317311       8 main.go:167] Error during shutdown: signal: terminated

I1229 16:54:28.317332       8 main.go:171] Handled quit, awaiting Pod deletion
```

**Comment by erjain** [comment]
Hi @fruex, we have identified the issue and updated the [Install NGINX Ingress Controller](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes#install-nginx-ingress-controller) section of [Deploy-to-Local-Kubernetes](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes) wiki page. Please try with the updated instruction for installing NGINX Ingress Controller which is as follows:

Run the following command:
`kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.1/deploy/static/provider/cloud/deploy.yaml`

Navigate to the folder deploy\k8s\nginx-ingress and run the following command:
`kubectl apply -f .\local-cm.yaml`

I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
