### ISSUE TITLE
Connection between Catalog GRPC server and Catalog GRPC client

### ISSUE THREAD

**Issue by menuconz** [dotnet/eShopOnContainers#1816]
How a connection is established between client(webshoppingagg --> CatalogSercice) and server(Services/Catalog/CatalogSercices)

Is this code in Startup.cs of webshoppingagg responsible to create a connection between client(webshoppingagg --> CatalogSercice) and server(Services/Catalog/CatalogSercices)?

 services.AddGrpcClient<Catalog.CatalogClient>((services, options) =>
 {
            var catalogApi = services.GetRequiredService<IOptions<UrlsConfig>>().Value.GrpcCatalog;
            options.Address = new Uri(catalogApi);
  })

**Comment by Jeevananthan-23** [comment]
Hi @menuconz, So your question is how the connection is established refer https://github.com/dotnet-architecture/eShopOnContainers/blob/4596d7aa99f841206e486e910d20b525cd48daf2/src/ApiGateways/Web.Bff.Shopping/aggregator/Web.Shopping.HttpAggregator.csproj#L39
And here as you mentioned in `Startup. cs` it acts as a `GRPC client factor` similar to `HTTP client Factor`

**Comment by erjain** [comment]
HI @menuconz, thanks for sharing your query. Thanks, @Jeevananthan-23 for answering the query. I am closing this issue now, however, feel free to continue the conversation here.
