### ISSUE TITLE
How to get this working in Visual Studio 2022

### ISSUE THREAD

**Issue by liamfoneill** [dotnet/eShopOnContainers#1821]
In order to get this to work properly in Visual Studio 2022, in addition to following the instructions in the Wiki, I also needed to change the run configuration from the default of 'Debug' to 'Release'.

Running it in Debug mode seems to cause some error about SPA Middleware not being able to find index.html.

Please update the Wiki.

**Comment by ChinguunU** [comment]
Having the same issue

**Comment by nishanil** [comment]
Thanks for reporting this. We are investigating this issue. From the initial look, it might be related to this one: https://github.com/dotnet/aspnetcore/issues/5223#issuecomment-977677128

**Comment by nishanil** [comment]
@erjain Hey! I have tested what @liamfoneill recommends and it works well. Can you update the Wiki to set the run configuration to `Release` for WebSpa please ? 
Thank  You @liamfoneill for the suggestion !!

**Comment by erjain** [comment]
Thanks @nishanil for confirming the suggestion from @liamfoneill .
Also if we want to run the application in debug mode using Visual Studio 2022, we can follow the below steps (also updated in [wiki](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#optional---to-run-webspa-project-via-visual-studio-2022-in-debug-mode)):
1. Update the Dockerfile in WebSPA project(src/Web/WebSPA/Dockerfile) to insert below instructions after WORKDIR /app

RUN apt-get update
RUN apt-get -y install curl gnupg
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get -y install nodejs
RUN npm install
RUN npm -v

2. Update the value for webspa.environment in docker-compose.override.yml as follows:
    ASPNETCORE_ENVIRONMENT=Development

**Comment by erjain** [comment]
I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.

**Comment by wanaxe** [comment]
Beside the above mentioned, I have to make below changes, to avoid `RUN npm install` error.

-  `RUN npm install -g npm@9.5.1` to `RUN npm install -g npm@9.6.6`
-  `RUN npm install` to `RUN npm install  --legacy-peer-deps`
