### ISSUE TITLE
Hot Reloading

### ISSUE THREAD

**Issue by ChinguunU** [dotnet/eShopOnContainers#1825]
Hi i am quite new to this and i have been trying to achieve hot reloading with the angular application. Is this feature available in the eShopOnContainers as i havent been able to do this via visual studio 2022. Or do we have set it up ourselves? If so could you please direct me to certain direction. Thank you.

**Comment by erjain** [comment]
Hi @ChinguunU,  After running your application in debug mode with F5, you can configure Hot Reload by selecting **Settings** from the **Hot Reload** drop-down button. Or please visit this link: https://docs.microsoft.com/en-us/visualstudio/debugger/hot-reload?view=vs-2022 for detailed knowledge on how to enable hot reloading via visual studio 2022. I am closing this issue, I hope this will help you or you can reopen it in case of further queries.
