### ISSUE TITLE
[Question] How can i debug specific microservice? 

### ISSUE THREAD

**Issue by chunk1ty** [dotnet/eShopOnContainers#1836]
I would like to debug specific microservice while rest of them run in docker. 
For instance I want to debug Catalog API. I stopped the cointaner then I changed CatalogAPI ports but for some reasons it did not worked.
![image](https://user-images.githubusercontent.com/6850746/151717659-66a9d8be-8adf-417c-a8c4-ee82cda7cb09.png)

Any ideas what am i missing?

Cheers!

**Comment by daniboi112** [comment]
try as per guideline here:

https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#optional---use-visual-studio

![image](https://user-images.githubusercontent.com/3529594/151747919-7a403af1-45a3-4406-833b-f98fcb525998.png)

I get this when I debug "docker-compose" project, why? anybody can help?

![image](https://user-images.githubusercontent.com/3529594/151747960-2268cf8d-2b4a-4c01-94a1-a3b81c2f7c51.png)

I am using VS 2022 preview for mac to get C#10 and Net6 goodies. [dev branch of eShopOnContainers]

Docker containers running

![image](https://user-images.githubusercontent.com/3529594/151748464-ded8f76a-c851-4757-ba22-c3f4f56250bb.png)

**Comment by andriyankrastev-finovation** [comment]
Hi, @daniboi112,
Thanks for the comment. I already tried that and yes it works but this is not what i want. Setting docker-compose as a start-up project is going to run and build all containers and thats a heavy operation which I would like to avoid. In most cases you are going to be focus only on one microservice and this is actually what i am looking for. I want all of the servces to run in background and if I want to debug some of them to turn it off from Docker for Windows (or VS code) and then to start that particular service from VS.

**Comment by chunk1ty** [comment]
Hi, @daniboi112 ,
Thanks for the comment. I already tried that and yes it works but this is not what i want. Setting docker-compose as a start-up project is going to run and build all containers and thats a heavy operation which I would like to avoid. In most cases you are going to be focus only on one microservice and this is actually what i am looking for. I want all of the servces to run in background and if I want to debug some of them to turn it off from Docker for Windows (or VS code) and then to start that particular service from VS.

**Comment by erjain** [comment]
Hi @chunk1ty, you can debug specific microservice by using `docker-compose up <imagename>`, e.g. if you want to run catalog api only, then you will run `docker-compose up catalog-api`, similarly for any other API. 
Then in visual studio open that particular microservice and attach the process, this way you can debug any microservice in the visual studio without running all containers which you are trying to avoid. 
I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
