### ISSUE TITLE
Where are Web Gateway Ocelot configurations files located?

### ISSUE THREAD

**Issue by dogaanismail** [dotnet/eShopOnContainers#1838]
I would like investigate Ocelot gateway configurations for web services, but I could not find them where they are located.

I have just found a configuration file for **Mobile Gateway**, but I could find it for Web.

src\ApiGateways\Mobile.Bff.Shopping\apigw\configuration.json

**Comment by nishanil** [comment]
Hey @dogaanismail We don't use Ocelot anymore. We are using Envoy proxy for the redirections. The `config` is here: https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/ApiGateways/Envoy/config/webshopping/envoy.yaml

**Comment by erjain** [comment]
Hi @dogaanismail,
I am closing this issue, however, feel free to reopen it if you are looking for more help.
