### ISSUE TITLE
How can I create a Jenkins file?

### ISSUE THREAD

**Issue by dogaanismail** [dotnet/eShopOnContainers#1839]
I am beginner for Devops and Continuous Integration process. I would like to deploy the project using Jenkins and to do this I should create a Jenkins file. How can I start the process?

**Comment by nishanil** [comment]
@dogaanismail  I am not sure about Jenkins. However, if you want to try the GitHub Actions, we wrote and entire course on it here: https://docs.microsoft.com/en-us/learn/modules/microservices-devops-aspnet-core/

**Comment by erjain** [comment]
Hi @dogaanismail, 
I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
