### ISSUE TITLE
[Question] Identity as a microservice (behind api gateway)

### ISSUE THREAD

**Issue by Simkiw** [dotnet/eShopOnContainers#1841]
Hello,

You've been told this a lot, but it's the least I can start with ... great work and I will soon or later dive into the e-book which I remind: [microservices and best practices](https://dotnet.microsoft.com/download/thank-you/microservices-architecture-ebook)

As I'm more focused on the gateway right now, and I came across this part of the doc: [api gateway implementation](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot#authentication-and-authorization-in-ocelot-api-gateways)
And I still can't really understand when I might want to use my identity provider as a microservice.

I quote _"That choice would be fair in a more **complex** microservice based architecture with multiple cross-cutting concerns microservices. Since there's **only one cross-cutting concern** in eShopOnContainers, it was decided to just handle the security service out of the API Gateway realm, for simplicity's sake."_

And I'm thinking:
- What do you mean by _"only one cross-cutting concern"_ (authentication?)
- I've read cross-cutting concern could be related to authentication, logging, retry, stuff like that, but I still find it hard to understand the concept of cross-cutting. Does it mean anything transverse through the whole app lifecycle? Like _services_ which are going to be common to all modules/microservices?
- And how can I understand _complexity_ in this context? (Like, if I have many microservices, then it's advised to have Identity provider behind? And if it's the case ... why? :) )

Those are my thoughts but I feel like I'm still missing something to fully understand the reasoning.
And sorry if questions are either direct or concept-related, I'm just trying to be on the same page.

Thank you very much

**Comment by erjain** [comment]
Hi @Simkiw, Thanks for sharing your concern. This application is a demonstration to implement the complex microservice-based architecture, including multiple microservices like catalog, basket, ordering, identity, etc. But here just to keep it simple in the sample we have made identity microservices, to be available publicly, the Identity/Auth service is left out of the API Gateways, in production scenarios you will have an API Gateway for Auth also, this(Authentication) is the "_only cross-cutting concern_" in eShopOnContainers we are talking about.

**Comment by erjain** [comment]
I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.

**Comment by Simkiw** [comment]
Hi @erjain, thank you for your response, which triggered an underlying question :) (and I can't seem to find some relevant information, I've tried)
It might be just a detail plus I think I got the idea: just "for simplicity", but still ... it's always interesting to have a perspective from a much more experienced person.

In production in this case, you might have an api gateway for authentication as well. And i am thinking, what would be the main benefits compared to having auth outside of api gw scope? Like ... when should I really really consider one design over another?

I've done some research and came up with the following:
Auth behind gateway is useful when

- you want to protect your identity provider (where it's being hosted, since everyone is seeing the gw only)
- you want to make it more flexible: you would only need to change your gateway config, since all services would be pointing to the gateway of authentication and not the IdP itself
- but ... what if I'm using an IdP such as Identity server, which does federation? In this case, it doesn't feel necessary to hide the IdP since it's supposed to be secure (facebook, google, IS4 itself), this is where I get confused.

On the other hand, auth outside of gw, security would be set up easily and that's all i could came up with in terms of advantages.

If you could enlighten/confirme/correct me on the topic, or if you have some resources I could check out, I would appreciate.

Thank you
