### ISSUE TITLE
Eshop page shows Error requesting catalog products, please try later on 

### ISSUE THREAD

**Issue by jiheechoi01** [dotnet/eShopOnContainers#1845]
I'm having issues with my eshopOnContainers page. Please see the errors below: 
All the pods are successfully running, however when I go to the http://eshop.3d826a4386af433db850.eastus.aksapp.io/
**1)**  I see the "Error requesting catalog products" for both public and login 
![catalog error](https://user-images.githubusercontent.com/82827230/152607058-5e2c3a38-742e-4dad-8a8e-6148f6af69ea.jpg)

**2)** http://eshop.3d826a4386af433db850.eastus.aksapp.io/catalog returns unhandled exception
![catalog erro 2](https://user-images.githubusercontent.com/82827230/152607128-bb316862-63a1-4902-a3d3-29c33366c942.jpg)

**3)** When I go to webmvc page http://eshop.3d826a4386af433db850.eastus.aksapp.io/webmvc, everything loads up successfully and I can login, add items to basket, and complete an order. However all the images of each item doesn't load up. 
![image](https://user-images.githubusercontent.com/82827230/152607260-1ca27105-ae8c-493f-9a5d-19bf1fdc4c26.png)

Would someone be able to assist in these issues?

**Comment by erjain** [comment]
Hi @jiheechoi01 ,  thank you for reaching out and reporting the issue. We have already identified the issue last week and working on it to resolve it asap. We will update you on this thread once after resolving this bug.

**Comment by Dintwe** [comment]
of course running everything on my dev machine, I have switched the gateway urls to use my local IP, maybe something to consider to see if the requests are going through.

<img width="998" alt="image" src="https://user-images.githubusercontent.com/56117627/153555837-cf29a5f1-3c0b-46de-acb8-92a7f06c0587.png">

it pulls the catalog, but not on first attempt, I had to F5 more than once though...strange.

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/56117627/153552633-e3f7f511-612e-4004-9b1e-cca9959a53f8.png">

and mvc web loads as well

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/56117627/153555569-580c545c-afb2-4822-8cc2-be2ad6918d7c.png">

**Comment by Dintwe** [comment]
...and also for mobile had to make some edits here:

<img width="578" alt="image" src="https://user-images.githubusercontent.com/56117627/153559287-8d910216-23dc-49ed-90c3-e24da989d55b.png">



<img width="429" alt="image" src="https://user-images.githubusercontent.com/56117627/153558575-f42d1773-bc3f-4abc-a09d-2a8412cae6d2.png">

**Comment by Dintwe** [comment]
...and importantly edit .env file at \src to enable seeding by Identity.API in the IdentityDb to use local IP

<img width="798" alt="image" src="https://user-images.githubusercontent.com/56117627/153567398-75462023-7c7e-4e13-9243-885bb48e4809.png">

You will need to DROP the IdentityDb and rerun the 'docker-compose build' and 'docker-compose up' commands in \src path for new values to be seeded. In my case i am using docker.

after Db has been recreated, your local ip will reflect in tables like here;

<img width="735" alt="image" src="https://user-images.githubusercontent.com/56117627/153568762-fc42134c-e461-4d62-bb04-6c2d0e5c38bb.png">

<img width="680" alt="image" src="https://user-images.githubusercontent.com/56117627/153568948-88058679-d855-485f-a753-78aa5673f969.png">

**Comment by Dintwe** [comment]
...back to SPA

change '**applicationUrl**' to use local IP as well under '**WebSPA**' section in **profiles**

<img width="554" alt="image" src="https://user-images.githubusercontent.com/56117627/153715872-3e0684cd-ab53-47a2-9080-23b1bc395d4b.png">

also change to local IP here in **appsettings.json**

<img width="473" alt="image" src="https://user-images.githubusercontent.com/56117627/153716453-2656cd4d-0810-4c55-b0fb-eacdf0f5d1b6.png">

and finally change here back to original code

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/56117627/153716603-fc163966-4c34-4d1e-a25b-9776356c5962.png">

**Comment by erjain** [comment]
Hi @Dintwe, Thanks for sharing your findings.  Are you trying to run the application with docker only or have you deployed it to your local Kubernetes?

**Comment by erjain** [comment]
Hi @jiheechoi01, the issue has been resolved now, you can take a fresh pull from dev branch and deploy on AKS, it should work. There were issues while deploying the Webshopping API Gateway. I am closing this issue as of now. Please feel free to reopen if needed. Thank you.

**Comment by Dintwe** [comment]
Hi @erjain for now docker only, when I do get time again kubernetes is next, thank you @nishanil for the update.
