### ISSUE TITLE
Architecture Design

### ISSUE THREAD

**Issue by ragzkotalwar** [dotnet/eShopOnContainers#1855]
Can we get source file (Editable copy) or eShopOnContainer architecture diagram. This would really help
![eShopOnContainers-architecture](https://user-images.githubusercontent.com/15087046/153994645-479ce5c8-bee4-4bf9-99aa-2716ed96101b.png)
.

**Comment by nishanil** [comment]
You will be surprised to know that it was created in Powerpoint :) I have an old copy here:  https://1drv.ms/p/s!AupZwrZ-sEsggchgPe_1gZfHtr6edg?e=AXcxcT  You should be able to update to this one pretty easily.
I am also closing the issue. Feel free to keep the conversation going.

**Comment by ragzkotalwar** [comment]
> You will be surprised to know that it was created in Powerpoint :) I have an old copy here: https://1drv.ms/p/s!AupZwrZ-sEsggchgPe_1gZfHtr6edg?e=AXcxcT You should be able to update to this one pretty easily. I am also closing the issue. Feel free to keep the conversation going.

Thanks a ton :)
