### ISSUE TITLE
Startup.cs(37,44): error CS1513: } expected [/usr/csuser/clouddrive/aspnet-learn/src/src/Services/Coupon/Coupon.API/Coupon.API.csproj]

### ISSUE THREAD

**Issue by LucaOtto** [dotnet/eShopOnContainers#1867]
Hello,

I'm receiving this error message when running the command: dotnet build src/Services/Coupon/Coupon.API/ found in https://docs.microsoft.com/en-us/learn/modules/microservices-aspnet-core/6-add-coupon-service

![image](https://user-images.githubusercontent.com/42404744/155721213-093c5706-a144-48c8-bba3-7d4894975282.png)

More errors are also appearing with this command ./deploy/k8s/implementation-script.sh 

![image](https://user-images.githubusercontent.com/42404744/155721507-3d6619a1-d0fe-43e1-921f-7fb8ab540315.png)

Thanks

**Comment by erjain** [comment]
Hi @LucaOtto, the module which you are exercising belongs to a different [repository](https://github.com/MicrosoftDocs/mslearn-aspnet-core/tree/live). Firstly to correctly install the application you can follow the instructions on page Exercise - [Set up the environment](https://docs.microsoft.com/en-us/learn/modules/microservices-aspnet-core/2-deploy-application), 
where you can open Azure Cloud Shell in your browser. Select a directory with access to the Azure subscription in which you want to create resources. Select Bash from the environment dropdown list in the upper left. Copy & run the below deployment script, in the command shell:

`. <(wget -q -O - https://aka.ms/microservices-aspnet-core-setup)`

The preceding command retrieves and runs a setup script from a GitHub repository. The script completes the following steps:

Installs the required version of the .NET SDK.
Clones the eShopOnContainers app from a GitHub repository.
Provisions AKS and Azure Container Registry resources.
Launches the Cloud Shell editor to view the code.
Deploys the containers to a fully-managed Kubernetes service in Azure, known as AKS.
Displays connection information upon completion.

For more information please refer to link [Set up the environment](https://docs.microsoft.com/en-us/learn/modules/microservices-aspnet-core/2-deploy-application), 

Once after setting up the environment you can add the coupon service and follow the instructions given on page [Exercise - Add the coupon service](https://docs.microsoft.com/en-us/learn/modules/microservices-aspnet-core/6-add-coupon-service). Let me know if this helps.

**Comment by LucaOtto** [comment]
Hello @erjain .Sorry for the confusion. I've done all this already. The error messages came up AFTER deploying all of the above.

**Comment by erjain** [comment]
No worries @LucaOtto, After observing your shared screenshots, it seems, there is a miss while updating your code from the exercise, it is missing `}`. Can you again check that you have correctly implemented the highlighted code from the exercise, or it is not breaking any syntax or runtime error? Let me know in case you still face any issues.

**Comment by erjain** [comment]
I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
