### ISSUE TITLE
Question: Variable name pattern

### ISSUE THREAD

**Issue by guiamar92** [dotnet/eShopOnContainers#1873]
I've been following the EShopOnContainers project to see how things are done by you who contribute to this project and I noticed a small difference that left me with a doubt.

In the WebApplication WebMVC project, we have the CartController with the private readonly ICatalogService _catalogSvc property declared, and I have verified that they use the "Srv" to indicate a service.

![image](https://user-images.githubusercontent.com/40678954/157931530-7c1af54e-ab9a-410b-bab2-4c587acb8c99.png)

But in the WebApplication Web.Shopping.HttpAggregator project, in the BasketController class we have the property declared like this: private readonly IBasketService _basket

![image](https://user-images.githubusercontent.com/40678954/157931431-13c9d529-64e1-456c-ad67-1da31e8107e5.png)

What would be the best way to use it?

Thank you!

**Comment by erjain** [comment]
Hi @guiamar92, Thanks for reaching out. We can use any one of the naming conventions, whether to use Svc or Srv. For information on naming guidelines, you can also go through the link https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members. Let me know if you have any further queries.
