### ISSUE TITLE
@angular-devkit/build-angular:dev-server is not found while npm install.

### ISSUE THREAD

**Issue by adit-github** [dotnet/eShopOnContainers#1877]
I get the below issue while running the webspa project. Is it because the angular version was upgraded?

An unhandled exception occurred while processing the request.
AggregateException: One or more errors occurred. (The npm script 'start' exited without indicating that the Angular CLI was listening for requests. The error output was: Node packages may not be installed. Try installing with 'npm install'.

Could not find the '@angular-devkit/build-angular:dev-server' builder's node package.

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! eshopaspnetnetcoredockerspa@0.0.0 start: `ng serve "--port" "33377"`

npm ERR! Exit status 1

npm ERR!

npm ERR! Failed at the eshopaspnetnetcoredockerspa@0.0.0 start script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:

npm ERR! /root/.npm/_logs/2022-03-19T11_10_32_763Z-debug.log

)

Here is the docker file settings.

WORKDIR /app
RUN apt-get update
RUN apt-get -y install curl gnupg
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get -y install nodejs
RUN npm install
RUN npm i -g @angular/cli
RUN npm install --save-dev @angular-devkit/build-angular
RUN npm -v
EXPOSE 80

**Comment by erjain** [comment]
Hi @adit-github,  Thanks for reporting this issue, we will check and update you.

**Comment by erjain** [comment]
Hi @adit-github, Please try by taking a fresh pull and following the instructions given on [windows set up](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup) wiki pages sections as below:

1. https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#build-and-deploy-eshoponcontainers. 
2. https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#optional---use-visual-studio

There is minimal modification required in any of the files. In case you still face any issues after going through the above links, then please go to the issue [section](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#in-case-you-find-issues-with-webspa-project-while-browsing-the-app-using-httpurl5104-after-hitting-f5-to-debug-in-visual-studio-then-follow-the-below-instructions). Please feel free to post here in case of any further issues.

**Comment by erjain** [comment]
I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
