### ISSUE TITLE
Production Ready

### ISSUE THREAD

**Issue by sinanopcommerce** [dotnet/eShopOnContainers#1883]
Is this repo is production-ready? Can e-commerce start with this repo? Or it is for learning materials of micro-service.

**Comment by adriver-kwiboo** [comment]
Check the readme 
https://github.com/dotnet-architecture/eShopOnContainers/blob/981507dccbfa94d68806241cd542ff38f56950b8/CONTRIBUTING.md#disclaimer---this-is-not-a-production-ready-template-for-microservices

This is not production ready

**Comment by erjain** [comment]
Hi @sinanopcommerce, This is just a demonstration of how to implement microservices, it is not production-ready. For illustrations of the implementation of an e-commerce application, you can visit the learning module: https://docs.microsoft.com/en-us/learn/paths/create-microservices-with-dotnet. I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
