### ISSUE TITLE
Why direct query from API project?

### ISSUE THREAD

**Issue by amiradeli** [dotnet/eShopOnContainers#1889]
I am not getting why there are db queries directly from Ordering.API project? And also why you are using raw sql and dynamic types to convert it into model instead of using an ORM?

**Comment by MithrilMan** [comment]
I think you should read this
https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/cqrs-microservice-reads

**Comment by amiradeli** [comment]
Thanks. Now it is clear to me. 
As I expected, the article says that using DTOs is much better than using dynamic types in real projects.
