### ISSUE TITLE
how do we access sql-data service after Deployment To AKS 

### ISSUE THREAD

**Issue by ozcano1** [dotnet/eShopOnContainers#1891]
Hello
I successfully deployed eShopOnContainers to AKS . I want to know how do we see inside the databases (tables etc.) such as we do with SQL Management Studio?
I tried following STATEMENT, it started listening, bu I cannot connect address http://127.0.0.1:8080, since I received ERROR at the bottom.  
Regards

STATEMENT:
"
kubectl port-forward $(kubectl get pods --namespace default -l "app=sql-data,release=eshop-sql-data" -o jsonpath="{.items[0].metadata.name}") 8080:80
"

ERROR:
"
E0408 14:18:39.304877   21696 portforward.go:400] an error occurred forwarding 8080 -> 80: error forwarding port 80 to pod ce38823a2e33c429963ad3569e9bd7d75c686c14a9599d666449e67a92b8a0d6, uid : failed to execute portforward in network namespace "/var/run/netns/cni-21df4e0f-edfe-ca64-2046-55e6e4f41303": failed to dial 80: dial tcp4 127.0.0.1:80: connect: connection refused
E0408 14:18:39.741193   21696 portforward.go:340] error creating error stream for port 8080 -> 80: Timeout occured
"

**Comment by erjain** [comment]
Hi @ozcano1, thanks for posting your query, since this is a question but not an issue, I am closing this as of now. However, you can continue the conversation here. We will get back to you with an answer to your original question.
