### ISSUE TITLE
question of curiousity

### ISSUE THREAD

**Issue by Techrese** [dotnet/eShopOnContainers#1893]
I more rather have a question than an issue

Why in this application the choice of repository pattern and cqrs?

I have read on the microsoft docs page that cqrs is rather a bad practice for crud apps?

And as A last one, the schematic in which application is it made?

**Comment by erjain** [comment]
Hi @Techrese, thanks for contacting us. You can go refer to the documentation given in section [Tackle Business Complexity in a Microservice with DDD and CQRS Patterns](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/), you can refer to the complete rest of the section for the clarification. 
I am closing it, however, feel free to continue the conversation or reopen it if you are looking for more help.
