### ISSUE TITLE
Not an issue a question

### ISSUE THREAD

**Issue by ora8** [dotnet/eShopOnContainers#1895]
Hallo I get this error. What have I to do?

Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2307	(TS) Cannot find module '@angular/common' or its corresponding type declarations.	C:\MicroService\eShopOnContainers-dev\src\Web\WebSPA\Client\tsconfig.json	C:\MicroService\eShopOnContainers-dev\src\Web\WebSPA\Client\src\modules\catalog\catalog.module.ts	3	Active

Thanks for the help.
Best Regards
Urs

**Comment by erjain** [comment]
Hi @ora8, thank you for reaching out.

Could you please try to clean the `npm` cache by using the below command ?

``` powershell
npm cache clean --force
OR 
npm cache verify
```

And then cloned the `dev` branch again if possible to a new directory location and try to build  ?

But before that if you want to clean up the existing containers and docker images to start from scratch you could follow below steps.

- To do clean up 

```powershell

docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
docker volume rm $(docker volume ls -q)

```

> !IMPORTANT: Above commands will clean up all running containers and it's data in your MacOS/Workstation. So you want to be careful on that.

- To run the app 

```powershell
docker-compose build
docker-compose up sqldata
```
once it's ready to accept the connection then you can bring up the other container by using the following command from a seperate terminal

```powershell
docker-compose up
```

Hope this helps !

**Comment by erjain** [comment]
I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
