### ISSUE TITLE
Duende IdentityServer or Microsoft identity platform (AD B2C) instead of IdentityServer4

### ISSUE THREAD

**Issue by Ogglas** [dotnet/eShopOnContainers#1897]
Is there any plan to update `Identity.API` to use `Duende IdentityServer` instead of `IdentityServer4`? 

Given that IdentityServer4 will only be maintained with security updates until November 2022 and the organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022).

https://identityserver4.readthedocs.io/en/latest/

https://github.com/IdentityServer/IdentityServer4

Is there any plan to show an alternative solution without IdentityServer and instead use Microsoft identity platform (Azure Active Directory or Azure AD B2C)?

**Comment by dalvarezabal** [comment]
Yes, it will be great to see how are you going to handle this.

**Comment by rekosko** [comment]
BUMP :)

**Comment by erjain** [comment]
I have picked this.

**Comment by CESARDELATORRE** [comment]
A good option is also KEYCLOAK: https://www.keycloak.org/

But since the original implementation was with IdentityServer4, moving to Duende, which is kind of IS4 vNext should be more straightforward..

**Comment by erjain** [comment]
As @CESARDELATORRE mentioned here the original implementation was IS4 so the move to Duende was the easiest migration, however, read through the [documentation](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-7.0&tabs=visual-studio) on the many options available for developers. Thank you so much. I am closing this issue for now, please feel free to post here in case you have any more questions.

**Comment by derKosi** [comment]
Don’t you need a valid license for Duende Software? If they aren’t enforcing their rights with you, wouldn’t it be unfair to enforce them with smaller companies? How did you resolve this issue?

Happy sailings.

Chad says it's not necessary to enforce this, yet it smells funny, especially with a goto architecture solution like eShops.

Not enforcing a copyright or license against one company does not necessarily mean that the right is lost against other companies. However, it is important for a company to consistently enforce their rights to maintain their validity. It is always advisable to consult with a legal professional for specific cases. Is there anything else you would like to know? 😊
