### ISSUE TITLE
How can I contribute? Unable to fork.

### ISSUE THREAD

**Issue by adriver-kwiboo** [dotnet/eShopOnContainers#1899]
I would like to contribute to this repo, however I note from the readme: https://github.com/dotnet-architecture/eShopOnContainers/blob/3af71331570358091794154d372718bc10c1a6b7/CONTRIBUTING.md I need to fork the solution.
Unfortunately when I try and fork it, I get:
No more forks can be created.

**Comment by amiradeli** [comment]
There is probably something wrong with your account since I just forked the repo without any problem.

**Comment by adriver-kwiboo** [comment]
Stupid me! I had already forked it. 
Thanks for your help.
