### ISSUE TITLE
How to use Domain Service in Ordering API?

### ISSUE THREAD

**Issue by bidianqing** [dotnet/eShopOnContainers#1902]
I'm DDD newbie, How to use Domain Service in Ordering API?

**Comment by erjain** [comment]
Hi @bidianqing, thanks for posting your query. You can go through the documentation for [designing a DDD-oriented microservices](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/ddd-oriented-microservice?msclkid=0cef2c1bc6df11ec81feb4e4f89298d6). Hope this helps. I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
