### ISSUE TITLE
Question on migration IntegrationEventLogContext for Ordering.API

### ISSUE THREAD

**Issue by dogaanismail** [dotnet/eShopOnContainers#1905]
Hello,

I have been trying to migrate IntegrationEventLogContext, but it is getting an error which says "Could not execute because the specified command or file was not found."

How can I migrate IntegrationEventLogContext?

`
dotnet ef migrations add Initial --context Microsoft.eCommerceOnContainers.BuildingBlocks.IntegrationEventLogEF.IntegrationEventLogContext -o Ordering.API/Infrastructure/IntegrationEventMigrations
`

![Screenshot_61](https://user-images.githubusercontent.com/30376425/166490467-47df7a69-cf24-4556-82ac-9a9d394fcccb.png)

**Comment by onurkanbakirci** [comment]
Hi @dogaanismail . You try to execute migration commands in incorrect terminal. Package Manager Console can't understand your instructions. You should run these commands in normal terminal not Package Manager Console.

**Tips:**
You can shortly use 
`dotnet ef migrations add Initial -c  IntegrationEventLogContext -o Ordering.API/Infrastructure/IntegrationEventMigrations`

**Comment by erjain** [comment]
Thanks @onurkanbakirci, for sharing the tips.
@dogaanismail, I am closing the issue, however, feel free to continue the conversation in case of any further queries.
