### ISSUE TITLE
Error requesting catalog products, please try later on 

### ISSUE THREAD

**Issue by ramganesh19** [dotnet/eShopOnContainers#1915]
Cloned the repo and built locally on my windows laptops in git bash prompt with latest docker desktop installed

WebSPA (Error requesting catalog products)
![image](https://user-images.githubusercontent.com/12521269/168457303-efe36743-2da8-497d-b760-4cc10c06afa5.png)

WebMVC (Dont see the images)
![image](https://user-images.githubusercontent.com/12521269/168457351-4ff4aa4c-77c4-4a78-9712-c2221f722af3.png)

Appreciate help in resolving it.

**Comment by ramganesh19** [comment]
Health check is all good
![image](https://user-images.githubusercontent.com/12521269/168457389-4a02e50b-1f3c-4575-9799-3f7a881fa21b.png)

**Comment by erjain** [comment]
Hi @ramganesh19, I have tested it locally at my end and the application is working fine, Sometimes an error during startup can disturb the application deployment and entries in the databases. Could you please clean up old docker images and build the docker images again? - To run the app 
- Go to the `/src/` directory

```text
docker-compose up sqldata
```
Once it's ready to accept the new connection, then you can bring up the other container by using the following command from a separate terminal window.

```text
docker-compose up
```

![image](https://user-images.githubusercontent.com/87998741/168604296-9aa8960c-57fb-4c64-beef-195c76b1ef10.png)

**Comment by erjain** [comment]
I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
