### ISSUE TITLE
build issue in windows 11 - executor failed running [/bin/sh -c npm install]: exit code: 127

### ISSUE THREAD

**Issue by ramganesh19** [dotnet/eShopOnContainers#1917]
I keep running into below build issues and not able to make progress
C:\Users\ramg1\source\repos\eShopOnContainers\src>docker-compose build
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ESHOP_SERVICE_BUS_USERNAME\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ESHOP_SERVICE_BUS_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"INSTRUMENTATION_KEY\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ORCHESTRATOR_TYPE\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"INSTRUMENTATION_KEY\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ORCHESTRATOR_TYPE\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"INSTRUMENTATION_KEY\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ORCHESTRATOR_TYPE\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ESHOP_SERVICE_BUS_USERNAME\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ESHOP_SERVICE_BUS_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ESHOP_SERVICE_BUS_USERNAME\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ESHOP_SERVICE_BUS_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ESHOP_AZURE_STORAGE_CATALOG_NAME\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ESHOP_AZURE_STORAGE_CATALOG_KEY\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"INSTRUMENTATION_KEY\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ORCHESTRATOR_TYPE\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ESHOP_SERVICE_BUS_USERNAME\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ESHOP_SERVICE_BUS_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"INSTRUMENTATION_KEY\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ORCHESTRATOR_TYPE\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ESHOP_SERVICE_BUS_USERNAME\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ESHOP_SERVICE_BUS_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"INSTRUMENTATION_KEY\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ORCHESTRATOR_TYPE\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ESHOP_SERVICE_BUS_USERNAME\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ESHOP_SERVICE_BUS_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"INSTRUMENTATION_KEY\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ORCHESTRATOR_TYPE\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"INSTRUMENTATION_KEY\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ORCHESTRATOR_TYPE\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ESHOP_SERVICE_BUS_USERNAME\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ESHOP_SERVICE_BUS_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"INSTRUMENTATION_KEY\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ORCHESTRATOR_TYPE\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"INSTRUMENTATION_KEY\" variable is not set. Defaulting to a blank string."
time="2022-05-16T22:30:47-05:00" level=warning msg="The \"ORCHESTRATOR_TYPE\" variable is not set. Defaulting to a blank string."
[+] Building 2.4s (132/599)
 => [eshop/webstatus:linux-latest internal] load build definition from Dockerfile                                                                                                                             0.0s
 => => transferring dockerfile: 4.67kB                                                                                                                                                                        0.0s
 => [eshop/webhooks.client:linux-latest internal] load build definition from Dockerfile                                                                                                                       0.0s
 => => transferring dockerfile: 4.70kB                                                                                                                                                                        0.0s
 => [eshop/webshoppingagg:linux-latest internal] load build definition from Dockerfile                                                                                                                        0.0s
 => => transferring dockerfile: 4.72kB                                                                                                                                                                        0.0s
 => [eshop/payment.api:linux-latest internal] load build definition from Dockerfile                                                                                                                           0.0s
 => => transferring dockerfile: 4.70kB                                                                                                                                                                        0.0s
 => [eshop/catalog.api:linux-latest internal] load build definition from Dockerfile                                                                                                                           0.0s
 => => transferring dockerfile: 5.01kB                                                                                                                                                                        0.0s
 => [eshop/mobileshoppingagg:linux-latest internal] load build definition from Dockerfile                                                                                                                     0.0s
 => => transferring dockerfile: 4.73kB                                                                                                                                                                        0.0s
 => [eshop/webmvc:linux-latest internal] load build definition from Dockerfile                                                                                                                                0.0s
 => => transferring dockerfile: 4.67kB                                                                                                                                                                        0.0s
 => [eshop/identity.api:linux-latest internal] load build definition from Dockerfile                                                                                                                          0.0s
 => => transferring dockerfile: 32B                                                                                                                                                                           0.0s
 => [eshop/webspa:linux-latest internal] load build definition from Dockerfile                                                                                                                                0.0s
 => => transferring dockerfile: 5.26kB                                                                                                                                                                        0.0s
 => [eshop/basket.api:linux-latest internal] load build definition from Dockerfile                                                                                                                            0.0s
 => => transferring dockerfile: 4.85kB                                                                                                                                                                        0.0s
 => [eshop/webhooks.api:linux-latest internal] load build definition from Dockerfile                                                                                                                          0.1s
 => => transferring dockerfile: 4.70kB                                                                                                                                                                        0.0s
 => [eshop/ordering.api:linux-latest internal] load build definition from Dockerfile                                                                                                                          0.1s
 => => transferring dockerfile: 4.87kB                                                                                                                                                                        0.0s
 => [eshop/ordering.backgroundtasks:linux-latest internal] load build definition from Dockerfile                                                                                                              0.0s
 => => transferring dockerfile: 4.72kB                                                                                                                                                                        0.0s
 => [eshop/ordering.signalrhub:linux-latest internal] load build definition from Dockerfile                                                                                                                   0.1s
 => => transferring dockerfile: 32B                                                                                                                                                                           0.0s
 => [eshop/webstatus:linux-latest internal] load .dockerignore                                                                                                                                                0.0s
 => => transferring context: 35B                                                                                                                                                                              0.0s
 => [eshop/webhooks.client:linux-latest internal] load .dockerignore                                                                                                                                          0.0s
 => => transferring context: 35B                                                                                                                                                                              0.0s
 => [eshop/webshoppingagg:linux-latest internal] load .dockerignore                                                                                                                                           0.0s
 => => transferring context: 35B                                                                                                                                                                              0.0s
 => [eshop/payment.api:linux-latest internal] load .dockerignore                                                                                                                                              0.0s
 => => transferring context: 35B                                                                                                                                                                              0.0s
 => [eshop/catalog.api:linux-latest internal] load .dockerignore                                                                                                                                              0.0s
 => => transferring context: 35B                                                                                                                                                                              0.0s
 => [eshop/mobileshoppingagg:linux-latest internal] load .dockerignore                                                                                                                                        0.0s
 => => transferring context: 35B                                                                                                                                                                              0.0s
 => [eshop/webmvc:linux-latest internal] load .dockerignore                                                                                                                                                   0.0s
 => => transferring context: 35B                                                                                                                                                                              0.0s
 => [eshop/identity.api:linux-latest internal] load .dockerignore                                                                                                                                             0.0s
 => => transferring context: 35B                                                                                                                                                                              0.0s
 => [eshop/webspa:linux-latest internal] load .dockerignore                                                                                                                                                   0.0s
 => => transferring context: 35B                                                                                                                                                                              0.0s
 => [eshop/basket.api:linux-latest internal] load .dockerignore                                                                                                                                               0.0s
 => => transferring context: 35B                                                                                                                                                                              0.0s
 => [eshop/webhooks.api:linux-latest internal] load .dockerignore                                                                                                                                             0.0s
 => => transferring context: 35B                                                                                                                                                                              0.0s
 => [eshop/ordering.api:linux-latest internal] load .dockerignore                                                                                                                                             0.0s
 => => transferring context: 35B                                                                                                                                                                              0.0s
 => [eshop/ordering.backgroundtasks:linux-latest internal] load .dockerignore                                                                                                                                 0.0s
 => => transferring context: 35B                                                                                                                                                                              0.0s
 => [eshop/ordering.signalrhub:linux-latest internal] load .dockerignore                                                                                                                                      0.0s
 => => transferring context: 35B                                                                                                                                                                              0.0s
 => [eshop/ordering.api:linux-latest internal] load metadata for mcr.microsoft.com/dotnet/sdk:6.0                                                                                                             0.4s
 => [eshop/ordering.signalrhub:linux-latest internal] load metadata for mcr.microsoft.com/dotnet/aspnet:6.0                                                                                                   0.0s
 => [eshop/webspa:linux-latest base 1/2] FROM mcr.microsoft.com/dotnet/aspnet:6.0                                                                                                                             0.0s
 => [eshop/webstatus:linux-latest internal] load build context                                                                                                                                                0.3s
 => => transferring context: 106.16kB                                                                                                                                                                         0.2s
 => [eshop/webspa:linux-latest build  1/38] FROM mcr.microsoft.com/dotnet/sdk:6.0@sha256:461fb5b750d93aec249e70aa4e1ebf99f4acb50512ec295ff88658ae9c50cae7                                                     0.0s
 => [eshop/webhooks.client:linux-latest internal] load build context                                                                                                                                          0.2s
 => => transferring context: 106.16kB                                                                                                                                                                         0.2s
 => [eshop/webshoppingagg:linux-latest internal] load build context                                                                                                                                           0.3s
 => => transferring context: 106.16kB                                                                                                                                                                         0.2s
 => [eshop/payment.api:linux-latest internal] load build context                                                                                                                                              0.2s
 => => transferring context: 106.16kB                                                                                                                                                                         0.1s
 => [eshop/catalog.api:linux-latest internal] load build context                                                                                                                                              0.2s
 => => transferring context: 106.16kB                                                                                                                                                                         0.1s
 => [eshop/mobileshoppingagg:linux-latest internal] load build context                                                                                                                                        0.3s
 => => transferring context: 106.16kB                                                                                                                                                                         0.1s
 => [eshop/webmvc:linux-latest internal] load build context                                                                                                                                                   0.3s
 => => transferring context: 106.16kB                                                                                                                                                                         0.2s
 => [eshop/webspa:linux-latest internal] load metadata for docker.io/library/node:12.0                                                                                                                        0.6s
 => [eshop/basket.api:linux-latest internal] load build context                                                                                                                                               0.4s
 => => transferring context: 106.16kB                                                                                                                                                                         0.2s
 => CACHED [eshop/webhooks.client:linux-latest build  2/38] WORKDIR /src                                                                                                                                      0.0s
 => CACHED [eshop/webstatus:linux-latest build  3/38] COPY eShopOnContainers-ServicesAndWebApps.sln eShopOnContainers-ServicesAndWebApps.sln                                                                  0.0s
 => CACHED [eshop/webstatus:linux-latest build  4/38] COPY ApiGateways/Mobile.Bff.Shopping/aggregator/Mobile.Shopping.HttpAggregator.csproj ApiGateways/Mobile.Bff.Shopping/aggregator/Mobile.Shopping.HttpA  0.0s
 => CACHED [eshop/webstatus:linux-latest build  5/38] COPY ApiGateways/Web.Bff.Shopping/aggregator/Web.Shopping.HttpAggregator.csproj ApiGateways/Web.Bff.Shopping/aggregator/Web.Shopping.HttpAggregator.cs  0.0s
 => CACHED [eshop/webstatus:linux-latest build  6/38] COPY BuildingBlocks/Devspaces.Support/Devspaces.Support.csproj BuildingBlocks/Devspaces.Support/Devspaces.Support.csproj                                0.0s
 => CACHED [eshop/webstatus:linux-latest build  7/38] COPY BuildingBlocks/EventBus/EventBus/EventBus.csproj BuildingBlocks/EventBus/EventBus/EventBus.csproj                                                  0.0s
 => CACHED [eshop/webstatus:linux-latest build  8/38] COPY BuildingBlocks/EventBus/EventBus.Tests/EventBus.Tests.csproj BuildingBlocks/EventBus/EventBus.Tests/EventBus.Tests.csproj                          0.0s
 => CACHED [eshop/webstatus:linux-latest build  9/38] COPY BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.csproj BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.csproj                  0.0s
 => CACHED [eshop/webstatus:linux-latest build 10/38] COPY BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.csproj BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.csproj          0.0s
 => CACHED [eshop/webstatus:linux-latest build 11/38] COPY BuildingBlocks/EventBus/IntegrationEventLogEF/IntegrationEventLogEF.csproj BuildingBlocks/EventBus/IntegrationEventLogEF/IntegrationEventLogEF.cs  0.0s
 => CACHED [eshop/webstatus:linux-latest build 12/38] COPY BuildingBlocks/WebHostCustomization/WebHost.Customization/WebHost.Customization.csproj BuildingBlocks/WebHostCustomization/WebHost.Customization/  0.0s
 => CACHED [eshop/webstatus:linux-latest build 13/38] COPY Services/Basket/Basket.API/Basket.API.csproj Services/Basket/Basket.API/Basket.API.csproj                                                          0.0s
 => CACHED [eshop/webstatus:linux-latest build 14/38] COPY Services/Basket/Basket.FunctionalTests/Basket.FunctionalTests.csproj Services/Basket/Basket.FunctionalTests/Basket.FunctionalTests.csproj          0.0s
 => CACHED [eshop/webstatus:linux-latest build 15/38] COPY Services/Basket/Basket.UnitTests/Basket.UnitTests.csproj Services/Basket/Basket.UnitTests/Basket.UnitTests.csproj                                  0.0s
 => CACHED [eshop/webstatus:linux-latest build 16/38] COPY Services/Catalog/Catalog.API/Catalog.API.csproj Services/Catalog/Catalog.API/Catalog.API.csproj                                                    0.0s
 => CACHED [eshop/webstatus:linux-latest build 17/38] COPY Services/Catalog/Catalog.FunctionalTests/Catalog.FunctionalTests.csproj Services/Catalog/Catalog.FunctionalTests/Catalog.FunctionalTests.csproj    0.0s
 => CACHED [eshop/webstatus:linux-latest build 18/38] COPY Services/Catalog/Catalog.UnitTests/Catalog.UnitTests.csproj Services/Catalog/Catalog.UnitTests/Catalog.UnitTests.csproj                            0.0s
 => CACHED [eshop/webstatus:linux-latest build 19/38] COPY Services/Identity/Identity.API/Identity.API.csproj Services/Identity/Identity.API/Identity.API.csproj                                              0.0s
 => CACHED [eshop/webstatus:linux-latest build 20/38] COPY Services/Ordering/Ordering.API/Ordering.API.csproj Services/Ordering/Ordering.API/Ordering.API.csproj                                              0.0s
 => CACHED [eshop/webstatus:linux-latest build 21/38] COPY Services/Ordering/Ordering.BackgroundTasks/Ordering.BackgroundTasks.csproj Services/Ordering/Ordering.BackgroundTasks/Ordering.BackgroundTasks.cs  0.0s
 => CACHED [eshop/webstatus:linux-latest build 22/38] COPY Services/Ordering/Ordering.Domain/Ordering.Domain.csproj Services/Ordering/Ordering.Domain/Ordering.Domain.csproj                                  0.0s
 => CACHED [eshop/webstatus:linux-latest build 23/38] COPY Services/Ordering/Ordering.FunctionalTests/Ordering.FunctionalTests.csproj Services/Ordering/Ordering.FunctionalTests/Ordering.FunctionalTests.cs  0.0s
 => CACHED [eshop/webstatus:linux-latest build 24/38] COPY Services/Ordering/Ordering.Infrastructure/Ordering.Infrastructure.csproj Services/Ordering/Ordering.Infrastructure/Ordering.Infrastructure.csproj  0.0s
 => CACHED [eshop/webstatus:linux-latest build 25/38] COPY Services/Ordering/Ordering.SignalrHub/Ordering.SignalrHub.csproj Services/Ordering/Ordering.SignalrHub/Ordering.SignalrHub.csproj                  0.0s
 => CACHED [eshop/webstatus:linux-latest build 26/38] COPY Services/Ordering/Ordering.UnitTests/Ordering.UnitTests.csproj Services/Ordering/Ordering.UnitTests/Ordering.UnitTests.csproj                      0.0s
 => CACHED [eshop/webstatus:linux-latest build 27/38] COPY Services/Payment/Payment.API/Payment.API.csproj Services/Payment/Payment.API/Payment.API.csproj                                                    0.0s
 => CACHED [eshop/webstatus:linux-latest build 28/38] COPY Services/Webhooks/Webhooks.API/Webhooks.API.csproj Services/Webhooks/Webhooks.API/Webhooks.API.csproj                                              0.0s
 => CACHED [eshop/webstatus:linux-latest build 29/38] COPY Tests/Services/Application.FunctionalTests/Application.FunctionalTests.csproj Tests/Services/Application.FunctionalTests/Application.FunctionalTe  0.0s
 => CACHED [eshop/webstatus:linux-latest build 30/38] COPY Web/WebhookClient/WebhookClient.csproj Web/WebhookClient/WebhookClient.csproj                                                                      0.0s
 => CACHED [eshop/webstatus:linux-latest build 31/38] COPY Web/WebMVC/WebMVC.csproj Web/WebMVC/WebMVC.csproj                                                                                                  0.0s
 => CACHED [eshop/webstatus:linux-latest build 32/38] COPY Web/WebSPA/WebSPA.csproj Web/WebSPA/WebSPA.csproj                                                                                                  0.0s
 => CACHED [eshop/webstatus:linux-latest build 33/38] COPY Web/WebStatus/WebStatus.csproj Web/WebStatus/WebStatus.csproj                                                                                      0.0s
 => CACHED [eshop/webstatus:linux-latest build 34/38] COPY docker-compose.dcproj docker-compose.dcproj                                                                                                        0.0s
 => CACHED [eshop/webstatus:linux-latest build 35/38] COPY NuGet.config NuGet.config                                                                                                                          0.0s
 => CACHED [eshop/webstatus:linux-latest build 36/38] COPY . .                                                                                                                                                0.0s
 => CACHED [eshop/webstatus:linux-latest build 37/38] WORKDIR /src/Web/WebStatus                                                                                                                              0.0s
 => CACHED [eshop/webhooks.client:linux-latest build  3/39] COPY eShopOnContainers-ServicesAndWebApps.sln eShopOnContainers-ServicesAndWebApps.sln                                                            0.0s
 => CACHED [eshop/webhooks.client:linux-latest build  4/39] COPY ApiGateways/Mobile.Bff.Shopping/aggregator/Mobile.Shopping.HttpAggregator.csproj ApiGateways/Mobile.Bff.Shopping/aggregator/Mobile.Shopping  0.0s
 => CACHED [eshop/webhooks.client:linux-latest build  5/39] COPY ApiGateways/Web.Bff.Shopping/aggregator/Web.Shopping.HttpAggregator.csproj ApiGateways/Web.Bff.Shopping/aggregator/Web.Shopping.HttpAggrega  0.0s
 => CACHED [eshop/webhooks.client:linux-latest build  6/39] COPY BuildingBlocks/Devspaces.Support/Devspaces.Support.csproj BuildingBlocks/Devspaces.Support/Devspaces.Support.csproj                          0.0s
 => CACHED [eshop/webhooks.client:linux-latest build  7/39] COPY BuildingBlocks/EventBus/EventBus/EventBus.csproj BuildingBlocks/EventBus/EventBus/EventBus.csproj                                            0.0s
 => CACHED [eshop/webhooks.client:linux-latest build  8/39] COPY BuildingBlocks/EventBus/EventBus.Tests/EventBus.Tests.csproj BuildingBlocks/EventBus/EventBus.Tests/EventBus.Tests.csproj                    0.0s
 => CACHED [eshop/webhooks.client:linux-latest build  9/39] COPY BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.csproj BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.csproj            0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 10/39] COPY BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.csproj BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.csproj    0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 11/39] COPY BuildingBlocks/EventBus/IntegrationEventLogEF/IntegrationEventLogEF.csproj BuildingBlocks/EventBus/IntegrationEventLogEF/IntegrationEventLo  0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 12/39] COPY BuildingBlocks/WebHostCustomization/WebHost.Customization/WebHost.Customization.csproj BuildingBlocks/WebHostCustomization/WebHost.Customiz  0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 13/39] COPY Services/Basket/Basket.API/Basket.API.csproj Services/Basket/Basket.API/Basket.API.csproj                                                    0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 14/39] COPY Services/Basket/Basket.FunctionalTests/Basket.FunctionalTests.csproj Services/Basket/Basket.FunctionalTests/Basket.FunctionalTests.csproj    0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 15/39] COPY Services/Basket/Basket.UnitTests/Basket.UnitTests.csproj Services/Basket/Basket.UnitTests/Basket.UnitTests.csproj                            0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 16/39] COPY Services/Catalog/Catalog.API/Catalog.API.csproj Services/Catalog/Catalog.API/Catalog.API.csproj                                              0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 17/39] COPY Services/Catalog/Catalog.FunctionalTests/Catalog.FunctionalTests.csproj Services/Catalog/Catalog.FunctionalTests/Catalog.FunctionalTests.cs  0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 18/39] COPY Services/Catalog/Catalog.UnitTests/Catalog.UnitTests.csproj Services/Catalog/Catalog.UnitTests/Catalog.UnitTests.csproj                      0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 19/39] COPY Services/Identity/Identity.API/Identity.API.csproj Services/Identity/Identity.API/Identity.API.csproj                                        0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 20/39] COPY Services/Ordering/Ordering.API/Ordering.API.csproj Services/Ordering/Ordering.API/Ordering.API.csproj                                        0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 21/39] COPY Services/Ordering/Ordering.BackgroundTasks/Ordering.BackgroundTasks.csproj Services/Ordering/Ordering.BackgroundTasks/Ordering.BackgroundTa  0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 22/39] COPY Services/Ordering/Ordering.Domain/Ordering.Domain.csproj Services/Ordering/Ordering.Domain/Ordering.Domain.csproj                            0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 23/39] COPY Services/Ordering/Ordering.FunctionalTests/Ordering.FunctionalTests.csproj Services/Ordering/Ordering.FunctionalTests/Ordering.FunctionalTe  0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 24/39] COPY Services/Ordering/Ordering.Infrastructure/Ordering.Infrastructure.csproj Services/Ordering/Ordering.Infrastructure/Ordering.Infrastructure.  0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 25/39] COPY Services/Ordering/Ordering.SignalrHub/Ordering.SignalrHub.csproj Services/Ordering/Ordering.SignalrHub/Ordering.SignalrHub.csproj            0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 26/39] COPY Services/Ordering/Ordering.UnitTests/Ordering.UnitTests.csproj Services/Ordering/Ordering.UnitTests/Ordering.UnitTests.csproj                0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 27/39] COPY Services/Payment/Payment.API/Payment.API.csproj Services/Payment/Payment.API/Payment.API.csproj                                              0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 28/39] COPY Services/Webhooks/Webhooks.API/Webhooks.API.csproj Services/Webhooks/Webhooks.API/Webhooks.API.csproj                                        0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 29/39] COPY Tests/Services/Application.FunctionalTests/Application.FunctionalTests.csproj Tests/Services/Application.FunctionalTests/Application.Functi  0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 30/39] COPY Web/WebhookClient/WebhookClient.csproj Web/WebhookClient/WebhookClient.csproj                                                                0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 31/39] COPY Web/WebMVC/WebMVC.csproj Web/WebMVC/WebMVC.csproj                                                                                            0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 32/39] COPY Web/WebSPA/WebSPA.csproj Web/WebSPA/WebSPA.csproj                                                                                            0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 33/39] COPY Web/WebStatus/WebStatus.csproj Web/WebStatus/WebStatus.csproj                                                                                0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 34/39] COPY docker-compose.dcproj docker-compose.dcproj                                                                                                  0.0s
 => CACHED [eshop/webhooks.client:linux-latest build 35/39] COPY NuGet.config NuGet.config                                                                                                                    0.0s
 => [eshop/identity.api:linux-latest internal] load build context                                                                                                                                             0.3s
 => => transferring context: 106.16kB                                                                                                                                                                         0.2s
 => CANCELED [eshop/webstatus:linux-latest build 38/38] RUN dotnet publish -c Release -o /app                                                                                                                 1.1s
 => CANCELED [eshop/webhooks.client:linux-latest build 36/39] RUN dotnet restore "eShopOnContainers-ServicesAndWebApps.sln"                                                                                   0.9s
 => [eshop/ordering.api:linux-latest internal] load build context                                                                                                                                             0.3s
 => => transferring context: 106.16kB                                                                                                                                                                         0.2s
 => [eshop/ordering.signalrhub:linux-latest internal] load build context                                                                                                                                      0.3s
 => => transferring context: 106.16kB                                                                                                                                                                         0.2s
 => [eshop/webhooks.api:linux-latest internal] load build context                                                                                                                                             0.3s
 => => transferring context: 106.16kB                                                                                                                                                                         0.2s
 => [eshop/ordering.backgroundtasks:linux-latest internal] load build context                                                                                                                                 0.3s
 => => transferring context: 106.16kB                                                                                                                                                                         0.2s
 => [eshop/webspa:linux-latest internal] load build context                                                                                                                                                   0.1s
 => => transferring context: 106.16kB                                                                                                                                                                         0.1s
 => [eshop/webspa:linux-latest node-build 1/8] FROM docker.io/library/node:12.0@sha256:c88ef4f7ca8d52ed50366d821e104d029f43e8686120a29541ce0371f333453f                                                       0.0s
 => CACHED [eshop/webspa:linux-latest base 2/2] WORKDIR /app                                                                                                                                                  0.0s
 => CACHED [eshop/webspa:linux-latest base 3/8] RUN apt-get update                                                                                                                                            0.0s
 => CACHED [eshop/webspa:linux-latest base 4/8] RUN apt-get -y install curl gnupg                                                                                                                             0.0s
 => CACHED [eshop/webspa:linux-latest base 5/8] RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -                                                                                                   0.0s
 => CACHED [eshop/webspa:linux-latest base 6/8] RUN apt-get -y install nodejs                                                                                                                                 0.0s
 => ERROR [eshop/webspa:linux-latest base 7/8] RUN npm install                                                                                                                                                0.5s
 => CACHED [eshop/webspa:linux-latest node-build 2/8] WORKDIR /web/src                                                                                                                                        0.0s
 => CACHED [eshop/webspa:linux-latest node-build 3/8] COPY Web/WebSPA/Client/package.json .                                                                                                                   0.0s
 => CACHED [eshop/webspa:linux-latest node-build 4/8] COPY Web/WebSPA/Client/package-lock.json .                                                                                                              0.0s
 => CACHED [eshop/webspa:linux-latest node-build 5/8] RUN npm install -g npm@6                                                                                                                                0.0s
 => CACHED [eshop/webspa:linux-latest node-build 6/8] RUN npm install                                                                                                                                         0.0s
 => CACHED [eshop/webspa:linux-latest node-build 7/8] COPY Web/WebSPA/Client .                                                                                                                                0.0s
 => CACHED [eshop/webspa:linux-latest node-build 8/8] RUN npm run build:prod                                                                                                                                  0.0s
------
 > [eshop/webspa:linux-latest base 7/8] RUN npm install:
#0 0.444 /bin/sh: 1: npm: not found
------
failed to solve: executor failed running [/bin/sh -c npm install]: exit code: 127

**Comment by ramganesh19** [comment]
I am running this on my windows 11 with WSL 2 enabled and Docker Installed. Appreciate your help and troubleshooting this build issue

**Comment by erjain** [comment]
Hi @ramganesh19, Are you able to run npm install using cmd at location `dotnet-architecture\eShopOnContainers\src\Web\WebSPA\Client` . There seems to be an issue with building the SPA project in your system. Also, try building without cache using the command: docker-compose build --no-cache. Let me know if this works.

**Comment by ramganesh19** [comment]
Thanks Erjain for your input. I dont have nodejs installed yet on my laptop. Hence npm install doesnt work. Is it a prerequisite that I need to have nodejs installed locally on my laptop to build docker image and run docker.

I tried the docker-compose build --no-cache and it did finish compiling successfully. But I get the error page in getting catalog
![image](https://user-images.githubusercontent.com/12521269/169448617-5ccde120-358e-4006-8593-97b0100d787c.png)

Not sure again if browser cache issue. So when I hit shift refresh, I get below error message
An unhandled exception occurred while processing the request.
AggregateException: One or more errors occurred. (The npm script 'start' exited without indicating that the Angular CLI was listening for requests. The error output was: sh: 1: ng: not found

npm ERR! code ELIFECYCLE

npm ERR! syscall spawn

npm ERR! file sh

npm ERR! errno ENOENT

npm ERR! eshopaspnetnetcoredockerspa@0.0.0 start: `ng serve "--port" "35013"`

npm ERR! spawn ENOENT

npm ERR!

npm ERR! Failed at the eshopaspnetnetcoredockerspa@0.0.0 start script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm WARN Local package.json exists, but node_modules missing, did you mean to install?

**Comment by erjain** [comment]
Sometimes an error during startup can disturb the application deployment and entries in the databases. Could you please clean up old docker images and build the docker images again? - To run the app 
- Go to the `/src/` directory

```text
docker-compose up sqldata
```
Once it's ready to accept the new connection, then you can bring up the other container by using the following command from a separate terminal window.

```text
docker-compose up
```

**Comment by dacy** [comment]
Were you able to fix this? I had the same issue and I did the following and some these steps fixed my issue. 

Installed NodeJs
Installed Angular
Run npm install in the `src\Web\WebSPA\Client` folder
Removed all the old containers
Docker-compose Build with `--no-cache`
Run visual studio in admin mode
Use an incognito session or a different browser

Because the error says angular has not been started, I thought perhaps it was not automatically installed as it's supposed to. Changing to a different browser seems to be an important step, because it was until I changed to a different browser (incognito worked too), that it started working.

**Comment by ramganesh19** [comment]
Thanks Dacy. I tried all your options above and still having issues

WebMVC:
InvalidOperationException: IDX20803: Unable to obtain configuration from: 'http://localhost:5105/.well-known/openid-configuration'.

Microsoft.IdentityModel.Protocols.ConfigurationManager<T>.GetConfigurationAsync(CancellationToken cancel)

WebSPA:
Worked finally by running with Visual Studio (as administrator) F5

Glad atleast WebSPA started working. But it took a while and was timing out at early stage

**Comment by erjain** [comment]
Hi @ramganesh19, it seems to be some interim system-related configuration issue at your end, Your WebMVC is not able to communicate with the identity service, as I said, generally, an error during startup can disturb the application deployment and entries in the databases. Try following the instruction given on the wiki link https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup. Considering your original issue is resolved I am closing this issue. Please feel free to reopen it, if needed.
