### ISSUE TITLE
Question on debugging on Docker Containers

### ISSUE THREAD

**Issue by dogaanismail** [dotnet/eShopOnContainers#1921]
Hello,

I can successfully debug code on Docker Containers, but suppose that I change code blocks and want to debug again with new changes. As you know, A Docker container must be recreated for new changes and then I will be able to debug on new code blocks. 

My question is that how can I recreate Docker Container with new changes? (For instance, Ordering.API must be recreated again.

In addition to my question and to clerify the question and problem, I would like to give an example.
I simply changed some code blocks for Web SPA, but when I started the project with docker compose, I could not see the new code blocks. 

I look forward to hearing from you.

Best regards,
Ismail

**Comment by erjain** [comment]
Hi @dogaanismail, Thanks for posting your query. If you want to recreate the container with a new image after your changes, then remove the specific image instance from the container which you want to update and delete the respective image from docker, then you can build a specific microservice or project by using 
`docker-compose up <imagename>`, e.g. if you want to run webspa only, then you will run 
`docker-compose build webspa`, 
and then after a successful build, run below command 
`docker-compose up <imagename>`, e.g. `docker-compose up webspa`. Your container should be updated with the new changes. Let me know if this works for you.

**Comment by velosojose** [comment]
sevgili doğan ismail
,
Anlayışınız için teşekkürler, bu isimde birini arıyordum. Sizinle iletişim kurmaya ve birbirimize en iyi nasıl yardımcı olabileceğimizi görmeye zorlandım. Ben burada Filipinler Ulusal Bankası'nda denetim müdürü olarak çalışan Bay Jose Veloso. Seninle şimdi tanışmamın Tanrı'nın isteği olduğuna inanıyorum. Sizinle paylaşmak istediğim önemli bir iş görüşmem var, ilginizi çekeceğine inanıyorum çünkü soyadınızla ilgili ve bundan faydalanacaksınız.
Ülkenizin Gentian ismail adlı bir vatandaşının bankamda 12.500.000,00 USD (On iki milyon beş yüz bin ABD Doları) değerinde sabit bir mevduatı vardı, bu mevduatın son kullanma tarihi geçen yıldı. Gentian ismail, 11 Mayıs 2012'de Filipinler'in Paranaque Manila şehrine giden yolda yedi aracın karıştığı ve otuz beş kişinin olay yerinde hayatını kaybettiği kazada hayatını kaybedenler arasında yer aldı.

**Comment by erjain** [comment]
I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
