### ISSUE TITLE
Issue in running docker-compose build command

### ISSUE THREAD

**Issue by nasrinazif** [dotnet/eShopOnContainers#1926]
Hello everyone,

I tried to build the application using this command:

docker-compose build

I tried it many times, but every time I get this error message:

![Build Issue](https://user-images.githubusercontent.com/23409009/173735401-5c838092-261c-4bd7-97ca-8a440f574966.jpg)

I would appreciate it if you could tell me how I can overcome this problem.

Regards

**Comment by erjain** [comment]
Sometimes an error during startup can disturb the application deployment and entries in the databases. Could you please clean up old docker images and build the docker images again? - To run the app 
- Go to the `/src/` directory

```text
docker-compose up sqldata
```
Once it's ready to accept the new connection, then you can bring up the other container by using the following command from a separate terminal window.

```text
docker-compose up
```

Let us know if this works for you.

**Comment by erjain** [comment]
I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
