### ISSUE TITLE
Encounter Build Error

### ISSUE THREAD

**Issue by pipchan** [dotnet/eShopOnContainers#1929]
Having an issue when docker-compose build, any suggestion?

![2022-06-21_15-52-19](https://user-images.githubusercontent.com/25620202/174886299-b3a905d4-d700-4461-a41e-69dd87e69e69.png)

**Comment by otuo-k** [comment]
Had the same issue. I resolved it by

1. installing the Libman CLI.
        dotnet tool install -g Microsoft.Web.LibraryManager.Cli

2. Opened cmd in the folder contain the libman.json file and run the following command
      > libman cache clean
      > libman restore
[](https://docs.microsoft.com/en-us/aspnet/core/client-side/libman/libman-cli?view=aspnetcore-6)

3. Go to project(s) in visual studio
    - Right click on libman.json file 
    - Click "Disable Client-Side Libraries on Build"

4. Build/run project.

Hope this helps

**Comment by erjain** [comment]
Hi @pipchan, thanks for posting your query. Sometimes an error during startup can disturb the application deployment and entries in the databases.  Could you please clean up old docker images and build the docker images again?  - To build and run the app 
- Go to the `/src/` directory and first-time build without cache

```text
docker-compose build --no-cache
```
- then, run

```text
docker-compose up sqldata
```
- Once it's ready to accept the new connection, then you can bring up the other container by using the following command from a separate terminal window.

```text
docker-compose up
```

Let us know if this works for you.

**Comment by erjain** [comment]
I am closing this issue, however, feel free to reopen it if you need more help.

**Comment by pipchan** [comment]
Hi @otuo-k:

I followed your steps as well as followed this as I am a MacOS user https://github.com/aspnet/LibraryManager/issues/367#issuecomment-631896612

However, but get the below error when I try libman restore
libman.json was not found

Hi @erjain

I followed your steps too but I still get the same error

![2022-08-24_05-28-34](https://user-images.githubusercontent.com/25620202/186383575-1ab450de-9e57-4e71-a570-2cadece551a9.png)
