### ISSUE TITLE
[Question] Is ValueObject necessary with record in C# 9.0+?

### ISSUE THREAD

**Issue by corygehr** [dotnet/eShopOnContainers#1930]
My takeaway from `ValueObject` is its utility derives from its equality helpers. From what I understand about `record`, it seems like C# now provides those capabilities out-of-the-box.

Given this, is there a case for continuing to use `ValueObject`? I suspect some scenarios could exist for modifying properties but even something like `Address` has properties with `private set;` anyway.

I imagine this could be a result of legacy code (and the accompanying eBook referencing `ValueObject` directly) but before I do something which could haunt me later, I'm curious if I'm not being thoughtful enough. It would help to cite this somewhere since the repo has been updated for .NET 6.0.

**Comment by ravividap** [comment]
@corygehr AFAIK ValueObject is something that doesn't have Id (identity) for e.g Address like you mentioned, or DateRangeClass. Whereas records can have Id properties but they are just read-only. So I think we can have both of them. What do you think?

**Comment by corygehr** [comment]
It's still possible to have read/write properties with `record` but most usage examples seem to imply it's primarily meant for read-only values.

I think my point is that features of `record` seem to supercede `ValueObject` enough that it's no longer necessary. There's no harm in keeping both, but if I can simplify my service by removing the abstraction, subsequent unit tests, equality logic, etc. then I prefer removal (at least on a new project).

**Comment by ardalis** [comment]
See: https://enterprisecraftsmanship.com/posts/csharp-records-value-objects/

**Comment by corygehr** [comment]
@ardalis that's exactly what I was after. Thank you! This presents a clear case for still needing `ValueObject`, assuming the things `record` lacks are part of your requirements (which I expect many are, except for maybe a **very** simple application).

The point about collection comparison in equality checks is especially relevant, as it's something I came across when working with `record` recently.
