### ISSUE TITLE
Integration Events in Ordering microservice

### ISSUE THREAD

**Issue by ffrankozz** [dotnet/eShopOnContainers#1936]
Hi,
I would be very glad if someone could help me on Ordering microservice's  event publishing mechanism. I am confused about the Integration Events publishing in the Ordering microservice. I see that the Integration Events are saved in the relevant database first instead of publishing them right  after entity persistence.
But when they are in the database, how on earth do they find their way on the event bus?
I see that there is a BackgroundWorker service that handles an event called GracePeriodIntegrationEvent .
But in that code, I see that only the ids of the events in the database are obtained and GracePeriodIntegrationEvents are created from the ids without any other event data inside the event object, which are then published. Moreover, where do we set the published events' status in the database to "already published" so that they do not get published again? I just do not see any code doing all of these in the Ordering microservice: What am I missing? Thank you for your help in advance.

**Comment by jinzaz** [comment]
You can find the transactionbehavior class. All integrationevents will pass through here before they are added to the database. First, create a transaction and generate a "transactionid". All integrationevents in the transaction are bound to this "transactionid". Then, after the transaction is submitted, you will see that the "publisheventthrougheventbusasync" method is called, which is the method to change the publishing status, First, find all integrationevents through "transactionid" and modify the status, and route by specifying routekey as "eventName" through rabbitmq

**Comment by erjain** [comment]
Thanks @jinzaz, for helping on the issue.
Hi @ffrankozz, thanks for posting your query here. I am closing this issue as of now. Please feel free to reopen if it's needed.
