### ISSUE TITLE
Libraries could not be resolved by the "cdnjs" provider

### ISSUE THREAD

**Issue by lfdesousa** [dotnet/eShopOnContainers#1942]
Hi,
While trying to do a docker-compose build I randomly get errors like the one below, is this also related with this issue ?
https://github.com/aspnet/LibraryManager/issues/685

```
 ---> Running in e9466a7c9528
Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /src/Web/WebStatus/WebStatus.csproj (in 11.01 sec).

  Restore operation started...
libman.json : error LIB002: The "jquery@3.4.1" library could not be resolved by the "cdnjs" provider [/src/Web/WebStatus/WebStatus.csproj]

  One or more libraries failed to restore

The command '/bin/sh -c dotnet publish -c Release -o /app' returned a non-zero code: 1
ERROR: Service 'webstatus' failed to build : Build failed
````

**Comment by lfdesousa** [comment]
I think that I found a solution here: https://github.com/dotnet-architecture/eShopOnContainers/pull/1939/commits/d719444e6187414a58a0d906b1a48bb3d34d8133

I tried it locally and it is working for me

**Comment by erjain** [comment]
Hi @lfdesousa, thanks for reporting this issue and suggesting a solution. I am linking PR #1939 already created to resolve this issue. I am closing this issue, please feel free to reopen it in case of any further queries.
