### ISSUE TITLE
Socket Connection Problem though eshopContainer inbound/outbound Rules are in place

### ISSUE THREAD

**Issue by ChrisFist** [dotnet/eShopOnContainers#1943]
Hello support Team,
after starting the containers I can run the mvc application and register as a new user or take existing demo user. But I cannot add any Items to the basket. Reason:
![image](https://user-images.githubusercontent.com/35878355/180833707-d4214aee-f476-47d3-b872-d78794790292.png).
The firewall rules are in place. What else could be the reason? I run the application w/o any VPN.

**Comment by erjain** [comment]
Hi @ChrisFist, thanks for posting your query. I tested this application completely and it is working fine. Can you share some details, about the method you are following for deployment. Sometimes an error during startup can disturb the application deployment and entries in the databases.  Could you please clean up old docker images and build the docker images again?  - To build and run the app 
- Go to the `/src/` directory and first-time build without cache

```text
docker-compose build --no-cache
```
- then, run

```text
docker-compose up sqldata
```
- Once it's ready to accept the new connection, then you can bring up the other container by using the following command from a separate terminal window.

```text
docker-compose up
```

Let us know if this works for you.

**Comment by erjain** [comment]
I am closing this issue, please free to reopen it if you are looking for more help.

**Comment by ChrisFist** [comment]
Dear Support Team,
I followed your instruction and partly this "clean build" solved some problems. The Health Check shows now only green services. And I can now properly open also the SPA Page (Yesterday it was not working). But infortunately I get Exceptions when clicking on login link of SPA: Some Probmels with the database.
![image](https://user-images.githubusercontent.com/35878355/181031809-0923bb0b-a6b5-49fa-a271-c4373a54e43f.png)
When clicking on the login link of MVC Web app following error appears:
![image](https://user-images.githubusercontent.com/35878355/181033257-027ef5e6-1fb6-4eb4-8e7a-100c568da360.png)
Maybe you understand what's going on. Thank you for your investigation
