### ISSUE TITLE
Problems to run SPA with VS 2022 in debug mode

### ISSUE THREAD

**Issue by ChrisFist** [dotnet/eShopOnContainers#1946]
Hi Support Team, I followed detailed instruction for VS set up to run the applications in debug mode. Especially I changed the configuration as indicated for SPA case. But unfortunately I faced then following error:

![image](https://user-images.githubusercontent.com/35878355/181269625-88a176a7-ecd3-4deb-be04-6be1ad299f56.png)

**Comment by erjain** [comment]
Hi @ChrisFist, I again tested the application and it is working fine. Sharing the screenshot, I recommend not changing any instructions. Sometimes a failed startup can corrupt the running containers. Can you delete all images and volumes or reset Docker and try again?
![image](https://user-images.githubusercontent.com/87998741/182099059-ebc43390-0bd6-4c0f-943a-fd5491b8ab4e.png)

**Comment by ChrisFist** [comment]
Dear Support team  I created an unlisted Youtube video, where I show what I did and which errors I face in detail:
https://youtu.be/69uwn932mvA
Unfortunately I cannot run the apps using docker-compose w/o Visual Studio. When runnung the system with VS2022 in debug mode I can run the MVC application but not SPA. Problems with Angular configuration though I added the code changes in Dockerfile of SPA. I hope the video helps you to understand the problem in my enviroment.

**Comment by Hadsen** [comment]
I get same error while debugging in VS2022, after modifying /WebSPA/Dockerfile and docker-compose.override.yml, as suggested.

**Comment by Hadsen** [comment]
So "npm start" gives "ng: not found" error, looks like there is no Angular in the WebSPA container. Don't know how it is supposed to work, but after installing Angular in the container's Client folder it starts working, and keeps doing so after rebuildings, cause it creates node_modules folder with Angular in the project source folder.

**Comment by ChrisFist** [comment]
Hi, that's a good hint I installed angular globally but that fixed only partially bthe problem. Can you please explain more detailed how you installed Angular as you told in the Client folder. Since I don't know much about angular on linux. You went into directory /app/Client of the container and installed there the Angular CLI and then it was working?

**Comment by Hadsen** [comment]
Yes, it worked like workaround, but i don't really know what i'm doing, and i would like to know how to fix it properly.

**Comment by ChrisFist** [comment]
Yes that is really not a satisfying situation. Are you able to run the applications without VS. If I run without VS I can use the MVC and SPA applications but only the catalog searching works. as soon as I try to login I face authorization problems.

**Comment by Hadsen** [comment]
Yes, I can run and use login process, but i think it is separate issue from one you have in starting post, so it might be confusing to discuss in same thread. I have some temporary issues, when some services have been started, and others not yet, but they resolve themselves by waiting, or by reseting/restarting or smth like that. Also I've noticed on your video, that everything is opening much slower, than on my pretty mediocre pc. Are you using ssd or hdd? Do you have enough hardware resources for this pretty heavy project?

**Comment by ChrisFist** [comment]
You are right there are two problems I face: When runnig the apps via "docker-compose up" command even after a full build (no cache issue) the database IdentityDb does not contain all t ables. E.g., table IdentityProperties is missing. And that causes of course problems. The other problem is runnig the SPA in VS debug mode. Your workarround is fine for my purposes currently. The database problem is somehow I suppose a synchronization problem between the containers. Wen starting the APP within VS the table is created:
![image](https://user-images.githubusercontent.com/35878355/184124759-ef4e755a-8cef-41bf-98d0-5deb0ef5adfa.png)

but I have no clou how to resolve this build issue. Anyhow I close this issue.
