### ISSUE TITLE
host.docker.internal didn’t send any data for WebStatus endpoint

### ISSUE THREAD

**Issue by ngaisteve1** [dotnet/eShopOnContainers#1947]
I am trying to run https://github.com/dotnet-architecture/eShopOnContainers locally. I managed to set up all the 21 containers in my Docker Desktop and all the 21 containers are running.

But when I try to access to http://host.docker.internal:5107/ for WebStatus endpoint, I got this error in my browser. 

This page isn’t working
host.docker.internal didn’t send any data.
ERR_EMPTY_RESPONSE

I have also run both powershell scripts at deploy/windows folder. In fact, when I go to http://host.docker.internal:5100/ , it also showing the same error.

**Comment by erjain** [comment]
Hi @ngaisteve1, I tested this application completely and it is working fine. Can you share some details, about the method you are following for deployment. Sometimes an error during startup can disturb the application deployment and entries in the databases.  Could you please clean up old docker images and build the docker images again?  - To build and run the app 
- Go to the `/src/` directory and first-time build without cache

```text
docker-compose build --no-cache
```
- then, run

```text
docker-compose up sqldata
```
- Once it's ready to accept the new connection, then you can bring up the other container by using the following command from a separate terminal window.

```text
docker-compose up
```

Let us know if this works for you.

**Comment by ngaisteve1** [comment]
I run the "Clean up" to delete all the images and retry. When I run docker-compose build --no-cache, I notice many error like below:

Failed to download package 'System.Diagnostics.DiagnosticSource.5.0.0' from 'https://api.nuget.org/v3-flatcontainer/system.diagnostic
 => => # s.diagnosticsource/5.0.0/system.diagnostics.diagnosticsource.5.0.0.nupkg'.

Is it normal?

**Comment by erjain** [comment]
No, it is not normal, it seems there are some issues while downloading packages. Can you ensure that you have all dependencies to run your project?

**Comment by ngaisteve1** [comment]
When I run **docker-compose build --no-cache** again, I got another error

failed to solve: error committing ahkwpxlwumb1uo0yg2f8so6j0: write /var/lib/docker/buildkit/metadata_v2.db: read-only file system

**Comment by ngaisteve1** [comment]
Now I manage to build all the 21 images. How command can I use to create the container which has these 21 images? I run docker-compose up but got this error

$ docker-compose up
The INSTRUMENTATION_KEY variable is not set. Defaulting to a blank string.
The ORCHESTRATOR_TYPE variable is not set. Defaulting to a blank string.
The ESHOP_SERVICE_BUS_USERNAME variable is not set. Defaulting to a blank string.
The ESHOP_SERVICE_BUS_PASSWORD variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_CATALOG_NAME variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_CATALOG_KEY variable is not set. Defaulting to a blank string.
Creating network "src_default" with the default driver
failed to update bridge store for object type *bridge.networkConfiguration: open /var/lib/docker/network/files/local-kv.db: read-only file system

**Comment by erjain** [comment]
Hi @ngaisteve1, There may be some interim issue or system-related issue, please refer to our wiki page for windows setup: https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup. I am closing this issue as of now, however, please feel free to continue conversations in case of any further issues
