### ISSUE TITLE
ProfileService is not used

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/eShopOnContainers#1951]
I don't see `ProfileService`/`IProfileService` used anywhere.

I was looking for an example of how to use permissions in DDD and I noticed that these types aren't used anywhere.

**Comment by ravividap** [comment]
@MisinformedDNA Can you raise a PR to delete these?

**Comment by erjain** [comment]
I am closing this issue as per the explanation given in PR #1960.
