### ISSUE TITLE
Missing Basket item quantity validation in backend.

### ISSUE THREAD

**Issue by ChrisFist** [dotnet/eShopOnContainers#1957]
At present the item quantity validation is only ensured by 
![image](https://user-images.githubusercontent.com/35878355/186097035-05136740-732b-4a18-9231-1932b64e0718.png)
of ..Shared/Components/CartList/Default.cshtml in case of MVC client. There is a validation defined for model **BasketItem** in 
![image](https://user-images.githubusercontent.com/35878355/186097650-ed6dc601-dd4c-4be4-b89a-8dac6950585e.png)
but this validation is not applied in implementation of **UpdateBasketAsync** in 
![image](https://user-images.githubusercontent.com/35878355/186098011-866e3288-5b0c-4f1a-ba0a-5a7dbd1a800f.png).
I suggest an improvement in UpdateBasketAsync like the following:

![image](https://user-images.githubusercontent.com/35878355/186098411-41f5c6b6-f8fa-4d10-a463-3b433bfae571.png)

**Comment by erjain** [comment]
Hi @ChrisFist, Thank you so much for pointing this out, we are glad if you or anyone from the community can share the PR and we can evaluate and update the same.

**Comment by ravividap** [comment]
@ChrisFist  do we really need to have validation again in the repository? BasketController already validates it.

**Comment by ChrisFist** [comment]
Hi Ravi,

I cannot see the validation in BasketController when updating the quantity property of a basket item except as mentioned in ..Shared/Components/CartList/Default.cshtml, which is a pure client/gui validation. The CustomerBasket Model class has as List property elements of type BasketItem. The model class BasketItem itself implements the IValidateObject interface taking care for the positive quantity value. But related Validate method is **not** invoked at all when calling:

![image](https://user-images.githubusercontent.com/35878355/187025810-b947ad23-98b1-4f97-95c3-7df3dcf95a2f.png)

If I comment the min=1 constraint of quantity input tag in Cartlist/Default.cshtml
![image](https://user-images.githubusercontent.com/35878355/187026254-567d2a3c-73a4-4a61-948c-4323caca3bde.png)
I can enter without any problems negative quantities and persist them into database using the update button (see below)

![image](https://user-images.githubusercontent.com/35878355/187026341-432019e7-d918-42fa-9ce1-4034f49cd267.png)

From my point of view validation in MicroService architecture should **not** depend **only** on client validation. Hence I suggest a little improved change:

![image](https://user-images.githubusercontent.com/35878355/187026594-973854b5-129a-4935-8795-eaca41efacea.png)

with validateBasket:

![image](https://user-images.githubusercontent.com/35878355/187026624-c181800b-2f6f-43c2-bc9b-5a17528a8000.png)

**Comment by ravividap** [comment]
@ChrisFist  I see the page is calling basket grpc service and not rest web API. Generally, validation should be handled at higher levels(e.g. by the controller) and the rest web API is doing that (not directly but there are filters written see image below)
<img width="237" alt="image" src="https://user-images.githubusercontent.com/12791849/187029162-410980da-b5c6-4554-b012-cf110c49fa51.png">

And there is an open issue in grpc-dotnet repo that would allow handling validation models/messages, but unfortunately, it's still open https://github.com/grpc/grpc-dotnet/issues/741.

So yeah in this case we can have validation at Repo level then.

**Comment by ChrisFist** [comment]
I see! The filter of course should be actual place for Model validation. So far the front end Cartlist/Default.cshtml prevents the entering of negative or zero quantities. I was not aware of this Model/State filter. I agree this filter should handle the model validation of the basket items. But I have not understood why the Modelstate is not set to false in the filter when entering negative Quantities to a basket item. Additionally I don's see in breakpoint OnActionExecuting  the UpdateBasket action bit ony GetBasketIdAsync. So if there is a way to do validation on filter level than this is fine for me else you should do it on repo level.
