### ISSUE TITLE
Basket Service - GetBasket - called too often in MVC Client

### ISSUE THREAD

**Issue by ChrisFist** [dotnet/eShopOnContainers#1959]
When showing the basket content of a user by clicking on his card the view /Card/Index is invoked which requires as View Output to the model variable a basket. Hence in related action controller CartController.cs you find:

 var vm = await _basketSvc.GetBasket(user);
 return View(vm);

calling the GetBasket service for the connected user. But this is not needed because the /Card/Index calls ViewComponent Cardlist which calls as well the GetBasket service. This is sufficient and the GetBasket call in Index Action of CartController.cs is not needed.

Proposed changes in CartController.cs:
![image](https://user-images.githubusercontent.com/35878355/186431096-a1cfe3ff-f847-412e-a70a-64b707c0b2a4.png)

and change in /Card/Index.cshtml

![image](https://user-images.githubusercontent.com/35878355/186431372-5bd21e7c-31c7-4656-986e-1dd2be0f234b.png)

**Comment by ravividap** [comment]
I want to pick this up

**Comment by erjain** [comment]
I am closing this issue since it's not an issue, this piece of code will be used to get the data based on the identity of the user. However please feel free to post here.
