### ISSUE TITLE
[Question] Web API vs gRPC?

### ISSUE THREAD

**Issue by alextse** [dotnet/eShopOnContainers#1963]
Hi there, I'm new to the microservice architecture.  Please excuse my newbie question to this sample project.
In the solution there's a regular Web API `BasketController` and gRPC service `BasketService`.  
I can see that the gRPC service is being called by the API Gateway but could not find any usage about the Web API.  Can someone help me understand the usage of it please?

Thanks.

**Comment by erjain** [comment]
Hi @alextse, Thanks for posting your query here. Please visit our wiki page for more information on the usage of gRPC in eShopOnContainers: https://github.com/dotnet-architecture/eShopOnContainers/wiki/gRPC. Please let us know in case of any further queries.

**Comment by erjain** [comment]
I am closing this issue since this is not an issue, however feel free to continue the conversation in case any further queries.
