### ISSUE TITLE
Unable to create an object of type 'ApplicationDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

### ISSUE THREAD

**Issue by pascalfossouo** [dotnet/eShopOnContainers#1967]
.Net 6 vs 2022

![Capture1](https://user-images.githubusercontent.com/12487736/188641956-d7e89ea8-fc10-40af-a70e-d1356fd1c7c1.PNG)

![image](https://user-images.githubusercontent.com/12487736/188642157-91aec720-f21d-48f3-a576-29f786ebe4c3.png)
![image](https://user-images.githubusercontent.com/12487736/188642256-0877d855-907f-47b3-872a-a74aa84ef1a1.png)

![image](https://user-images.githubusercontent.com/12487736/188642721-0ec7b91e-8617-42e3-aced-4ffb925362c5.png)

![image](https://user-images.githubusercontent.com/12487736/188642648-ca38caf9-d204-4ecb-99aa-2f2c8237ea6e.png)

![image](https://user-images.githubusercontent.com/12487736/188648392-3848eb58-3d8c-4591-b583-287825889b26.png)

**Comment by pascalfossouo** [comment]
Allo still have no solution. someone can help me with that ?

**Comment by pascalfossouo** [comment]
Resolve 👍 

Put on your file this in order 

![image](https://user-images.githubusercontent.com/12487736/189169522-ba80c97f-271a-42ff-9922-8d80d4330a51.png)

**Comment by shriramshende8391** [comment]
Thank you so much problem resolved

**Comment by shriramshende8391** [comment]
using Microsoft.AspNetCore.DataProtection.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System.Collections.Generic;
using WebApplication2.Models;

namespace WebApplication2.Data
{
    public class ApplicationDbContext : DbContext
    {

       public ApplicationDbContext():base()
        {

        }
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> Options) : base(Options)
        {

        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if(!optionsBuilder.IsConfigured)
            {
                IConfigurationRoot configuration=new ConfigurationBuilder()
                    .SetBasePath(Directory.GetCurrentDirectory())
                    .AddJsonFile("appsettings.json")
                    .Build();
                var connectionstring = configuration.GetConnectionString("default_connection");
                optionsBuilder.UseSqlServer(connectionstring);

            }


        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            
            base.OnModelCreating(modelBuilder);
        }
        public DbSet<tbladmin_details> tbladmin_details { get; set; }

    }
}
