### ISSUE TITLE
Why queries doesn't been send within query bus?

### ISSUE THREAD

**Issue by 1304654** [dotnet/eShopOnContainers#1968]
I wonder why it's the reason to don't send queries throughout the bus. For instance .
`_bus.send( new getQustomerQuery())`
That allows to implement decorators in the query side if it's necessary have query times or some kind of traking. Like command bus side.

**Comment by erjain** [comment]
Hi @1304654, Due to bandwidth and maintainability, we are keeping it a low priority. If you or anyone from the community want to give it a try we can review the approach and link it to the wiki. Since this is not an issue I am closing it, however, feel free to continue the conversation here.
