### ISSUE TITLE
docker-compose up command is running for which yml?

### ISSUE THREAD

**Issue by ngaisteve1** [dotnet/eShopOnContainers#1970]
![image](https://user-images.githubusercontent.com/21274590/189029450-ebf693e3-6b0e-48f7-851d-7085c3379a08.png)

When I run the "docker-compose up" command, which yml is actually running? There are a lot of yml file in src folder.

**Comment by erjain** [comment]
Hi @ngaisteve1, thanks for raising your query here. The `docker-compose.yml` file allows you to configure and document all your application's service dependencies (other services, cache, databases, queues, etc.). For more information, you can visit: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/multi-container-applications-docker-compose. Hope this helps, I am closing this issue, feel free to continue the conversation in case of more queries.
