### ISSUE TITLE
Unable to access to http://localhost/eshop-webstatus - 404 error

### ISSUE THREAD

**Issue by ngaisteve1** [dotnet/eShopOnContainers#1978]
I followed the steps in https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes to deploy it locally. 
 
I think I managed to get it all up.

![image](https://user-images.githubusercontent.com/21274590/191658218-c474fe9f-e989-4699-b12e-7f7a65542062.png)

But when I run http://localhost/eshop-webstatus, I got a 404 error.

![image](https://user-images.githubusercontent.com/21274590/191658321-6bc2c1d7-6dd1-4fbe-b3f2-bb56d498b428.png)

Anything which I miss out?

**Comment by erjain** [comment]
Hi @ngaisteve1, thanks for posting here. Try removing eshop and browse with the URL http://localhost/webstatus. Hope it helps.

**Comment by ngaisteve1** [comment]
@erjain , I still get the same error.

![image](https://user-images.githubusercontent.com/21274590/191699087-55cb07f6-8b0f-4cef-9c97-11769348a78d.png)

**Comment by erjain** [comment]
Hi @ngaisteve1, thanks for testing eShop and posting here. I have tested it completely using public images
`.\deploy-all.ps1 -imageTag linux-dev -useLocalk8s $true`
 and it is working for me. Attaching screenshot: 
![image](https://user-images.githubusercontent.com/87998741/192248140-1e2911b2-f035-4be2-8c2f-50a6bb537c9f.png)

![image](https://user-images.githubusercontent.com/87998741/192248389-ab4e1799-9337-4fc9-981e-d4b14777d2d6.png). Can you share any further logs?

**Comment by erjain** [comment]
Hi @ngaisteve1, I am closing this issue. However, feel free to continue the conversation in case of any more queries.
