### ISSUE TITLE
Build fails | commit 8438a6a | The command "npm install" exited with code 1

### ISSUE THREAD

**Issue by npagare** [dotnet/eShopOnContainers#1979]
Hello,

Build after updating dev branch to the latest commit [8438a6a - Merge pull request #1955 from teghoz/dev] is failing with the following error.

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "npm install" exited with code 1.	WebSPA	{path}\eShopOnContainers\src\Web\WebSPA\WebSPA.csproj	57	

Would you please help? 
Thank you.

---------
output my npm and node installs

npm -version
npm version                                                    pwsh  07:16:49 
{
  npm: '8.19.2',
  node: '16.17.0',
  v8: '9.4.146.26-node.22',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.7',
  openssl: '1.1.1q+quic',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022a',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

**Comment by erjain** [comment]
Hi @IoTFier, thanks for posting here. I have tested the application and it is working fine for me. Sometimes an error during startup can disturb the application deployment and entries in the databases.  Could you please clean up old docker images and build the docker images again?  - To build and run the app 
- Go to the `/src/` directory and first-time build without cache

```text
docker-compose build --no-cache
```
- then, run

```text
docker-compose up sqldata
```
- Once it's ready to accept the new connection, then you can bring up the other container by using the following command from a separate terminal window.

```text
docker-compose up
```
Hope it helps.

**Comment by erjain** [comment]
Hi @IoTFier, I am closing this issue, however, feel free to continue the conversation in case of more queries.
