### ISSUE TITLE
[K8S] - Ingress on / rewrites to WebMVC instead of WebSPA

### ISSUE THREAD

**Issue by kbeaugrand** [dotnet/eShopOnContainers#1982]
Hi, 

I found a small issue on the K8S deployment charts.
The default path (/), is rewriting the path to /webMVC instead of /webSPA.

I'm able to provide a PR for this issue soon...

**Comment by erjain** [comment]
Hi @kbeaugrand, thanks for testing the deployment and posting here. I have tested it completely and it is working for me. Attaching screenshot: 
![image](https://user-images.githubusercontent.com/87998741/192248140-1e2911b2-f035-4be2-8c2f-50a6bb537c9f.png)

![image](https://user-images.githubusercontent.com/87998741/192248389-ab4e1799-9337-4fc9-981e-d4b14777d2d6.png)

**Comment by kbeaugrand** [comment]
Sorry again, 

It was an old branch I tried to deploy. 
My bad.
