### ISSUE TITLE
Notification Service / Sending Emails

### ISSUE THREAD

**Issue by MattHartz** [dotnet/eShopOnContainers#1986]
Hi all,

Thanks for this documentation. It has inspired me in a lot of ways and is much appreciated.  I do have a question regarding the sample code for "SendEmailToCustomerWhenOrderStartedDomainEventHandler".

It seems off to me that this is planned to be a DomainEventHandler rather than an IntegrationEventHandler, only because if in-process you call a 3rd party service, and then committing the DB transaction fails, could still deliver an invalid email.

Would it be planned in this example, that maybe this domainhandler actually writes to some table in-process part of the transaction, and then another sub-system picks up  that record and calls 3rd party email service out-of-process?

Thanks for everything!

**Comment by erjain** [comment]
Hi @MattHartz, Thanks for your valuable suggestion. For sure this can be an additional enhancement and thus a new feature.  The purpose of this sample application is to provide a sample application showing how to use microservices and Docker containers plus showing multiple clients(WebMVC, WebSPA, etc). However, if you or anyone else want to work with such add-ons, and share the PRs, we are happy to review the PRs and can proceed with linking to our wiki pages. I am closing this issue as of now, however, feel free to continue the conversation here.
Thanks for your feedback and for taking the time to think about it. :)
