### ISSUE TITLE
WebSPA not building correctly via F5 in VS: Question

### ISSUE THREAD

**Issue by Cubelaster** [dotnet/eShopOnContainers#1987]
I have forked the project and pressed F5 from Visual Studio.
Build passed, Docker started, project was successfully run. 
MVC works, everything works as far as I can see, except for WebSPA project.  

The issue is the same (probably the same) as: [1821](https://github.com/dotnet-architecture/eShopOnContainers/issues/1821) and [5223](https://github.com/dotnet/aspnetcore/issues/5223)

![image](https://user-images.githubusercontent.com/14044616/194539674-612e0e1c-86d7-474f-8262-fbb82ba04e1b.png)

I understand what the error is: Basically Angular was not built (in time or at all) for Docker to create the image. 
This is my folder when I don't make any manual changes:   

![image](https://user-images.githubusercontent.com/14044616/194539855-401475ad-34c9-4686-bf1f-284deb98ed96.png)
Only assets are there. 

When I add the build:prod command on project build, everything works fine and the folder contains built angular app:
![image](https://user-images.githubusercontent.com/14044616/194540032-a158cd92-41b8-4e20-a3dd-a1cd9a54bd8d.png)
![image](https://user-images.githubusercontent.com/14044616/194540726-2e671ab4-9846-4a36-950f-a2f7f63ce72a.png)

So, from this it is obvious that when building via Docker Compose, WebSPA project is containerized without Angular part. 
If I'm correct about this, how can I remedy it correctly? 
I see that the Dockerfile has the section responsible for building Angular application but for whatever reason, it's not used/waited upon/something else? 
![image](https://user-images.githubusercontent.com/14044616/194540844-7c007eb3-c7f9-44c9-b047-f6a8117406e7.png)

I went through the wiki and set Release to WebSPA project but it's not affecting it in any way. 
I did not make any changes to the Dockerfile because node.js check is already contained in .csproj file and it should be redundant in Debug mode. Should it? 
Am I doing something wrong?
Am I even supposed to run Angular inside Docker when Debugging? 
Is the image able to use live reload like webpack? 
I understand the idea to build:prod and deploy but building Angular for Debug session is weird?

**Comment by erjain** [comment]
Hi @Cubelaster, thanks for trying on eShopOnContainers and posting here. There is a frequent error reported earlier, please refer to the link: https://github.com/dotnet-architecture/eShopOnContainers/wiki/Frequent-errors#webspa-project-doesnt-come-up-on-debug-mode-in-visual-studio-2019. Let me know if this helps you.

**Comment by erjain** [comment]
I am closing this issue, please feel free to reopen it in case you are looking for more help.
