### ISSUE TITLE
[Error] Deploying on M1 mac, show an error: Google.Protobuf.Tools cannot determine host OS and CPU

### ISSUE THREAD

**Issue by wy1207** [dotnet/eShopOnContainers#1990]
When I use `docker-compose build`, an error occurred: 
#47 3.022 /root/.nuget/packages/grpc.tools/2.34.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : Google.Protobuf.Tools cannot determine host OS and CPU. [/src/Services/Catalog/Catalog.API/Catalog.API.csproj]
#47 3.022 /root/.nuget/packages/grpc.tools/2.34.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : Use environment variables PROTOBUF_TOOLS_OS={linux|macosx|windows} and PROTOBUF_TOOLS_CPU={x86|x64} to try the closest match to your system. [/src/Services/Catalog/Catalog.API/Catalog.API.csproj]
#47 3.022 /root/.nuget/packages/grpc.tools/2.34.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : You may also set PROTOBUF_PROTOC to specify full path to the host-provided compiler (v3.5+ is required). [/src/Services/Catalog/Catalog.API/Catalog.API.csproj]

**Comment by erjain** [comment]
HI @wy1207, thanks for posting here. Please refer to the issue #1771.

And, In `Docker Desktop for Mac` :

- Clean up the existing docker images and data volumes using the **Clean/Purge data** feature.
- Under the **Resources/FILE SHARING** option right path is mounted. (You can delete the existing entry and add it back again)

Once the cleanup is done, then you need to rebuild the images for running that application. You can do that by using the following steps.

- You can go the directory `~/eShopOnContainers/src`
- Go to the `.env` file. 
- Choose the right DNS :
    Uncomment : 
       ```
        ESHOP_EXTERNAL_DNS_NAME_OR_IP=docker.for.linux.localhost
        ESHOP_STORAGE_CATALOG_URL=http://docker.for.linux.localhost:5202/c/api/v1/catalog/items/[0]/pic/
      ```
    and comment out :
       ```
         #ESHOP_EXTERNAL_DNS_NAME_OR_IP=host.docker.internal
         #ESHOP_STORAGE_CATALOG_URL=http://host.docker.internal:5202/c/api/v1/catalog/items/[0]/pic/
       ```
- Run the command `docker-compose build`
- And after that `docker-compose up`
- You should be able to access the `webmvc` app using `http://docker.for.linux.localhost:5100`

Hope this helps !

**Comment by wy1207** [comment]
Thank you so much! It helps a lot.
But another error occurred when explore "http://docker.for.mac.localhost:5100/" :
An unhandled exception occurred while processing the request.
InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)

**Comment by erjain** [comment]
Hi @wy1207, try using `ESHOP_EXTERNAL_DNS_NAME_OR_IP=docker.for.linux.localhost` in .env file. You can do that by using the following steps.

- You can go the directory `~/eShopOnContainers/src`
- Go to the `.env` file. 
- Choose the right DNS :
    Uncomment : 
       ```
        ESHOP_EXTERNAL_DNS_NAME_OR_IP=docker.for.linux.localhost
        ESHOP_STORAGE_CATALOG_URL=http://docker.for.linux.localhost:5202/c/api/v1/catalog/items/[0]/pic/
      ```
    and comment out :
       ```
         #ESHOP_EXTERNAL_DNS_NAME_OR_IP=host.docker.internal
         #ESHOP_STORAGE_CATALOG_URL=http://host.docker.internal:5202/c/api/v1/catalog/items/[0]/pic/
       ```

Sometimes an error during startup can disturb the application deployment and entries in the databases. Could you please clean up old docker images and build the docker images again? - To run the app 
- Go to the `/src/` directory

```text
docker-compose up sqldata
```
Once it's ready to accept the new connection, then you can bring up the other container by using the following command from a separate terminal window.

```text
docker-compose up
```

**Comment by wy1207** [comment]
@erjain Thank you so much.
