### ISSUE TITLE
deploy on k3s

### ISSUE THREAD

**Issue by wjkhappy14** [dotnet/eShopOnContainers#1991]
maybe  deploy  the all services on k3s  environment ！

**Comment by erjain** [comment]
Hi @wjkhappy14, thanks for posting here. This could be an exciting thing to do. I appreciate it, if you or someone else want to showcase it and share a PR, we can review the PR and link the same as a demonstration on our wiki page.

**Comment by erjain** [comment]
I am closing this issue as of now, however, please feel free to continue the conversation here.
