### ISSUE TITLE
Question: Why are we not using MassTransit?

### ISSUE THREAD

**Issue by MatheusXavier** [dotnet/eShopOnContainers#1992]
The [MassTransit library](https://github.com/MassTransit/MassTransit) provides some facilities when working with messages and events, but here at eShopOnContainers we build custom code for this, is there any specific reason for this approach?

**Comment by erjain** [comment]
Hi @MatheusXavier, thanks for your valuable suggestion. For sure this can be a good idea to include MassTransit library, the purpose of this sample application is just to provide a sample application showing how to use microservices and Docker containers plus showing multiple clients(WebMVC, WebSPA, etc). 

However, if anyone wants to work on the feature to add MassTransit library, we're open to accepting PRs or linking PRs to wiki pages (Pull Requests) from the community, as long as the PRs don't break the rest of the scenarios and client apps. I am closing this issue as of now, however feel free to continue the conversation here. 
Thanks for your feedback and for taking the time to think about it, of course. :)
