### ISSUE TITLE
no PersistentVolumeClaim for the  helm  chart of the catalog-api 

### ISSUE THREAD

**Issue by wjkhappy14** [dotnet/eShopOnContainers#1993]
when i deploy the all helm on k8s, all services are working ,but can  not show  pictures,
maybe  no PersistentVolumeClaim  for  the  catalog-api

**Comment by wjkhappy14** [comment]
sorry，i found   the docker  image   has alread include the Pics  Dir.
but   is  this not good?

**Comment by erjain** [comment]
HI @wjkhappy14, thanks for posting here. All images are present in catalog.api project in `Pics` folder. The purpose of this sample application is just to provide a sample application showing how to use microservices and Docker containers plus showing multiple clients(WebMVC, WebSPA, etc). I am closing this issue, please feel free to post here in case of any more queries.
