### ISSUE TITLE
Circuit breaker not working

### ISSUE THREAD

**Issue by bhupi-cloudeq** [dotnet/eShopOnContainers#2000]
Circuit breaker not working as laid out in this article.

https://learn.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-circuit-breaker-pattern

**Comment by erjain** [comment]
Hi @bhupi-cloudeq, thanks for posting here. Please visit the link: https://learn.microsoft.com/en-us/training/modules/microservices-resiliency-aspnet-core/ for implementing the Circuit-Breaker pattern. I am closing this issue as of now, please feel free to post here in case of more queries.
