### ISSUE TITLE
eShopOnContainers for linux amr64

### ISSUE THREAD

**Issue by odidev** [dotnet/eShopOnContainers#2002]
I tried building docker using docker-compose build for linux arm64 but it fails with following error:
```
/root/.nuget/packages/grpc.tools/2.34.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : Use environment variables PROTOBUF_TOOLS_OS={linux|macosx|windows} and PROTOBUF_TOOLS_CPU={x86|x64} to try the closest match to your system. [/src/Services/Ordering/Ordering.API/Ordering.API.csproj]
/root/.nuget/packages/grpc.tools/2.34.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : You may also set PROTOBUF_PROTOC to specify full path to the host-provided compiler (v3.5+ is required). [/src/Services/Ordering/Ordering.API/Ordering.API.csproj]
The command '/bin/sh -c dotnet publish --no-restore -c Release -o /app' returned a non-zero code: 1
```

I also tried to deploy  arm templates with ServiceBus, COSMOSDB, Redis and so on and the deployment was successful on azure but we don't have detailed explanation of how we can use it after the deployment on azure.

Could you please share your pointers regarding running eShopOnContainers for linux arm64.

**Comment by whitesiroi** [comment]
I've just tried it today and getting the same error.

MacBook Pro (16-inch, 2021)
Chip Apple M1 Pro

**Comment by odidev** [comment]
@whitesiroi, Please refer [comment](https://github.com/dotnet-architecture/eShopOnContainers/issues/1990#issuecomment-1296933385) and then try docker-compose build. 

@erjain, Could you please share your feedback for linux arm64. Thanks in advance!

**Comment by erjain** [comment]
Hi @odidev, thanks for raising your query and posting the [resolution ](https://github.com/dotnet-architecture/eShopOnContainers/issues/1990#issuecomment-1296933385)for the same. I hope it helped to resolve the issue. I am closing this issue as of now, however, feel free to continue the conversation if you are looking for more help.

**Comment by odidev** [comment]
Hi @erjain, I have already tried this but the issue was not resolved.
Also could you please share your feedback regarding arm templates. Thanks in advance!

**Comment by odidev** [comment]
@erjain, could you please share your feedback regarding arm templates. Thanks in advance!
