### ISSUE TITLE
npm install throw ERESOLVE in WebSPA  project

### ISSUE THREAD

**Issue by Broderick890** [dotnet/eShopOnContainers#2018]
Hi there! Error below:
PS G:\Test\eShopOnContainers\src\Web\WebSPA\Client> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @angular-devkit/build-angular@0.1102.19
npm ERR! Found: @angular/localize@10.2.5
npm ERR! node_modules/@angular/localize
npm ERR!   peer @angular/localize@"^10.0.0" from @ng-bootstrap/ng-bootstrap@8.0.4
npm ERR!   node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!     @ng-bootstrap/ng-bootstrap@"^8.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @angular/localize@"^11.0.0 || ^11.2.0-next" from @angular-devkit/build-angular@0.1102.19
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"~0.1102.14" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/localize@11.2.14
npm ERR! node_modules/@angular/localize
npm ERR!   peerOptional @angular/localize@"^11.0.0 || ^11.2.0-next" from @angular-devkit/build-angular@0.1102.19
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~0.1102.14" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See G:\Reference\Package\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     G:\Reference\Package\npm-cache\_logs\2022-12-12T06_48_36_947Z-debug-0.log

**Comment by Broderick890** [comment]
# npm resolution error report

2022-12-12T06:48:39.288Z

While resolving: @angular-devkit/build-angular@0.1102.19
Found: @angular/localize@10.2.5
node_modules/@angular/localize
  peer @angular/localize@"^10.0.0" from @ng-bootstrap/ng-bootstrap@8.0.4
  node_modules/@ng-bootstrap/ng-bootstrap
    @ng-bootstrap/ng-bootstrap@"^8.0.0" from the root project

Could not resolve dependency:
peerOptional @angular/localize@"^11.0.0 || ^11.2.0-next" from @angular-devkit/build-angular@0.1102.19
node_modules/@angular-devkit/build-angular
  dev @angular-devkit/build-angular@"~0.1102.14" from the root project

Conflicting peer dependency: @angular/localize@11.2.14
node_modules/@angular/localize
  peerOptional @angular/localize@"^11.0.0 || ^11.2.0-next" from @angular-devkit/build-angular@0.1102.19
  node_modules/@angular-devkit/build-angular
    dev @angular-devkit/build-angular@"~0.1102.14" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "edge": {
    "type": "peerOptional",
    "name": "@angular/localize",
    "spec": "^11.0.0 || ^11.2.0-next",
    "error": "INVALID",
    "from": {
      "name": "@angular-devkit/build-angular",
      "version": "0.1102.19",
      "location": "node_modules/@angular-devkit/build-angular",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "dev",
          "name": "@angular-devkit/build-angular",
          "spec": "~0.1102.14",
          "from": {
            "location": "G:\\Test\\eShopOnContainers\\src\\Web\\WebSPA\\Client"
          }
        }
      ]
    }
  },
  "dep": {
    "name": "@angular/localize",
    "version": "11.2.14",
    "whileInstalling": {
      "name": "@angular-devkit/build-angular",
      "version": "0.1102.19",
      "path": "G:\\Test\\eShopOnContainers\\src\\Web\\WebSPA\\Client\\node_modules\\@angular-devkit\\build-angular"
    },
    "location": "node_modules/@angular/localize",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "peerOptional",
        "name": "@angular/localize",
        "spec": "^11.0.0 || ^11.2.0-next",
        "error": "INVALID",
        "from": {
          "name": "@angular-devkit/build-angular",
          "version": "0.1102.19",
          "location": "node_modules/@angular-devkit/build-angular",
          "isWorkspace": false,
          "dependents": [
            {
              "type": "dev",
              "name": "@angular-devkit/build-angular",
              "spec": "~0.1102.14",
              "from": {
                "location": "G:\\Test\\eShopOnContainers\\src\\Web\\WebSPA\\Client"
              }
            }
          ]
        }
      }
    ]
  },
  "current": {
    "name": "@angular/localize",
    "version": "10.2.5",
    "location": "node_modules/@angular/localize",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "peer",
        "name": "@angular/localize",
        "spec": "^10.0.0",
        "from": {
          "name": "@ng-bootstrap/ng-bootstrap",
          "version": "8.0.4",
          "location": "node_modules/@ng-bootstrap/ng-bootstrap",
          "isWorkspace": false,
          "dependents": [
            {
              "type": "prod",
              "name": "@ng-bootstrap/ng-bootstrap",
              "spec": "^8.0.0",
              "from": {
                "location": "G:\\Test\\eShopOnContainers\\src\\Web\\WebSPA\\Client"
              }
            }
          ]
        }
      }
    ]
  },
  "peerConflict": {
    "current": {
      "name": "@angular/localize",
      "version": "10.2.5",
      "location": "node_modules/@angular/localize",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "peer",
          "name": "@angular/localize",
          "spec": "^10.0.0",
          "from": {
            "name": "@ng-bootstrap/ng-bootstrap",
            "version": "8.0.4",
            "location": "node_modules/@ng-bootstrap/ng-bootstrap",
            "isWorkspace": false,
            "dependents": [
              {
                "type": "prod",
                "name": "@ng-bootstrap/ng-bootstrap",
                "spec": "^8.0.0",
                "from": {
                  "location": "G:\\Test\\eShopOnContainers\\src\\Web\\WebSPA\\Client"
                }
              }
            ]
          }
        }
      ]
    },
    "peer": {
      "name": "@angular/localize",
      "version": "11.2.14",
      "whileInstalling": {
        "name": "@angular-devkit/build-angular",
        "version": "0.1102.19",
        "path": "G:\\Test\\eShopOnContainers\\src\\Web\\WebSPA\\Client\\node_modules\\@angular-devkit\\build-angular"
      },
      "location": "node_modules/@angular/localize",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "peerOptional",
          "name": "@angular/localize",
          "spec": "^11.0.0 || ^11.2.0-next",
          "error": "INVALID",
          "from": {
            "name": "@angular-devkit/build-angular",
            "version": "0.1102.19",
            "location": "node_modules/@angular-devkit/build-angular",
            "isWorkspace": false,
            "dependents": [
              {
                "type": "dev",
                "name": "@angular-devkit/build-angular",
                "spec": "~0.1102.14",
                "from": {
                  "location": "G:\\Test\\eShopOnContainers\\src\\Web\\WebSPA\\Client"
                }
              }
            ]
          }
        }
      ]
    }
  },
  "strictPeerDeps": false,
  "force": false,
  "isMine": true
}

**Comment by erjain** [comment]
Hi @JOECHAN890, thanks for posting here, I recommend please delete your local repository and then try again.
Also if you are trying to run the whole application, I have tested the application and it is working fine for me. Sometimes an error during startup can disturb the application deployment and database entries. Could you please clean up the old docker images and build the docker images again?  - To build and run the app 
- Go to the `/src/` directory and first-time build without cache

```text
docker-compose build --no-cache
```
- then, run

```text
docker-compose up sqldata
```
- Once it's ready to accept the new connection, then you can bring up the other container by using the following command from a separate terminal window.

```text
docker-compose up
```
I hope it helps.

**Comment by Broderick890** [comment]
Hi @erjain,  It works! Thank you very much!
