### ISSUE TITLE
npm install --force WebSPA.csproj

### ISSUE THREAD

**Issue by samzuercher** [dotnet/eShopOnContainers#2027]
It currently works, but I had troubles building "eShopOnContainers\src\Web\WebSPA\WebSPA.csproj": npm install could not find the file packages.json because there were different Angular versions.

Replacing "npm install" with "npm install --force" in the .csproj-file solved the issue.

#253
[https://github.com/dotnet-architecture/eShopOnContainers/wiki/06.-(Optional)-Setting-the-Web-SPA-application-up](url)

**Comment by erjain** [comment]
Hi @samzuercher, thanks for sharing your query. It was clear there were issues while installing the packages. Are you still facing the problem? 

Or, could you please clean up the old docker images and build the docker images again?  - To build and run the app 
- Go to the `/src/` directory and first-time build without cache

```text
docker-compose build --no-cache
```
- then, run

```text
docker-compose up sqldata
```
- Once it's ready to accept the new connection, you can bring up the other container by using the following command from a separate terminal window.

```text
docker-compose up
```

I hope it helps.

**Comment by samzuercher** [comment]
Hi @erjain 

As stated above, with the '--force' - switch it worked. I did not investigate further but assume that there libaries of different versions got installed, which of course is not too fine. But these could also be external dependencies.

I would keep the issue open in case others encounter the same problem and only start to investigate by then.

Concerning docker: the error was an msbuild error, not docker, the project could not be built in Visual Studio, because msbuild detected same libraries with different versions.

greetings,
Sam

**Comment by erjain** [comment]
HI @samzuercher, after testing it works as expected. Though we are parallelly working on upgrading the whole application packages. I am closing this issue since we can not keep the issue open for a long time. However, feel free to continue the conversation on this thread or reopen it in case of any further queries.
