### ISSUE TITLE
Login with Google in the microservice-based architecture

### ISSUE THREAD

**Issue by qui8t** [dotnet/eShopOnContainers#2034]
In the eshop example you have a dedicated service for identity (`Identity/Identity.Api`), which can be utilized by every service that requires identity, including UI. According, I design the following scenario.

- In a single-page webapp, the UI renders a `Signin with Google` button generated [as this](https://developers.google.com/identity/gsi/web/tools/configurator);
- When user clicks on this button, a pop-up opens and redirects the user to `GET https://identityapi/api/account/login`;
- The endpoint _challenges_ the user and redirects them to the Google login page;
- After user logs-in to their Google account, a callback is sent to `POST https://identityapi/api/account/callback`;
- The endpoint handles user log in, and returns user DTO to the UI, including setting the cookies;
- The UI then shows the user as logged-in using the DTO.

My questions: 

- Almost all the examples about social authNZ I find online, including [asp.net docs](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-7.0), and importantly, including the flow [Google explains](https://developers.google.com/identity/gsi/web/guides/personalized-button) (please see the following code that generates a button that when clicked, opens a pop-up and redirects to Google login page), implements the entire authN flow (challenge and callback) in the webapp. Hence, no redirection to dedicated identity service happens. Should I suppose those examples online exclude a dedicate identity service for simplicity, or the architecture I layout here is wrong (hence I am misunderstanding the eshop identity architecture).   

    ```
    <div id="g_id_onload"
         data-client_id="test"
         data-context="signin"
         data-ux_mode="popup"
         data-login_uri="localhost/callback"
         data-auto_prompt="false">
    </div>
    ```

- If the above architecture is correct, what am I missing in the [Google-generated login button](https://developers.google.com/identity/gsi/web/tools/configurator) that by-default redirects to Google login? I can use [`click_listener`](https://developers.google.com/identity/gsi/web/reference/js-reference#click_listener) to redirect to `GET https://identityapi/api/account/login`, but I am reading that as a hack, not a feature by design.

**Comment by erjain** [comment]
Hi @qui8t, thanks for sharing your query. Yes, they didn't include a dedicated Identity Service just for the sake of simplicity. I am not sure of the Google Login process, which requires Google Cloud registration and other processes. But here eShopOnContainers app delegates authentication and authorization concerns to an identity service that also serves as a Security Token Service (STS). The identity service is a containerized ASP.NET Core project that uses [IdentityServer 4](https://identityserver4.readthedocs.io/), a popular OpenID Connect and OAuth framework for ASP.NET Core. An alternative to hosting an STS is to use [Azure Active Directory](https://azure.microsoft.com/services/active-directory) (Azure AD). Azure AD offers identity and access management as a service. I hope it helps.

**Comment by qui8t** [comment]
Thank you @erjain. I understand your approach with IdentityServer4 and Azure Active Directory. However, I think we can responsibly appreciate the fact that using external libraries, specifically including IdentityServer4 is not an option for everyone.  Therefore, with all due respect, I think it is a miscalculated strategy to implement identity features in the framework but redirect everyone to paid/partner services with everyone question the community asks about AuthNZ. Login with Google is superficially explained [on this page](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-7.0); and, IMHO, `Login with Google` should not be treated as a corner case that cannot be implemented using the out-of-box functionality of framework so to justify the ASP.NET developer community's immediate redirect to paid services with every related question asked.

You have implemented a dedicated identity service (i.e., `Identity.API`) and left out an important piece of the puzzle:

https://github.com/dotnet-architecture/eShopOnContainers/blob/4596d7aa99f841206e486e910d20b525cd48daf2/src/Services/Identity/Identity.API/Controllers/AccountController.cs#L43-L46

How would implement this functionality, and leverage it in an SPA that implements [the Google-generated `Login with Google` button?](https://developers.google.com/identity/gsi/web/tools/configurator)

**Comment by erjain** [comment]
Thanks @qui8t, I really love the idea of Login with Google. The main purpose of this project is to provide a sample application showing how to use microservices and Docker containers plus showing multiple clients(WebMVC, WebSPA, etc), as of now we are only supporting IdentityServer4 for Identity service, due to bandwidth and maintainability. However, we are happy to review and accept a PR from the community on this. If you or anyone else wishes to work on this or capture the steps as a blog/article, please let us know on this thread, and we will be happy to link it to the wiki. Considering this is not a functional issue with the application, I am closing this ticket, however, please feel free to continue the conversation here in case of further queries.

**Comment by qui8t** [comment]
You provided incomplete examples, that can mislead and risk the time and investment of larger teams. If this is the set policy of the ASP.NET team, then [all misleading and incomplete docs such as this](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-7.0) should be removed because you do not supporting them at any capacity and only refer to paid libraries. 

I regret my decision having pushed an entire team to adopt ASP.NET, yet we're stuck on the login with such support.
