### ISSUE TITLE
Clean Branch Docker Compose Issue

### ISSUE THREAD

**Issue by thellebuyck** [dotnet/eShopOnContainers#2035]
I have cloned the main branch and am having an issue running `docker-compose build` I am getting some error messages along the way and I cannot complete the build process and then run this in my docker environment.  Can anyone advise on this?

 ERROR [eshop/webmvc:linux-latest build 42/42] RUN dotnet publish --no-restore -c Release -o /app
  => CANCELED [eshop/ordering.signalrhub:linux-latest build 42/42] RUN dotnet publish --no-restore -c Release -o   15.9s
 => CANCELED [eshop/locations.api:linux-latest build 42/42] RUN dotnet publish --no-restore -c Release -o /app    15.9s
 => CANCELED [eshop/basket.api:linux-latest build 42/42] RUN dotnet publish --no-restore -c Release -o /app       15.8s

**Comment by erjain** [comment]
HI @thellebuyck, thanks for posting here and sharing your query. Could you please clean up the old docker images and build the docker images again?  - To build and run the app 
- Go to the `/src/` directory and first-time build without cache

```text
docker-compose build --no-cache
```
- then, run

```text
docker-compose up sqldata
```
- Once it's ready to accept the new connection, then you can bring up the other container by using the following command from a separate terminal window.

```text
docker-compose up
```

Let us know if this works for you.

**Comment by erjain** [comment]
Hi @thellebuyck, I have tested this application and it is working fine for me, are you able to run eShop with the help of the above shared instructions?

**Comment by thellebuyck** [comment]
Using these steps, I am still not able to build and run eShop.  

I am receiving this in the output:
```
failed to solve: executor failed running [/bin/sh -c npm i npm@latest -g && npm update && npm install && npm run build:prod]: exit code: 1
PS C:\Development\github\eshopOnContainers\src> npm i npm@latest
```

**Comment by erjain** [comment]
There is an issue while installing npm packages. Sometimes an error during startup can disturb the application deployment. You should 
install NodeJs, 
Angular and 
run npm install in the src\Web\WebSPA\Client folder. After that, you can start with the information given in the above comment. I hope it helps.

**Comment by thellebuyck** [comment]
@erjain Thank you for the help.  That resolved it for me.
