### ISSUE TITLE
Web UI Notification 

### ISSUE THREAD

**Issue by kundansingh86** [dotnet/eShopOnContainers#2036]
If there is a requirement to send notifications to web UI from the backend services then how it can be defined in this architecture?

Consider an example, a product is in the cart of the customer and the price of that product being updated and basket service made an update in its database but how that change will be notified to customer on  the web in real-time without the page refresh?

**Comment by erjain** [comment]
Hi @kundansingh86, thank you for reaching out.

Please note that the eShopOnContainers is the reference application that focuses on the architectural pattern rather than on specific business logic. However, I believe you can refer to #1668, hopefully, this comment https://github.com/dotnet-architecture/eShopOnContainers/issues/1668#issuecomment-871478280 can throw some light. Let me know if it helps you.

**Comment by kundansingh86** [comment]
Thanks @erjain for your comment. I had a look to the #1668 but it didn't provide the solution that I was looking for. Like I mentioned, I need to notify the Web UI i.e. the end user when any price gets changed in a product. 

Should I subscribe the Web UI service to event "ProductPriceChangedIntegrationEvent" raised by catalog service? If I do so, will it match with the architecture that is currently being followed in this project?

**Comment by erjain** [comment]
Hi @kundansingh86, "ProductPriceChangedIntegrationEvent" can be used to update the prices. Though for more information, I am sharing some older discussions in regard to this. Please refer to the comment: https://github.com/dotnet-architecture/eShopOnContainers/issues/250#issuecomment-369919714 and https://github.com/dotnet-architecture/eShopOnContainers/issues/250#issuecomment-369988144. I hope it will be helpful to you.

**Comment by erjain** [comment]
Hi @kundansingh86, I am closing this issue, however, feel free to continue the conversation if you are looking for more help.

**Comment by kundansingh86** [comment]
Thanks @erjain for your help. I read through the conversation but still it doesn't answer my question. 

As per the architecture, the event bus is only communicating with back-end services and not with the front-end services, therefore if I consume the event "ProductPriceChangedIntegrationEvent" in the front-end service then will it not be a violation of  defined architecture.

**Architecture:** 
https://github.com/dotnet-architecture/eShopOnContainers/raw/dev/img/eShopOnContainers-architecture.png
