### ISSUE TITLE
Mistake in architecture.png, WebApp access to OrderingMicroservice

### ISSUE THREAD

**Issue by magals** [dotnet/eShopOnContainers#2040]
The picture showing the logic (eShopOnContainers-architecture.png) shows that communication between the WebApp and the OrderingMicroservice takes place through the Web-Shopping intermediate service.

But in fact, when we open the http://host.docker.internal:5100/ page, we get the product list directly from the OrderingMicroservice bypassing Web-Shopping. It turns out that the client application immediately accesses the microservice and the intermediate service, is this ideologically correct?

This confuses me, since I assumed that for clients you need to create a separate api service that can connect to several microservices

**Comment by ardalis** [comment]
I think the diagram shows the intended design. Communication from the client should ideally go through a BFF, rather than directly to the microservice.

**Comment by erjain** [comment]
I am closing this issue.
