### ISSUE TITLE
.NET 7 debug issues

### ISSUE THREAD

**Issue by Sensis04** [dotnet/eShopOnContainers#2041]
Hi everyone,

I hope it's fine that I opened a new issue despite already posting in #2010:

I'm not able to start the Net7 version of the application for debug via VS 2022 while a simple docker compose && docker up via CLI works as expected. There are only minor modification and updates to the packages. With the default Docker files via VS 2022 the error is

System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request. Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.

Updating the SPA dockerfile for development and adding

RUN apt-get update RUN apt-get -y install curl gnupg RUN curl -sL https://deb.nodesource.com/setup_17.x | bash - RUN apt-get -y install nodejs RUN npm install RUN npm -v

results in failed to solve: executor failed running [bin/sh -c npm install]: exit code: 254.

Does anybody have ideas how to resolve these errors for the updated version? I have tried deleting, rebuilt all images without caches, and switched between development and production for the SPA application.

**Comment by erjain** [comment]
Hi @Sensis04, thanks for posting your query here, we'll check on this and update you.

**Comment by Broderick890** [comment]
![image](https://user-images.githubusercontent.com/16652353/217530547-af345009-ccd6-42ef-9a8c-5049df598cda.png)
same issue, please help! Thank!

**Comment by erjain** [comment]
Strange, for me it is working fine at my end. Sometimes, there is a frequent error reported in the past, can you guys have a look at this: https://github.com/dotnet-architecture/eShopOnContainers/wiki/Frequent-errors#webspa-project-doesnt-come-up-on-debug-mode-in-visual-studio-2019. I hope it helps.

**Comment by erjain** [comment]
Hi @Sensis04, Are we good to close this issue?

**Comment by erjain** [comment]
I am closing this issue, however, feel free to continue the conversation or reopen it in case of further queries.
