### ISSUE TITLE
Databases not getting created while installing the Eshop application

### ISSUE THREAD

**Issue by rgandhi715** [dotnet/eShopOnContainers#2042]
I installed the eshop application on AKS cluster using the documentation provided on https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS)

However the Databses under SQL server were not created after installation.

Below are the logs for SQL-data containers:
Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'OrderingDb'
Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'IdentityDb'
Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'CatalogDb'
Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'WebhooksDb'

Then I created the all 4 Databases manually, then login and basket services started working. But the checkout services is throwing error:
<img width="927" alt="image" src="https://user-images.githubusercontent.com/65450546/216288253-9230f7ba-234f-4cb2-99a0-527617c3ed59.png">

Ordering API logs:
<img width="938" alt="image" src="https://user-images.githubusercontent.com/65450546/216288589-bf320ea1-8e18-4ccb-8c1f-097b9d64ff8e.png">

What are the steps to resolve this issue. And create databases while deploying the application?

**Comment by SumanHansada** [comment]
Hi, I have also encountered the same issue (in M1 Mac Laptops).
There seems to be problem with SQL server on Mac (M1) so I changed it to azure-sql-edge
The fix which worked was - 
In docker-compose.yml, docker-compose.windows.yml, docker-compose-tests.yml
Change the sqldata image-
sqldata:
    image: mcr.microsoft.com/azure-sql-edge:latest
    
Remove all containers - 
docker rm $(docker ps -aq)
Rebuild all containers - 
docker-compose build --no-cache
Run -
docker-compose up

**Comment by erjain** [comment]
Thank you so much @SumanHansada for testing eShop and sharing your experience. I hope it will help users.

**Comment by erjain** [comment]
Hi @ rgandhi715, Could you please let me know if you are able to resolve your issue with the above-shared instructions?

**Comment by rgandhi715** [comment]
Thank you @SumanHansada 

Yes I was able to resolve the issue by the solution provided by @SumanHansada 
Used Image: mcr.microsoft.com/azure-sql-edge:latest

**Comment by erjain** [comment]
Thank you so much @rgandhi715 for confirming. Thanks @SumanHansada. I am closing this issue now.
