### ISSUE TITLE
Not able to Use Azure Storage Account for catalog images

### ISSUE THREAD

**Issue by rgandhi715** [dotnet/eShopOnContainers#2047]
Are there any documents/steps available to use Azure Storage account for catalog API. I have tried passing the container endpoint URL in the Image along with the Storage account name and key. have also uploaded the images in Storage account. still not loading the images.

I am deploying the application on AKS.
<img width="719" alt="image" src="https://user-images.githubusercontent.com/65450546/217804798-09cef35b-9d90-4f00-a556-8ad908434017.png">

**Comment by erjain** [comment]
Hi @rgandhi715, thanks for testing eShop and sharing your query here. You can follow below steps :

Change the value of the below variable to `True`:
https://github.com/dotnet-architecture/eShopOnContainers/blob/7cf90e06fd9c00c0233d824242a09f34877dcc4e/src/Services/Catalog/Catalog.API/appsettings.json#L16

https://github.com/dotnet-architecture/eShopOnContainers/blob/7cf90e06fd9c00c0233d824242a09f34877dcc4e/src/docker-compose.prod.yml#L49

https://github.com/dotnet-architecture/eShopOnContainers/blob/7cf90e06fd9c00c0233d824242a09f34877dcc4e/src/docker-compose.override.yml#L94

Then comment below line:
https://github.com/dotnet-architecture/eShopOnContainers/blob/7cf90e06fd9c00c0233d824242a09f34877dcc4e/src/.env#L9

Uncomment the below line and configure this value to the cloud storage locations URL(https://xxxxxxxx.blob.core.windows.net/pics/):
https://github.com/dotnet-architecture/eShopOnContainers/blob/7cf90e06fd9c00c0233d824242a09f34877dcc4e/src/.env#L20


Let me know if this helps.

**Comment by erjain** [comment]
We have also captured the process in the wiki section on page [Using-Azure-resources](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Using-Azure-resources#azure-storage-account-service). I am closing this issue right now, but please feel free to continue the conversation if you want more help.
