### ISSUE TITLE
i can not login by browser - invalid request, how to do it by postman?

### ISSUE THREAD

**Issue by refaeldimri** [dotnet/eShopOnContainers#2063]

**Comment by erjain** [comment]
Hi @refaeldimri, thank you for posting your query here. To run the application you can refer to the instructions on the wiki page, [build-and-deploy-eshoponcontainers]( https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#build-and-deploy-eshoponcontainers). I am closing this issue now, however, feel free to continue the conversation if you are looking for more help.
