### ISSUE TITLE
WebSPA: An unhandled exception occurred while processing the request.

### ISSUE THREAD

**Issue by cosmic-flood** [dotnet/eShopOnContainers#2081]
I followed the instructions in the [Windows setup guide](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup) to run eShopOnContainers with Docker Compose on Windows 11. After starting the Docker containers, the MVP service at `http://host.docker.internal:5100/` worked as expected.

![image](https://user-images.githubusercontent.com/68597908/230597626-3e0f1f78-4dd4-4eee-b409-ab0e81c1a3fd.png)

However, I encountered errors with the WebSPA service. I suspect there might be a Node.js version incompatibility between the Dockerfile configuration and the WebSPA's config file.

![image](https://user-images.githubusercontent.com/68597908/230599884-cc8cb61e-a534-48f0-bfc3-df69670eab5c.png)

Please help me resolve this issue, and let me know if you require any additional information or logs to investigate the problem.

**Comment by erjain** [comment]
Hi @cosmic-flood, thanks for sharing your query here. you can refer to the link: https://github.com/dotnet-architecture/eShopOnContainers/issues/2062#issuecomment-1477834665. 

You have to install the latest version of npm and node. Please ensure you have the latest or below version installed: 
```
PS C:\Users\xxxxxx> npm -v
9.5.1
PS C:\Users\xxxxx> node -v
v16.13.2
```

**Install n**
`npm install -g n`
You'll need to install this package globally as it manages the Node versions at the root.

Install a new version of Node
```
n lts
```

**How to Update NPM?
Just as you use NPM to update packages, you can use NPM to update itself. Here's the command to achieve this:**

`npm install -g npm@latest`

I hope it helps.

**Comment by cosmic-flood** [comment]
> 

Hi @erjain , thanks for the reply. I updated my NodeJs and NPM version. 

![image](https://user-images.githubusercontent.com/68597908/230626246-6322f398-77d4-48f1-909c-373a306b4670.png)

I got another error now:

![image](https://user-images.githubusercontent.com/68597908/230626515-70fe0b06-64e9-4c63-85ca-2be12e4b1dce.png)
