### ISSUE TITLE
I think it's time to upgrade to .NET 7 :)

### ISSUE THREAD

**Issue by ravichigurupalli** [dotnet/eShopOnContainers#2096]
with .NET 7...It's entirely native, with no IL or JIT, and provides fast startup time and a small, self-contained deployment.

**Comment by erjain** [comment]
Hi @ravichigurupalli, thanks for posting here. We have already upgraded this project to .NET 7. Are you seeing any miss in any service which doesn't have .NET 7?

**Comment by ravichigurupalli** [comment]
hoo yes, I posted in other project did same thing, sorry to bother you, let me close this.
