### ISSUE TITLE
Node 12 warnings

### ISSUE THREAD

**Issue by abrahamberg** [dotnet/eShopOnContainers#2120]
Hello 
There is a warning annotated to most of workflow runs : 

> **Warning**
> 
>Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

I created a PR for it long ago, I appreciate if someone can approve it.
#2090

**Comment by jamesmontemagno** [comment]
Thanks for the PR, will have @SrushtiPasari94  look at it now

**Comment by SrushtiPasari94** [comment]
@abrahamberg @jamesmontemagno  [This PR 2090](https://github.com/dotnet-architecture/eShopOnContainers/pull/2090) has merged.
