### ISSUE TITLE
 CORS-related errors when loading SPA version of web app

### ISSUE THREAD

**Issue by ngaisteve1** [dotnet/eShopOnContainers#2121]
I cloned the dev branch and followed the instructions to build and run the project using Docker Compose. After running `docker-compose build` and `docker-compose up`, health checks indicate that all services are healthy.

![webstatus](https://github.com/dotnet-architecture/eShopOnContainers/assets/21274590/db290318-ed23-4d49-96bd-bdc3d3ea1c1e)

The MVC version of the web app is functioning correctly, but I encountered CORS-related errors when trying to load the SPA version. This issue is likely due to Cross-Origin Resource Sharing (CORS) restrictions.

![webmvc](https://github.com/dotnet-architecture/eShopOnContainers/assets/21274590/428cfcb0-a573-47ec-9ada-d5d2529015d8)

![webspa](https://github.com/dotnet-architecture/eShopOnContainers/assets/21274590/0a8fdccb-816b-4c1e-b27c-80ec3ade5df7)

I would appreciate guidance on how to configure the necessary CORS settings to resolve this issue. Please provide instructions or suggestions on how to modify the project's configuration files or any other relevant steps to enable proper CORS handling for the SPA version of the web app.

Thank you for your assistance.

Please feel free to adjust the content as needed.

**Comment by davidfowl** [comment]
Likely broken in the major refactoring that we're doing. Will take a look.
