### ISSUE TITLE
Explicit reference to Duende.IdentityServer.EntityFramework.Storage not required

### ISSUE THREAD

**Issue by Pepsi1x1** [dotnet/eShopOnContainers#2131]
https://github.com/dotnet-architecture/eShopOnContainers/blob/06d5164532902a076813894c965d6c99122d39f2/src/Services/Identity/Identity.API/Identity.API.csproj#L12

Is this explicit reference required? It’s an implicit dependency of Duende.IdentityServer.EntityFramework

**Comment by jamesmontemagno** [comment]
Agreed, @vSrushtiPasari94 you can remove this and send a PR

**Comment by SrushtiPasari94** [comment]
Dependency removed.
