### ISSUE TITLE
Implement Integration events between multiple microservices

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/eShopOnContainers#32]
Implement Event-Driven communication between microservices/containers based on Event-Bus interfaces and any simple inter-process communication implementation (That implementation could be swapped by any more advanced Service Bus, like Azure Service Bus using Topics) Integration Events.

Integration events could be raised after handling Domain Events as part of the Domain Events "side effects".

IMPORTANT: Need to tackle resilient publish, so how to avoid that data is not consistent if after updating data locally the network or Event Bus fails when trying to publish.
See links like: https://docs.particular.net/nservicebus/azure/ways-to-live-without-transactions

**Comment by eiximenis** [comment]
We use now RMQ for integration events between services, so I think that could be closed :)
/cc @CESARDELATORRE

**Comment by CESARDELATORRE** [comment]
Closing. We already implemented this feature.
