### ISSUE TITLE
Review/Refactor CreateOrderCommandHandler

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/eShopOnContainers#34]
Looks like this code has BUGs and is not consistent to a regular Ordering Business Domain:

1. It is always Adding a new Buyer?, no matter if it was found or not in the database the following line is called:
 _buyerRepository.Add(buyer);
Looks like that internally it might not be adding it because it adds it only if the entity is transient:
if (buyer.IsTransient())
            {
                return _context.Buyers
                    .Add(buyer)
                    .Entity;
            }
But in any case, it doesn't look good in the code. The Ubiquitous Language here is wrong. "Add" should means only Add"... and the validation should occur only in collateral cases.
Or change the method name to **_buyerRepository.AddIfNotExists(buyer);** ...
Might need to discuss this topic. 

2. We have a similar issue right after that, when adding the PaymentMethod to the Buyer.
I think that it should be more explicit here. Internally, the buyer.AddPaymentMethod() is not adding it if the PayMentMethod Value-Object already exists in the DB, but I think it should be explicit in the Command Handler logic... Or change the method name to buyer.**AddPaymentMethodIfNotExists**()...
Might need to discuss this topic.

3. We might want to use Domain Events here in order to chain the two aggregates' transactions so this CommandHandler would update a single Aggregate, the Order Aggregate.

 
BELOW IS THE CURRENT CODE (Which I don't like much, needs to evolve):

    public class CreateOrderCommandHandler
        : IAsyncRequestHandler<CreateOrderCommand, bool>
    {
       //.......
        public async Task<bool> Handle(CreateOrderCommand message)
        {
            //find buyer/payment or add a new one buyer/payment 

            var buyer = await _buyerRepository.FindAsync(message.BuyerFullName);

            if (buyer == null)
            {
                buyer = new Buyer(message.BuyerFullName);
            }

            var payment = buyer.AddPaymentMethod(message.CardTypeId,
                $"Payment Method on {DateTime.UtcNow}",
                message.CardNumber,
                message.CardSecurityNumber,
                message.CardHolderName,
                message.CardExpiration);

            _buyerRepository.Add(buyer);

            await _buyerRepository.UnitOfWork
                .SaveChangesAsync();

            //create order for buyer and payment method

            var order = new Order(buyer.Id, payment.Id, new Address(message.Street, message.City, message.State, message.Country, message.ZipCode));

            foreach (var item in message.OrderItems)
            {
                order.AddOrderItem(item.ProductId, item.ProductName, item.UnitPrice, item.Discount, item.PictureUrl, item.Units);
            }

            _orderRepository.Add(order);

            var result = await _orderRepository.UnitOfWork
                .SaveChangesAsync();

            return result > 0;
        }

**Comment by kifjj** [comment]
In my view, the CreateOrderCommandHandler should be the aggregate and its operations  1) create buyer  2) add payment method, 3) add items, should be done in memory. At the end, order should be passed to the CreateOrderRepository which together with buyerRepository would persist what is needed in a single transaction. 

Question, how to implement a single tx accross 2 or more repositories?

Anyway, my idea would be something like:

`CreateOrderCommandHandler.Handle(order)
{
	var buyer = new Buyer(buyerGuid);
	buyer.PaymentMethod.Add(....)
	
	var order = new Order(buyer, ....);

        foreach (var item in message.OrderItems)
        {
            order.AddOrderItem(item.ProductId, item.ProductName, item.UnitPrice, item.Discount, item.PictureUrl, item.Units);
        }

	_createOrderRepository.SaveOrder(order)
}

CreateOrderRepository.SaveOrder(order)
{	
	var buyer = _buyerRepository.AddIfNotExists(order.Buyer); 
		
	order.buyerId = buyer.id;	
	order.patymentId = buyer.PaymentMethodId;
	
	_orderRepository.Save(order); //this should be in tx with _buyerRepository.AddIfNotExists
}

BuyerRepository.AddIfNotExists(buyerToAdd)
{
 	   var buyer = await _buyerRepository.FindAsync(buyerToAdd.buyerGuid);

            if (buyer == null)
            {
                buyer = new Buyer(buyerToAdd.buyerGuid);
            }

            var payment = buyer.AddPaymentMethod(cardTypeId,
                $"Payment Method on {DateTime.UtcNow}",
                message.CardNumber,
                message.CardSecurityNumber,
                message.CardHolderName,
                message.CardExpiration);

            _buyerRepository.Add(buyer);

            await _buyerRepository.UnitOfWork.SaveChangesAsync();
}
`

**Comment by CESARDELATORRE** [comment]
Initially, you shouldn't include several repositories within the same transaction. Sometimes you could, but as a "by default rule", you shouldn't because that means you are including multiple Aggregates within the same transaction. You should try to avoid that case and do it only under exceptional cases.
Reasons:

- A repository should handle persistence related to a single Aggregate.
- Aggregates should normally be defined/identified based on the transactions. An Aggregate is a consistency boundary and usually a transaction boundary, as well. 
- If you think that based on you concrete Domain's requirements you'd need to have a transaction across multiple Aggregates, maybe you didn't define those aggregates correctly for your concrete Domain's business requirements and they should be shaped as a single Aggregate. In this case, the Order could be an child entity of the Buyer Aggregate, then.

It all depends on your concrete Business Domain's requirements.
In our case, we want to show an example of several Aggregates within the Ordering microservice, so our consistency and transaction boundaries (because we want our Domain's requirements that way) is just about the Order on one hand and the Buyer on the other.
Basically, in our hypothetical Domain it doesn't make sense to update an OrderLine by itself, that's why it is part of the Order Aggregate. However, in our concrete and hypothetical Domain, we could want to update an Order independently of the Buyer, or viceversa, so they could be treated in different transactions. That's why we created two separate Aggregates.
Ultimately, we want to show how to communicate several aggregates through Domain Events, that the ultimately reason why our Domain is "thought" like that.

So, there are not right/wrong aggregate definitions. It depends on your concrete Business Domain.
In our Domain "we want to show two separate Aggregates" as an example, so our hypothetical business domain requirements wouldn't require Buyer and Order to have single atomic transactions between them.
In a real project, it would be vice versa. You get the Domain Experts' requirements and model based on that. But for a sample app, we can shape the domain requirements as we'd prefer, we are the domain experts in this case and we define our Domain as we prefer, right? 

If in your concrete domain you need to have transactional consistency between Buyer and Order, then, create a single Aggregate: Buyer, and add stuff to the orders through the Buyer AggregateRoot methods. And have a single Repository for the Buyer Aggregate.

In regards the way we're building it, the current code at CreateOrderCommandHandler was temporal and wrong. We're need to refactor it by using Domain Events in order to connect the Order to the Buyer. That's why I created this issue time ago.
We'll have that code implemented soon, hopefully.

Thoughts?

**Comment by CESARDELATORRE** [comment]
Closing this issue. We refactored the CreateOrderCommandHandler and decoupled the operations between multiple Aggregates with the Domain Events.
