### ISSUE TITLE
A Command Handler should directly affect one single aggregate... Use Domain Events here?

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/eShopOnContainers#37]
Explained below, however, I'm not sure I agree on this rule...
An Aggregate is a consistency boundary, but that consistency can be achieved as part of a larger transaction involving multiple aggregates within the whole Command-Handler's task... 
In any case, this is something to consider and discuss here plus the advanced solution can be part of a new feature for next sprints. 
In any case, this issue is related to this: 
https://github.com/dotnet/eShopOnContainers/issues/34
The CommandHandler has to be reviewed, looks like it has domain logic Bugs explained in issue #34 ..

In a different page, for this issue, I mean the following:
According to http://cqrs.nu/Faq/command-handlers 
"**A command handler should only directly affect one aggregate.**"

We are updating two Aggregates in the CreateOrderCommandHandler:
The Order aggregate and the Buyer aggregate:
https://github.com/dotnet/eShopOnContainers/blob/migration/net11/src/Services/Ordering/Ordering.API/Application/Commands/CreateOrderCommandHandler.cs

**When implementing DOMAIN EVENTS, this could be a good case for raising an event and create or update a Buyer if it needs to be done.**

(In this thread however some folks are ok with affecting multiple Aggregates from the same Command Handler...): https://groups.google.com/forum/#!topic/dddcqrs/vX8Zd6Si1-E 

See these discussions, too:
https://groups.google.com/forum/#!topic/dddcqrs/UYXXR4iU8f4 
http://stackoverflow.com/questions/23324713/should-the-rule-one-transaction-per-aggregate-be-taken-into-consideration-when

**Comment by davasquez-newshore** [comment]
[Feedback] As I understood, the whole idea behind Aggregates as consistency boundaries is to make them able to change independently from each other. 

Using sagas and compensating actions allow the process to scale, cause surely a transaction across two aggregates would be achieved, but with any further logic added on the process it will start to be harder to evolve.

In my experience, it is worth to model each process with more than an aggregate involved as a saga. Enforces SRP and usually also helps to better  discover new concepts e.g. in the forum discussion, the Transfer aggregate) or border cases while modeling compensations. And when you really find that two aggregates MUST be changed using one transaction, probably means that those aggregates should be only one.

**Comment by CESARDELATORRE** [comment]
I partially agree, but those same principles also apply to independent aggregates communicating by Domain events. IMHO, Sagas target additional scenarios more like long running processes and workflows.
You should be able to just use Domain Events to "connect" multiple aggregates within your Domain Model without needing to use Sagas.
It is just a different way. Using Sagas for this scenario is right and probably safer but could also be overkill. For this case, I think that using just domain events is simpler and good enough for many scenarios dealing with multiple aggregates within the same Domain. 

I mean approaches like this, where you are not going so far and using Sagas:
https://lostechies.com/jimmybogard/2014/05/13/a-better-domain-events-pattern/ 

It is a matter of business requirements. If you need a safer approach, it should be done with a Saga.
To me it is like "How many 9 do you want for your system", depending on that you'd need more or less infrastructure complexity for HA. That case is comparable.

Btw, we will implement a Saga for the Ordering microservice. That scenario deserves it. :)

**Comment by davasquez-newshore** [comment]
Agree with the idea of simplifying avoiding a canonical saga in a simple process. I think the decision should be driven not by how many aggregates are involved, but if you need to keep state across the process and if you can guarantee that order of events are well known or not important.

 Btw, The article you point is  _exactly_ what I meant on other post about "A list of events in the aggregate to be dispatched (published) later". It is kinda standard implementation though.
