### ISSUE TITLE
Scenario for Domain Events: Compare Basket Items price vs. Catalog-Product price when converting from Basket to Order

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/eShopOnContainers#38]
Compare Basket Items price vs. Catalog-Product price when converting from Basket to Order.
If the price changed in the Product from the Catalog, the Order has to have that new price reflected in the "Pre-Order page", but it has to also show a message saying "Warining, the original price was XXXX, but it has changed to XXXX since you added the product to your basket".
Implement this with Domain EVENTS starting when the basket is being converted to an Order.

**Comment by dsrodenas** [comment]
Implemented and merged toDev branch with **Integration events**.

**Comment by CESARDELATORRE** [comment]
Feature done. Closing this issue.
