### ISSUE TITLE
Test Xamarin app in VS 2017 and consuming the local Docker microservices

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/eShopOnContainers#53]
This is a testing reminder for the team. Something might be missing after this migration to VS 2017, hopefully not.. In any case, please, test it and confirm if it is working properly with VS 2017

**Comment by CESARDELATORRE** [comment]
The Xamarin app connects good from a real Android mobile device (in my case testing with a Google Pixel XL) to the microservices running in the Docker Host. It is able to authenticate, too.
However, I found to important issues to fix:
1. Product images are not shown in the list of products of the Xamarin app runnin in the device, just a "by default" eShop logo instead, like if it doesn't find the images.
2. The Order process (checkout) throws an error when trying to checkout from the basket.

Let's fix it. This was working in previous versions...

**Comment by CESARDELATORRE** [comment]
It is almost working now agains the "prod" environment:
https://github.com/dotnet/eShopOnContainers/blob/master/docker-compose.prod.yml

Just the Order Checkout is failing then consuming the remote microservices. Might be due to any breaking change in the Ordering.API. Will fix this tomorrow.

**Comment by eiximenis** [comment]
Order checkout is fixed in commit c3444287ec9ce02e92a91114a05768a473a2e75e
@CESARDELATORRE review & close if appropiate :)
