### ISSUE TITLE
Full eShopOnContainers.sln solution is not updated with the new Docker for VS 2017 config

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/eShopOnContainers#55]
The full eShopOnContainers.sln solution is not updated with the new Docker for VS 2017 config:
see:
![eshoponcontainers-full-solution-missing-docker-vs-2017](https://cloud.githubusercontent.com/assets/1712635/23109779/caf9767e-f6d0-11e6-94f9-553edb01dd1e.PNG)

Please, update that golbal solution so it shows the new docker in VS 2017 configuration.

Also, (related to issue https://github.com/dotnet/eShopOnContainers/issues/53) test the Xamarin app consuming the local microservices in Docker for Windows by deploying the Xamarin app in the old VS Android emulator instead of the newer Google Android emulator which is NOT compatible with Hyper-V and Docker for Windows.

**Comment by eiximenis** [comment]
Fixed in commit 7254710184d33a4a7f829b89d0c5359ca51f2a07

Please @CESARDELATORRE review ;)

**Comment by CESARDELATORRE** [comment]
This is fixed. Re-open if needed.
