### ISSUE TITLE
In MVC app, the Identity.API STS cannot be reached after the latest changes in docker-compose.yml

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/eShopOnContainers#60]
Here's the issue happening in the MVC app when trying to login.
It is configured as  - IdentityUrl=http://identity.api:5105 , that's why it cannot reach it from the browser.
![error_identity_api](https://cloud.githubusercontent.com/assets/1712635/23242015/8c109872-f92b-11e6-8a30-1f7751c9d8cd.png)

If changing to IdentityUrl=http://localhost:5105 it doesn't work neither, as it throws this error:
![error_identity_api_2](https://cloud.githubusercontent.com/assets/1712635/23242265/af491fd4-f92c-11e6-83cd-443eb8c9ab7e.png)

**Comment by aqueenan** [comment]
That doesn't seem to fix the problem.

The MVC container can access http://identity.api:5105:

```
# curl http://identity.api:5105
<!DOCTYPE html>
<html>
...
```

It cannot connect to http://10.0.75.1:5105 though:

```
# curl -v http://10.0.75.1:5105
* Rebuilt URL to: http://10.0.75.1:5105/
* Hostname was NOT found in DNS cache
*   Trying 10.0.75.1...
* connect to 10.0.75.1 port 5105 failed: Connection timed out
* Failed to connect to 10.0.75.1 port 5105: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to 10.0.75.1 port 5105: Connection timed out.
```

The container is not in the 10.0.75.0 bridge subnet - it is in a bridge set up by Docker Compose. The IP address of the container is 172.18.0.5. http://172.18.0.1:5105 works correctly from inside the container, but is not visible to the Windows host.

As a workaround I can use the IP address of the host.
