### ISSUE TITLE
Suggestion: ViewModels folder

### ISSUE THREAD

**Issue by ardalis** [dotnet/eShopOnContainers#67]
Many, but not all, of the classes in the WebMVC/Models folder are actually ViewModels. Consider creating a root-level ViewModels folder and moving all of the ViewModel types to it.
https://github.com/dotnet/eShopOnContainers/tree/master/src/Web/WebMVC/Models

Also be consistent about using a ViewModel suffix with these types. If they're in a ViewModels folder/namespace I would not then also use a suffix.

**Comment by CESARDELATORRE** [comment]
Closing.
