### ISSUE TITLE
Sign out crashes

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/eShopOnContainers#80]
This feature was working ok previously, not sure when we had this regression bug.
Anyways, when trying to Sign out the app is crashing. see:
![eshoponcontainers_logout_error](https://cloud.githubusercontent.com/assets/1712635/23637123/9311ed1c-028e-11e7-84b5-15af0fecad0b.PNG)

Need to fix this.

**Comment by dsrodenas** [comment]
Issue fixed on Comit 1b6ff6cb20470fc111a62c3cd8d0850e5d9cde41
Master branch since it is a crash and the solution is only to modify one wrong uri in the config.
