### ISSUE TITLE
Login page has no styles and images when deploying from the CLI

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/eShopOnContainers#81]
The Login page has no styles and images when deploying from the CLI.
Somehow, styles and or/images are not being included when building/deploying from the CLI.
However, when deploying from VS 2017, the page looks ok.
See the login page when deployed from the CLI:

![eshoponcontainers_login_page_no_styles](https://cloud.githubusercontent.com/assets/1712635/23638534/1017ff60-0297-11e7-9114-f0ee67c080a4.png)

**Comment by eiximenis** [comment]
Fixed in commit 39d4280b314f4c67e8be2079439cb899c0d8fa5e

**Comment by CESARDELATORRE** [comment]
Closing. This is fixed.
