### ISSUE TITLE
no branch with name vs2017

### ISSUE THREAD

**Issue by mstechies** [dotnet/eShopOnContainers#93]
In the setup instructions it is mentioned to clone from branch vs2017, however no such branch exists.

**Comment by BillWagner** [comment]
@mstechies Thanks for pointing this out  We'll fix the notes.  The correct choice is to use the 'master' branch. (Everything from the vs2017 branch has been merged into master).

**Comment by CESARDELATORRE** [comment]
Right, that was from the previous setup using the vs2017 branch.
You can use the master branch. 
Fixed now in the wiki.
Thanks for catching that! :)
Closing this issue now.
