### ISSUE TITLE
Typo in document "architecting-and-developing-containerized-and-microservice-based..." | Section: The new world: multi Architectural Patterns and polyglot microservices

### ISSUE THREAD

**Issue by thepill** [dotnet/eShopOnContainers#95]
There is a typo on page 71:

`- Simple CRUD, single Tier, sinle Layer`

should be 

`- Simple CRUD, single Tier, single Layer`

PS: Great work!

**Comment by davidfowl** [comment]
@thepill pull request?

**Comment by thepill** [comment]
@davidfowl where can i get the non-pdf-Version to edit it :)?

**Comment by davidfowl** [comment]
lol oops

**Comment by thepill** [comment]
Found another one. Is there a better place to mention this?

**Comment by BillWagner** [comment]
@thepill This is the best place to mention these at this time.

**Comment by thepill** [comment]
@BillWagner Ok. Should i open separate issues for each typo?

**Comment by BillWagner** [comment]
@thepill I don't have a strong preference, but I think it would save us all time to bundle them in batches. I'll suggest one issue per section. 

The main thing is to make sure we fix them. Thank you for bringing them to our attention.

**Comment by CESARDELATORRE** [comment]
@thepill Thanks for the feedback! :)
I just fixed the typo at the original WORD document. I'll be updated along with more updates in a few days when I update a new version of the .PDF
