### ISSUE TITLE
wiki error

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/eShopOnContainers#96]
Please check the wiki documentation, as it seem to be incorrect/out of date; example 

https://github.com/dotnet/eShopOnContainers/wiki/03.-Setting-the-eShopOnContainers-solution-up-in-a-Windows-CLI-environment-(dotnet-CLI,-Docker-CLI-and-VS-Code)

**Docker-compose -f docker-compose.build.ci.yml up**

should be

**Docker-compose -f docker-compose.ci.build.yml up**

**Comment by CESARDELATORRE** [comment]
Right, it is docker-compose.ci.build.yml
It was right in the detailed instructions but worng in the "summary or main steps"
Thanks for catchin that up!
Fixed already. 

You guys can do a pull request for these kind of typos at the Wiki. 

Thanks for the feedback! :)
