### ISSUE TITLE
Typo in document "architecting-and-developing-containerized-and-microservice-based..." | Section: No-SQL databases as your persistence infrastructure

### ISSUE THREAD

**Issue by thepill** [dotnet/eShopOnContainers#99]
There is a typo on page 153:

`However, when using a No- SQL database, especially a Document-oriented database like Azure Document DB, CouchDB,...`

should be (

`... No-SQL database,...` (removed the space between `No` and `-SQL`

**Comment by CESARDELATORRE** [comment]
Thanks, fixed now in the original WORD document in quite a few other places, too.
I'll be updated in the published .PDF in the next draft version in a few days with new content updates.
Thanks for the feedback! :)
